### ISSUE TITLE
List Znuny on alternativeto.net

### ISSUE THREAD

**Issue by kolbma** [znuny/Znuny#10]
Hello,

probably it would be a good idea to list **Znuny** on https://alternativeto.net/software/otrs/ as an alternative.

**Comment by hanneshal** [comment]
It is pending review / approval for now

![image](https://user-images.githubusercontent.com/804939/108740908-736ae080-7536-11eb-9ac4-8fc91c527ccb.png)

**Comment by hanneshal** [comment]
It is available now. 
Thx for the hint @kolbma
