### ISSUE TITLE
Support Data Collector shows error on Debian 11 (Permission to home folder)

### ISSUE THREAD

**Issue by trentasis** [znuny/Znuny#103]
### Environment

- OS:          Linux
- Browser:      Mozilla Firefox
- Znuny version: 6.0.32

### Expected behaviour

Support Data Collector should be green.

### Actual behaviour

I have a problem with this showing in red.

File System Writable (/bin/, /Kernel/, /Kernel/System/, /Kernel/Output/, /Kernel/Output/HTML/, /Kernel/Modules/)

The file system on your OTRS partition is not writable.

### How to reproduce

1 Recently Installed, OTRS shows a problem in AdminSupportDataCollector.

### Additional information

Znuny just installed on Debian 11, everything is working perfectly except this. I used apt to install it.

**Comment by rkaldung** [comment]
@trentasis Did you run the script `bin/otrs.SetPermissions.pl`? Please delete application cache before you check the result again with the support data collector.

**Comment by rkaldung** [comment]
@trentasis I checked this with Debian 11 and the otrs2 package. The mentioned folders are own by root:root after installing the package. This is related to the Debian package. I recommend contacting the package maintainer, we can't solve this.

**Comment by trentasis** [comment]
Thank you, the script bin/otrs.SetPermissions.pl fixed the problem.
