### ISSUE TITLE
Missing Mozilla::CA on Debian 11

### ISSUE THREAD

**Issue by trentasis** [znuny/Znuny#104]
### Environment

- OS:           Linux
- Browser:     Mozilla Firefox
- Znuny version: 6.0.32-5

### Actual behaviour

I'm having this error:

Perl Modules

Not all required Perl modules are correctly installed.

 Mozilla::CA......................Not installed! (required )

### How to reproduce

1 Recently Installed, OTRS shows a problem in AdminSupportDataCollector.

### Additional information

I have debian 11, and otrs is just installed with apt. Everything works well but can't find the CA. I have installed ca-certificates package.

**Comment by rkaldung** [comment]
@trentasis Which command exactly do you used to install Znuny?

**Comment by rkaldung** [comment]
@trentasis There is something wrong with you setup. Mozilla::CA is bundled with Znuny. Please follow the install instruction properly or ask for support at the [forum](https://community.znuny.org) or via [Discord](https://discord.gg/XTud3WWZTs)

**Comment by trentasis** [comment]
I installed it with apt install otrs in debian 11. Also installed ca-certificates package.

**Comment by rkaldung** [comment]
> I installed it with apt install otrs in debian 11. Also installed ca-certificates package.

@trentasis I tried it with Debian 11 Bullseye with the same result. Please contact the package maintainer. The original source of Znuny conatains the missing package.
