### ISSUE TITLE
Bug - [Postmaster could not process email]

### ISSUE THREAD

**Issue by GeniusM35** [znuny/Znuny#110]
### Environment

- OS:          Centos 7
- Browser:      Chrome
- Znuny version: OTRS 6.0.23

### Expected behaviour

Tickets are generated in time without errors

### Actual behaviour

I'm having some issues with OTRS 6.0.23 when inbound mails are being processed

When the email is sent, some tickets are not created or are not attached to the existing one.

If it is a new email when marking error it is not created, but if later someone answers or resends the original it is created

Checking the communication log I get errors

If I check some in the registry it shows that the ticket is created and later delete

If I try to locate the ticket it doesn't appear when the ticket is new.

Now if the ticket generated an error, some emails reprocess them after 00:10:00 am with the name of STDIN but it is not functional for me because I have spent a lot of time (You can make the emails be reprocessed after a defined time when this error message is flagged and not let it process them after 00:10:00)

Now if the ticket already exists, checking the ticket in the article line appears empty

### How to reproduce

I have no way to reproduce it 

### Screenshots

![image](https://user-images.githubusercontent.com/88741616/129257857-f46650b6-71da-4ad6-b8fd-7bbde965254b.png)

![image](https://user-images.githubusercontent.com/88741616/129258853-b32e313c-1677-4d8a-b9fb-bd32e10d4470.png)

![image](https://user-images.githubusercontent.com/88741616/129258957-3c4eaaaa-2c8a-496d-a2d7-42414dfdd1e0.png)

**Comment by hanneshal** [comment]
Hi @GeniusM35 

if the EML file is processed in the night, it is the Spool Mail Job. Which collects mails that cant be processed on the usual way. This can be the cause when the .procmail config is not correct or the permissions are bad.
If this happens for every E-Mail I would check the procmail log (/opt/otrs/var/log/), /var/log/messages and mail log.

I would suggest to move this to the forum or to discord for two reasons 6.0.23 is outdated and this is most likely a config / setup error, not a bug. 


Forum: https://community.znuny.org
Discord: https://discord.gg/XTud3WWZTs


Regards
Johannes

**Comment by GeniusM35** [comment]
Thanks I upload the topic in discord
