### ISSUE TITLE
Bug - [GenericAgent "next execution time" calculated wrong, depending on timezone]

### ISSUE THREAD

**Issue by paulfolkers** [znuny/Znuny#113]
#### Currently being fixed
_We are already working on a fix, which will be commited here then, so no further action is required yet_
_This issue should just document that this bug is already known_

-------------------

### Environment

- OS: misc. 
- Browser: misc. 
- Znuny version: 6.0.36 

### Expected behaviour
When GenericAgents are configured to be run at time intervals, the next execution time is calculated correct, based on the last execution time.  Timezones should be considered correctly.  
  
Example:
- System time zone: CEST, OTRSTimeZone: Europe/Berlin
- GenericAgent configuration: Automatic execution -> Min: 00, Hour: 11,23, Day: Mon,Tue,Wed,Thu,Fri,Sat,Sun
- Last execution time: 23.08.2021, 11:00:00
- Next execution time: 23.08.2021, 23:00:00

### Actual behaviour
- System time zone: CEST, OTRSTimeZone: Europe/Berlin
- GenericAgent configuration: Automatic execution -> Min: 00, Hour: 11,23, Day: Mon,Tue,Wed,Thu,Fri,Sat,Sun
- Last execution time: 23.08.2021, 13:00:00
- Next execution time: 24.08.2021, 01:00:00

### How to reproduce

1. Setup linux with specific timezone, which is **not** UTC (in our case: CEST)
2. Setup Znuny with your specific SysConfig-setting "OTRSTimeZone" (in our case: Europe/Berlin)
3. Create GenericAgent with automatic execution, e.g. Min: 00, Hour: 23, Day: Mon,Tue,Wed,Thu,Fri,Sat,Sun
4. Run `/opt/otrs/bin/otrs.Console.pl Maint::Daemon::Summary` and the next execution (and last execution) will be wrong.  
In our case with this example it is now the following:  

| Name                                 | Last Execution      | Last Status | Last Duration | Next Execution      |
|--------------------------|------------------|-------------|---------------|-------------------|
| test 23:00:00 uhr                          | 2021-08-23 01:00:00 | N/A         | N/A           | 2021-08-24 01:00:00 |

### Additional information
This problem occurs only when the system time zone is not UTC.  
As far as we could see, the next execution is calculated assuming the system timezone is UTC, then the timezone difference is added (e.g. CEST = +2). Since the system time is already in correct timezone, the timezone does not have to be added here.

### Screenshots
![cron_bug_ga](https://user-images.githubusercontent.com/83212096/130466711-b1e2e6fc-a181-4a49-9bd0-980892df083c.png)
![cron_bug_summary](https://user-images.githubusercontent.com/83212096/130466729-c922251b-f647-4c9d-98fd-e1cb92493a57.png)

**Comment by paulfolkers** [comment]
Wrong, going to be committed again.

**Comment by felixjogris** [comment]
I am still experiencing this on 6.0.38 with OTRSTimeZone set to Europe/Berlin as well. Haven't tried yet, but it might be ok not to convert $StartDateTime/$EventDateTime to/from UTC in Kernel/System/CronEvent.pm. Kernel/System/DateTime.pm calls _AutocorrectNonExistingDateTimeForTimeZone() if creating a CPAN DateTime object fails.

**Comment by paulfolkers** [comment]
Hi @felixjogris, please check the followig PR: https://github.com/znuny/Znuny/pull/124
There is a proposed change to this behaviour, which is not yet implemented.

**Comment by felixjogris** [comment]
Hi @paulfolkers i believe https://github.com/znuny/Znuny/commit/5f87d0ebe28e9d590adb21e931ec8c063f27fa68 fixed this whole datetime vs. daylight savings issue, and thus propose to rollback https://github.com/znuny/Znuny/commit/dc8282e00d72b87d1ca39a9559c0e63a0176810b from Kernel/System/CronEvent.pm.
Tested this on 6.0.38:
```
#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename;
use FindBin qw($RealBin);
use lib dirname($RealBin);
use lib dirname($RealBin) . '/Kernel/cpan-lib';
use lib dirname($RealBin) . '/Custom';

use Kernel::System::ObjectManager;

$Kernel::OM = Kernel::System::ObjectManager->new();

print $Kernel::OM->Create('Kernel::System::DateTime', ObjectParams => {
  Year     => 2022,
  Month    => 3,
  Day      => 27,
  Hour     => 2,
  Minute   => 23,
  TimeZone => "Europe/Berlin",
})->ToString(), "\n";
````
March 27th is going to be a switchover from winter to summer time in Gemany (2am jumps forward to 3am):
```
# ./t.pl
2022-03-27 03:23:00
```
