### ISSUE TITLE
Bug - Link does not work

### ISSUE THREAD

**Issue by rimace** [znuny/Znuny#117]
### Environment

- OS:            Linux
- Browser:       Firefox
- Znuny version:  None

### Expected behaviour

The migration documentation should show up.

### Actual behaviour

A "404" error is returned from the server.

### How to reproduce

1. Go to https://doc.znuny.org/doc/manual/admin/6.0/en/html/updating.html
2. Click on "[converted to the new formats supported by OTRS 6](http://doc.znuny.org/doc/manual/developer/6.0/en/html/package-porting.html#packge-porting-5-to-6-configuration-files)"

**Comment by rkaldung** [comment]
@rimace Thank you for reporting. I fixed the web server configuration.
