### ISSUE TITLE
Bug - UI hang on admin group name change

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#121]
### Environment

- OS:           Linux
- Browser:      FF, Chromium
- Znuny version: 6.0.36

### Expected behaviour

When trying to change admin group name in AdminGroup from admin to admin1 with pressing "Save" warning should be displayed as when one presses "Save and finish".

### Actual behaviour

UI buttons are disabled and nothing happens.

### How to reproduce

In AdminGroup open admin group editor, change its name to admin1 and press Save. UI buttons "Save" and "Save and finish" will be disabled and nothing happens.

### Screenshots

![image](https://user-images.githubusercontent.com/8192649/131351408-05b65aac-518e-4372-9522-9279ec57dd33.png)

**Comment by hanneshal** [comment]
Hi @pboguslawski,

I can confirm that. 

The issue is that the JS Warning Box is not shown when hitting save. 
But the box is shown when you hit "save and finish"

![image](https://user-images.githubusercontent.com/804939/131459321-c9e0aff4-68ac-4421-9f26-2cc0b7344365.png)
