### ISSUE TITLE
Bug - Error Log Message - Missing value for Sat / Sun

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#122]
### Environment

- OS:           macOS
- Browser:      Chrome
- Znuny version: 6.0.36

### Expected behaviour

If I select only some of the days of a WorkingTimeCalendar, I except no error to be written. 

### Actual behaviour

An error is logged:
![image](https://user-images.githubusercontent.com/804939/131857962-35950662-b5de-4bee-a0e2-11b16b5fc2ae.png)

### How to reproduce

Steps to reproduce the behaviour:
- Modify a working time calendar and store it
- Set values Sat / Sun 
- Reset the value for this entry

An empty array is created for Sat / Sun (in this case) and this is parsed and an error is thrown

The issue exists at least since 6.0.28

### Additional information
Stacktrace

```
 Traceback (31011): 
   Module: Kernel::System::SysConfig::ValueType::Select::EffectiveValueGet Line: 171
   Module: Kernel::System::SysConfig::SettingEffectiveValueGet Line: 960
   Module: Kernel::System::SysConfig::SettingGet Line: 373
   Module: Kernel::System::SysConfig::_SettingTranslatedGet Line: 6131
   Module: Kernel::System::SysConfig::ConfigurationTranslatedGet Line: 2139
   Module: Kernel::System::SysConfig::ConfigurationSearch Line: 4376
   Module: Kernel::Modules::AdminSystemConfiguration::Run Line: 264
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 1135
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 38
   Module: (eval) (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 173
   Module: ModPerl::Registry::handler (v1.99) Line: 32
```

My guess would be that a simple check, if a given day has a value would be enough here.

https://github.com/znuny/Znuny/blob/dev/Kernel/System/SysConfig/ValueType/WorkingHours.pm#L128

`next DAY if NoValueGiven`

**Comment by dennykorsukewitz** [comment]
Fixed:
6.0.38 e3fc177
6.2.1    c670cef
