### ISSUE TITLE
Bug - Avoidable error message / entry in logfiles

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny#123]
### Environment

- OS:           n.a.
- Browser:      n.a.
- Znuny version: 6.0.36

### Expected behaviour

No error message when processing e-mails/articles without a subject.

### Actual behaviour

Running commands like `bin/otrs.Console.pl Maint::Ticket::PendingCheck` or executing other actions might lead to log entries like:
```
[Mon Sep  6 09:41:54 2021] otrs.Console.pl: Use of uninitialized value in concatenation (.) or string at /opt/znuny-6.0.36/Kernel/System/EmailParser.pm line 750.
```

### How to reproduce

1. Create an e-mail without a subject and push this e-mail into Znuny
2. Set a pending state on this ticket
3. Wait till the pending time has been reached
4. Execute the pending check

### Additional information

Initially reported in the (https://community.znuny.org/viewtopic.php?f=35&t=42697&p=172938#p172938)[Community forum].

**Comment by dennykorsukewitz** [comment]
Internal merge request was created for:

- 6.0.39
- 6.2.2
- 6.3.1

Waiting for QA.
