### ISSUE TITLE
Bug - Regression Error Message in Log

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#126]
### Environment

- OS:           macOS
- Browser:      Safari
- Znuny version: 6.0.36 & 6.1.1.

### Expected behaviour

If I send a Email reply and no error exists, no error should be written the log.

### Actual behaviour

An error is written every time to the log. 

```
ERROR: OTRS-CGI-89 Perl: 5.30.0 OS: linux Time: Mon Sep 6 13:41:39 2021

 Message: No TicketID is given!

 RemoteAddress: 172.16.39.81
 RequestURI: /otrs/index.pl?

 Traceback (175900):
   Module: Kernel::Output::HTML::Layout::Error Line: 1032
   Module: Kernel::Output::HTML::Layout::ErrorScreen Line: 1013
   Module: Kernel::Modules::AgentTicketCompose::Run Line: 62
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 1136
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 39
   Module: (eval) (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 173
   Module: ModPerl::Registry::handler (v1.99) Line: 32
```

### How to reproduce

1. Create a ticket
2. Reply using a templates
3. Send mail
4. Error is written to the log

### Additional information

The issue was introduced in:

https://github.com/znuny/Znuny/pull/88 proposed by @reneeb 
I think this line is causing the issue:
https://github.com/znuny/Znuny/pull/88/commits/8eb11ab71968d26327bf3f1457ae28d306ff603a#diff-343bf31c8bb9d19c878033dc908936a96ca9213109401adf40731381c141d4f3R49

it only checks on change, which is made every time right before the submit is executed, because the input fields are set to ro. 
The check fails because right at the time of the execution, the popup is already closed. 

Possible solutions (proposal):
1) Perform check for needed attributes before executing the AJAX call
2) Modify the event trigger to listen for content/value change, not a change of the field itself

**Comment by reneeb** [comment]
@hanneshal I already proposed a change: https://github.com/znuny/Znuny/pull/118 

I will work on the requested changes tomorrow...

**Comment by dennykorsukewitz** [comment]
Fixed in 
- 6.0.39
- 6.2.2
- 6.3.1

**Comment by nscblauensteiner** [comment]
6.0.39

**Comment by dennykorsukewitz** [comment]
test
