### ISSUE TITLE
Bug - Need Ticket ID error when switching templates in AgentTicketCommon Modules

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#127]
### Environment

- OS:           macOS
- Browser:      Safari
- Znuny version: 6.0.36 / 6.1.1

### Expected behaviour

I want to switch templates in AgentTicketNote or any other AgentTicketCommon related view, without generating an error message.

### Actual behaviour

If there is no article created by an agent and a user creates a note. An error is logged to the logfile.

### How to reproduce

1. Create a ticket
2. Create two templates of type note and assign them to the ticket queue
2. Open "Note"
3. Select on template, switch to another

### Additional information

The issue is caused when a ticket has no agent article. 
Then L: 1718 throws an error "Need TicketID"

![image](https://user-images.githubusercontent.com/804939/132366462-7b3f2559-2813-4fb6-a107-2a25998aafc6.png)

**Comment by dennykorsukewitz** [comment]
Fixed in:

rel-6_0_38
rel-6_2_1
