### ISSUE TITLE
Inconsistent commit numbers in  rel-6_0 and  rel-5_0 branches

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#13]
Hello,

Seems that znuny/Znuny fork has inconsistent commit numbers with original OTRS/otrs in rel-6_0 and rel-5_0 branches, i.e. corresponding commits

https://github.com/OTRS/otrs/commit/022440711970f725e9a9a4724369e86ba7897ec4
https://github.com/znuny/Znuny/commit/21d654d37481af28e645fed1140c9a60ef7c5e71

have different commit numbers.

Comparison of

https://github.com/OTRS/otrs/commits/rel-6_0?since=2015-08-17&until=2015-08-19
https://github.com/znuny/Znuny/commits/rel-6_0?since=2015-08-17&until=2015-08-19

shows that last consistent commit number is probably

```
Fixes to the JS unit tests
e19c44159ca5211025421157e18ca49f1a79ab58
from 18 Aug 2015 
```

Similar problem seems to exist in rel-5_0 branch.

Inconsistent commit numbers cause conflicts in case one want to merge original OTRS/otrs/rel-6_0 to znuny/Znuny/rel-6_0 (same in opposite direction):

```
git clone https://github.com/znuny/Znuny.git
cd Znuny
git remote add otrsce https://github.com/OTRS/otrs.git
git remote update
git merge otrsce/rel-6_0
# tons of conflicts to resolve here
```
Shouldn't your fork be exact (1:1) copy of original project before forking to avoid conflicts in case contributors want to contribute their work based on repos forked from OTRS/otrs in the past? Introducing new commit numbers in will probably confuse people searching for changes in history based on commit numbers (i.e. from already posted threads on the internet).

Please verify and consider fixing.

Regards,
Paweł

**Comment by pboguslawski** [comment]
Keeping consistent commit numbers will probably be helpful in case of merging future OTRS CE versions, if upstream decides to open in.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski,

thanks for your report and support. 👍🏼

Due to internal filtering there was a change to the CommitIDs.
We will probably change this after the next release.
The commits should be correct again then.

We will keep you up to date here.

Best regards 🚀

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski,

we have resolved the inconsistent and restored all original commit ids.

Thanks for a support. 
Best regards 🚀

**Comment by pboguslawski** [comment]
Hi,

> we have resolved the inconsistent and restored all original commit ids.

Commit ids in rel-6_0 look consistent now - thank you!

Consider similar fixing in rel-5_0 even it's not supported by Znuny; different ids may confuse people searching for changes in history based on commit ids (i.e. from already posted threads on the internet).

Regards,
Paweł

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski 

rel-5_0 - resolved the inconsistent.

Thx Denny
