### ISSUE TITLE
Feature - make Queue clickable in Ticket Information

### ISSUE THREAD

**Issue by dpalic** [znuny/Znuny#132]
The Queue on the right hand side in the detail view of the Ticket named "Ticket Information" is displaying the queue. But sadly you cannot click on the queue to open the queue view. 
Instead you have manually to navigate to the queue, which eats senseless time.

Better:
make the Queue clickable, so the users can jump to the queue with a single click

The href target shall be configurable. e.g. _blank, to avoid that agents loose their written content

**Comment by hanneshal** [comment]
Please see the merge Request https://github.com/znuny/Znuny/pull/152 for more information
