### ISSUE TITLE
Bug - truncation is at a multi-byte-character

### ISSUE THREAD

**Issue by VRDD** [znuny/Znuny#134]
### Environment

- OS:           Linux, Windows
- Browser:      Chrome 
- Znuny version: 6.0.34

### Expected behaviour

If a ticket subject exceeds the max length, it will be shortened. The truncation at the position of a multi-byte-character (UTF-8) shouldn't be done in the middle of this character.

### Actual behaviour

 If a ticket subject exceeds the max length, it will be shortened. If the truncation is done at a multi-byte-character, the output is not ok. It seems to be that the truncation is done after x bytes in the middle of a multi-byte-character.
![Znuny-Bug](https://user-images.githubusercontent.com/63101121/132837757-7a841694-e28a-4f34-ad1b-6dd4121f3eed.png)

### How to reproduce

1. Create a ticket with a subject containing utf-8-Characters. The string should exceed the max length that can be displayed in status view.
2. Select status view

**Comment by hanneshal** [comment]
Hi @VRDD,
can you pass the original mail to bugreport@znuny.com 

Thank you

**Comment by dennykorsukewitz** [comment]
Hi @VRDD,

Since we have not heard from you, we will close the ticket.
If your problem still exists, we are happy to reopen the issue and expect you to send us the original mail or a way to reproduce it.

Thanks 🚀
