### ISSUE TITLE
Feature - Make a znuny maintained debian/ubuntu LTS package 

### ISSUE THREAD

**Issue by dpalic** [znuny/Znuny#135]
the otrs package in ubuntu is really badly maintained and often causing issues on upgrades of the OS.

It would be great to have a Ubuntu LTS package, which is maintained by znuny so users with less experience can easily install znuny latest on their Ubuntu LTS. Since LTS is maintained 5 years the maintenance effort should not be a high effort for the development stream

**Comment by hanneshal** [comment]
Maybe @carnil can something say about this.

We keep our head out of the distro on purpose, but we are happy to assist, if anything is needed. 

Regards

**Comment by dpalic** [comment]
I am sure it will boost the usage of otrs if you provide debian/ubuntu package for the system.

how could a support look like? 
getting push permissions to znuny?

**Comment by hanneshal** [comment]
thanks for the follow up: 

First of all: this is NOT OTR* . We dont use the name for several reasons. One of them is: we dont like to get sued. 
Please respect the new name for future tasks.

As I wrote earlier: we wont get into distro stuff. We just dont. Distros and their repos are maintained by a large community. On of the persons who is already working and maintaining this for debian Patrick. you can find his details here:
https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=otrs2


He can help and I'm sure he is happy when someone joins the team. 

Regards
Johannes
