### ISSUE TITLE
Bug - Exchange Out of Office Replay Messages closes the ticket. 

### ISSUE THREAD

**Issue by fuco809** [znuny/Znuny#138]
### Environment

- OS:           Windows Exchange Mailsystem
- Browser:      Outlook 2019 / Exchange 2016
- Znuny version: 6.0.35

### Expected behaviour
an auto reply (out of office - Abwesenheitsassistent) should not close ticket.

### Actual behaviour
the out of office mail from exchange changes the state of the ticket to close (old state open or wait)

### How to reproduce

only works with real exchange out of office mails, just tried with subject&text -> does not occur.
tried with other mailsystems -> does not occur.

* set ticket state to open or other except close.
* send mail from otrs to an exchange mailadress where out of office is (newly) activated (and not yet tried before)
* wait and check ticket state after answer is arrived in ticket system. (mails are being collected by "postmaster e-mail account")

**Comment by rkaldung** [comment]
@fuco809 Please check the message log from the article which contains the out of office reply. Is there any Postmaster filter which sets the state?

**Comment by fuco809** [comment]
which message log do you mean.

history and otrs.log entries for example:

HISTORY of ticket ...

15.09.2021 09:06:17
AGENT	AKTION	ARTIKEL
-	Status geändert von "pending reminder" auf "closed successful". (StateUpdate)	
-	Wartezeit geändert auf "00-00-00 00:00". (SetPendingTime)	
-	Follow-Up hinzugefügt zu Ticket [2021091533000051]. (FollowUp)	
-	Zurücksetzen des Freigabe-Zeitintervalls. (Misc)	
-	Benachrichtigung "Ticket follow-up notification (unlocked-quickClose)" versandt and "xyz" via "Email". (SendAgentNotification)	
-	Benachrichtigung "Ticket follow-up notification (unlocked-quickClose)" versandt and "xyz2" via "Email". (SendAgentNotification)	
-	Benachrichtigung "Ticket FollowUp - persönlich" versandt and "mymailadress" via "Email". (SendAgentNotification)	

15.09.2021 09:06:35
AGENT	AKTION	ARTIKEL
Johannes Fuchs	Status geändert von "closed successful" auf "pending reminder". (StateUpdate)	
Johannes Fuchs	Wartezeit geändert auf "2021-09-16 09:06". (SetPendingTime)	
Johannes Fuchs	Notiz hinzugefügt (Note). (AddNote)	
Johannes Fuchs	Zurücksetzen des Freigabe-Zeitintervalls. (Misc)	



OTRS.LOG entries ...

...
[Wed Sep 15 09:06:21 2021][Info][Kernel::System::Ticket::Event::NotificationEvent::Transport::Email::SendNotification] Sent agent 'Ticket follow-up notification (unlocked-quickClose)' notification to 'xyz@media-data.at'.
[Wed Sep 15 09:06:21 2021][Info][Kernel::System::Ticket::Event::NotificationEvent::Transport::Email::SendNotification] Sent agent 'Ticket follow-up notification (unlocked-quickClose)' notification to 'xyz2@media-data.at'.
[Wed Sep 15 09:06:21 2021][Info][Kernel::System::Ticket::Event::NotificationEvent::Transport::Email::SendNotification] Sent agent 'Ticket FollowUp - persönlich' notification to 'mymailaddress@domain.at'.
[Wed Sep 15 09:06:22 2021][Debug][Kernel::System::Email::SendExecute][747] Trying to send the email using backend 'Kernel::System::Email::Sendmail'.
[Wed Sep 15 09:06:22 2021][Debug][Kernel::System::Email::SendExecute][747] Trying to send the email using backend 'Kernel::System::Email::Sendmail'.
[Wed Sep 15 09:06:22 2021][Debug][Kernel::System::Email::SendExecute][747] Trying to send the email using backend 'Kernel::System::Email::Sendmail'.
[Wed Sep 15 09:07:53 2021][Debug][Kernel::System::Email::SendExecute][747] Trying to send the email using backend 'Kernel::System::Email::Sendmail'.
...

**Comment by rkaldung** [comment]
@fuco809 This is the log I'm talking about: 
![image](https://user-images.githubusercontent.com/378324/133432482-4e1407f4-0927-4855-89f9-7cec5c0280eb.png)

This shows you easy all involved filters

**Comment by fuco809** [comment]
i found a postmaster filter rule which causes the ticket close, thanks. 
no issue, just a config problem.
