### ISSUE TITLE
Feature: Provide rules (length, regex) for close comment

### ISSUE THREAD

**Issue by dpalic** [znuny/Znuny#142]
Agents are sometimes lazy. Sadly I cannot enforce a minimum requirement on a close comment

my wish here would be:
- provide a configuration to check a minimal length
- provide a configuration to check also against a regex

**Comment by hanneshal** [comment]
Hi @dpalic,
after an internal discussion we wont implement this feature. There are several use-cases where this would cause issues. 
A simple "Thank you" message, which causes a reopen and needs to be closed again for example. 

Also there are several other ways to close tickets (Bulk action, Ticket Merge, Generic Agents, Process Management) which also needed to address to make this feature work. 

We decided to close this issue. If you need something like this custom develop is the ways to go. We can offer help for this or you ask one of the companies who develop for Znuny.

Johannes
