### ISSUE TITLE
Note - Title of Documentation

### ISSUE THREAD

**Issue by derAlff** [znuny/Znuny#15]
Hello,

I have viewed your documentation page https://doc.znuny.org/ . I've seen, that the title of the page is set to "OTRS Documentation". 

You should change this ;P

**Comment by rkaldung** [comment]
Done ;-) At least for the moment.

**Comment by NeverMin** [comment]
Hi @rkaldung , The link of the PDF file needs to be fixed:

e.g.:
`http://ftp.otrs.org/pub/otrs/doc/doc-admin/6.0/en/pdf/otrs_admin_book.pdf`

change to:
`https://ftp.otrs.org.cn/releases/doc/doc-admin/6.0/en/pdf/otrs_admin_book.pdf`

or change to:
`https://download.znuny.org/releases/doc/doc-admin/6.0/en/pdf/otrs_admin_book.pdf`

Or, please tell me where I can find the Git repository for the document.

**Comment by rkaldung** [comment]
@NeverMin Thank you, the linked for the PDF is fixed.
