### ISSUE TITLE
Bug - Dashboard-TicketQueueOverview refresh

### ISSUE THREAD

**Issue by tune6688** [znuny/Znuny#156]
Dear all
I found a new problem, Dashboard-TicketQueueOverview refresh often fails to refresh automatically(Sometimes it works and sometimes it doesn't).
Please check it!
- OS:           <centos8>
- Browser:      <Chrome>
- Znuny version: <61.2>

Thank you for your attention and support!

**Comment by hanneshal** [comment]
I'm sorry but without a more detailed description we cant do a thing here. 
There is a reason why we have this bug template. :shipit: :crystal_ball:

We need at least, browser+version and the OS.

Additional questions: 
Is the refresh working again after you manually refresh the window?
Is there an error in the browser console shown when the refresh stops? 
Is there an error in the Znuny Log and / or in the webserver log?
 
Greetings

**Comment by tune6688** [comment]
Thank for all help !
Sorry for my late response.
Chrome： 94.0.4606.81
OS：Windows10
Zunny：6.12

On the dashboard page, I select the ticket queue overview and some other widgets, and then refresh the page. Sometimes this widget can be triggered to refresh automatically, sometimes not, other widgets are running normally, such as my ticket, and the processed tickets are running normally . The problem that has been found is that the TargetNS.Get function in the Core.Config.js file has added an output debugging statement, as shown in the figure 1.jgp below.
3.jpg

And then we check the results in the browser Cansole, and find that when the variable ConfigLevel is wrong, the control information of QueueOverview cannot be obtained correctly, and when it is correct, it is as that shown in Figure 2.jpg.
2.jpg

When it is wrong, it is as that in Figure 3.jgp
1.jpg
Please help to comment what we should do next to solve the problem?
![3](https://user-images.githubusercontent.com/70299028/137687334-983fc2d2-44e7-4645-af6a-77c0663aff05.jpg)
![2](https://user-images.githubusercontent.com/70299028/137687344-1a3ab473-45f4-40b6-a917-7b93fccefff5.jpg)
![1](https://user-images.githubusercontent.com/70299028/137687347-aa48fcdd-f7c2-4367-a11a-cd89b29f9132.jpg)

**Comment by tune6688** [comment]
To solve this problem, I added the following debugging code: "if (Keys=='QueueOverview') {console.log(ConfigLevel);alert(ConfigLevel[ConfigPrefix + Keys[KeyToken]])},". Through the chrome console output, I found that the QueueOverView object cannot be obtained correctly every time.

**Comment by tune6688** [comment]
Thanks for your help!
