### ISSUE TITLE
[6.0.37] Ticket::Frontend::AgentTicket*###StateDefault not honored

### ISSUE THREAD

**Issue by felixjogris** [znuny/Znuny#158]
Hi,

I upgraded from 6.0.30. 6.0.37 seems to ignore any StateDefault settings for the Ticket::Fronend:AgentTicket* masks. The valid states can be chosen from the dropdowns, but the default state is not selected. I have no ACLs configured. No errors in the log files, no JavaScript issues in my browsers' debug window.
After upgrade, I did the whole otrs.Console.pl Maint::Cache::Delete, Maint::Config::Rebuild --cleanup, Maint::Config::Sync, Maint::Loader::CacheCleanup, Maint::Loader::CacheGenerate, Maint::WebUploadCache::Cleanup, otrs.SetPermissions.pl dance. I also did a git diff rel-6_0_30 rel-6_0_37, and searched in the relevant Perl modules. Also had a look at community.znuny.org. No luck so far.
Is someone else experiencing this? I assume a JavaScript frontend issue.

BR,
Felix

**Comment by dennykorsukewitz** [comment]
Hi @felixjogris,

this sounds like https://github.com/znuny/Znuny/issues/150
Please, check if the settings work in english? `StateDefault`

**Comment by felixjogris** [comment]
@dennykorsukewitz That's it. Too simple. If I switch my agent's language to English, StateDefaults work again. Thank you.
