### ISSUE TITLE
Ticket::Frontend::AgentTicketCompose###StateDefault is being ignored

### ISSUE THREAD

**Issue by hildeb** [znuny/Znuny#159]
Today I upgraded from znuny-6.0.36 to 37, and now Ticket::Frontend::AgentTicketCompose###StateDefault is being ignored.

The current setting is: "erfolgreich geschlossen"

But when I'm answering a ticket, the "next status" field is empty. I can active choose an option, but the "preselection" is gone:

![next_status_empty](https://user-images.githubusercontent.com/2426330/138865697-faccdd2e-9021-4e00-a68d-11ffd24a9dd7.png)
.
![next_status_selection](https://user-images.githubusercontent.com/2426330/138865706-b1d26543-ad33-4ee1-8299-d04de4489ed9.png)

**Comment by dennykorsukewitz** [comment]
Fixed:
lts 6.0.38: f074fe3
dev 6.2.1: 74c3286

**Comment by dennykorsukewitz** [comment]
Check #150
