### ISSUE TITLE
Bug - Undefined subroutine &Kernel::System::Ticket::encode_base64 called at /opt/otrs/Kernel/System/Ticket.pm

### ISSUE THREAD

**Issue by Reedu** [znuny/Znuny#160]
### Environment

- OS:           Debian 10 (Buster)
- Browser:      Firefox 93.0
- Znuny version: 6.1.2

### Expected behaviour

Properly process prepared data

### Actual behaviour

Not making any posts to requested system

### How to reproduce

1. Create webservice with Znuny as Requester, Invoker: Ticket:Generic, and event based on ArticleCreate without additional rules.
2. Add note to ticket.
3. Check if ws debuger log more than : Communication sequence started, Using invoker xxxx ....
4. Check apache error.log

### Additional information

Problem with encode_base64 appeared form me when i've tried to make simple integration with Slack, and Znuny as Requester with invoker based on article events. It died when it was trying to process prepared data (if i'm not mistaken). 
Invokers based on TicketCreate event worked properly. 
WS Debuger showed for TicketCreate event all steps 1-8, but for ArticleCreate it showed only 1-2:
1 Communicationsequnce started
2 Using invoker xxxxx
3 Outgoing data before mapping
4 Outgoing data after mapping
5 URI after interpolating URI params from outgoing data
6 Remaining outgoing data to be send
7 Request params from outgoing data
8 <Response from requested system>

Adding 
use MIME::Base64;  
on begining of Ticket.pm resolved my issue.

**Comment by dennykorsukewitz** [comment]
Fixed:
6.2.1 https://github.com/znuny/Znuny/commit/5db857d156ab10c7c75ad510e3c2688db22b46ff
