### ISSUE TITLE
CPANUpdate on FreeBSD

### ISSUE THREAD

**Issue by papeng** [znuny/Znuny#162]
Greetings

As recommended in the last newsletter email, I ran the following command to update the CPAN module Mozilla::CA:

```
otrs/bin/otrs.Console.pl Dev::Code::CPANUpdate --mode stable
```

### Environment

- OS:           FreeBSD 12.2
- Browser:      None (CLI)
- Znuny version: 6.0.36

### Expected behaviour

```
$ otrs/bin/otrs.Console.pl Dev::Code::CPANUpdate --mode stable
Updating CPAN::Audit...
Updating Mozilla::CA...
```

### Actual behaviour

```
$ otrs/bin/otrs.Console.pl Dev::Code::CPANUpdate --mode stable
Updating CPAN::Audit...
tar: Error opening archive: Failed to open '/dev/sa0'
Error: Download and/or file extraction of https://cpan.metacpan.org/authors/id/V/VT/VTI/CPAN-Audit-0.15.tar.gz failed. at <redacted>/otrs/Kernel/System/Console/Command/Dev/Code/CPANUpdate.pm line 161.
```

### How to reproduce

1. Run `otrs/bin/otrs.Console.pl Dev::Code::CPANUpdate --mode stable` on a FreeBSD machine

### Additional information
I'm guessing the reason for this issue is the difference between `bsdtar` and GNU `tar`.

Following the explaination in https://unix.stackexchange.com/a/131053, I made the following changes in `otrs/Kernel/System/Console/Command/Dev/Code/CPANUpdate.pm` on line 138:

```diff
-    system("cd $TmpDir; wget -q -O - $DownloadURL | tar -xz --strip 1");
+    system("cd $TmpDir; wget -q -O - $DownloadURL | tar -xzf - --strip 1");
```

which resolved the issue.

This change should also work for systems with GNU tar and therefore I think this could be easily fixed.

**Comment by hanneshal** [comment]
@rkaldung what do you think. I checked the three major OSs we use (CentOS, Debian, macOS) all support 
the "-f" flag

**Comment by rkaldung** [comment]
I fully agree, using the switch`f` and `-` for STDIN works.

**Comment by rkaldung** [comment]
@jepf Please take car of this

**Comment by jepf** [comment]
@papeng 

Thanks for reporting the issue and for your fix. It will be part of Znuny releases 6.0.39 and 6.2.2.
