### ISSUE TITLE
Question about support timeframes and releases

### ISSUE THREAD

**Issue by tgurr** [znuny/Znuny#163]
Now that the second feature release appeared I got some questions about the support timeframes.

There's Znuny LTS for 6.0.x (which we currently use) and then there's been the first feature release 6.1.x which we want(ed) to make use of because of the new features. But we have a small Addon programmed by Znuny `Znuny4OTRS-TicketCounterAttributeBased` which required some modifications for the new framework version and also depends on another Znuny package `Znuny4OTRS-DatabaseBackend` so we issued an order to have these updated to 6.1.x these days.

But just now 6.2.x appeared, which was of course clear on the roadmap https://www.znuny.org/en/roadmap. But what I didn't assume is that we have the same problem yet again. I read in the release notes that the changes this time are probably minor but it's hard/impossible to justify spending money in such short timeframes of like 3-4 months.

So since I couldn't find any clear statements, is it even planned to provide patch releases for the feature/minor releases 6.1.x / 6.2.x even after the next feature release manifested, for the likes of maybe ~1 year or isn't this planned at all?

I guess I'm not the only one who would love to make use of features introduced by the feature releases but now stands infront of a problem like this.

And if the feature releases won't get support / patch releases, when is a new "LTS" release planned? Since there's also no information in this reagard on the roadmap yet. I'm missing something along the likes of e.g. https://nodejs.org/en/about/releases/ with a clear overview, support timeframes and end-of-life dates.

**Comment by hanneshal** [comment]
Hello @tgurr,

we do not plan to have minor patch updates after the release of a newer version. So after 6.2 is released no more updates for 6.1 will be released. 
We are working on resolving the packaging issues and automate the whole process on the long run. But we are not there yet. 

If you want to update to 6.2 just pass us a mail and we take care about this for you for free. So you can just follow the path. 

New LTS releases cant be planned that easily, so there is no roadmap. We just maintain the current state and fix security issues and bugs. The last release was ~a week ago. 
See [znuny.org](https://www.znuny.org/en/releases/znuny-6-0-38) . 

If there is no security related context, the LTS release is usually done together with the feature releases.

Hope this helps to plan accordingly.

Regards
Johannes
