### ISSUE TITLE
"No TicketID is given!" on each outgoing reply

### ISSUE THREAD

**Issue by sergiykhan** [znuny/Znuny#170]
While working on switching from OTRS 6.0.30 to Znuny 6.0.38, I noticed the following issue in Znuny.

### Environment
- OS: CentOS Linux release 7.9.2009 (Core)
- Browser: Chrome 95.0.4638.69 (Official Build) (64-bit)
- Znuny version: 6.0.38

### Expected behaviour
Agent's ticket replies should not generate in otrs.log the error
```
[Error][Kernel::Output::HTML::Layout::Error][1030] No TicketID is given!
```

### Actual behaviour
Every agent's reply on an existing ticket generates the `No TicketID` error line following the `ArticleSend` log message.
```
[Fri Nov  5 19:44:43 2021][Info][Kernel::System::Ticket::Article::Backend::Email::ArticleSend] Queued email to '"XXX" <XXX>' from 'xxx'. HistoryType => SendAnswer, Subject => Re: [Ticket#0143090] eee;
[Fri Nov  5 19:44:44 2021][Error][Kernel::Output::HTML::Layout::Error][1030] No TicketID is given!
```

### How to reproduce
Click reply on an existing ticket, select a template, the click "Send mail", watch otrs.log.

### Additional information
* The message appears only for existing tickets. For a new email outgoing ticket generated by an agent, it does not appear.
* The issue is not present in OTRS 6.0.30

**Comment by sergiykhan** [comment]
The error appears to be coming from `CheckSubject` as suggested here https://community.znuny.org/viewtopic.php?f=35&t=42655

If I replace `var/httpd/htdocs/js/Core.Agent.TicketCompose.js` with that from OTRS 6.0.30, the error goes away. The only change I see in that file is related to `CheckSubject`, nothing else.

**Comment by sergiykhan** [comment]
The patch proposed in that community post https://community.znuny.org/viewtopic.php?f=35&t=42655 by @reneeb worked for me as well although I am not sure if this is simply a temporary workaround until a proper solution is in place.

```
--- Core.Agent.TicketCompose.js.znuny   2021-11-05 23:52:03.883316887 +0000
+++ Core.Agent.TicketCompose.js 2021-11-06 00:34:59.693209401 +0000
@@ -77,6 +77,12 @@
         var CurrentSubject = $('#Subject').val();
         $('#SubjectWarning').remove();

+        var ForTicketID = $('input[name=TicketID]').val();
+
+        if ( !ForTicketID ) {
+            return;
+        }
+
         $.ajax({
             url: Core.Config.Get('Baselink'),
             type: 'POST',
@@ -84,7 +90,7 @@
                 Action: Core.Config.Get('Action'),
                 Subaction: 'CheckSubject',
                 Subject: CurrentSubject,
-                TicketID: $('input[name=TicketID]').val(),
+                TicketID: ForTicketID,
             },
             success : function(Response) {
                 if (Response.Empty) {

```

**Comment by hanneshal** [comment]
Hi @sergiykhan 

thanks for creating an issue for this. 
There is already a PR from @reneeb which just needs some tweaking I guess.
Link: https://github.com/znuny/Znuny/pull/133

@dennykorsukewitz can you take a look here please.

Thanks

**Comment by dennykorsukewitz** [comment]
I have previewed the PR and made some suggestions. 
@reneeb still has to accept these suggestions before we go any further.

**Comment by reneeb** [comment]
@dennykorsukewitz I've updated the PR...

**Comment by dennykorsukewitz** [comment]
Fixed in 
- 6.0.39
- 6.2.2
- 6.3.1
