### ISSUE TITLE
Bug - Error "Parameter 'Config' must be a hash ref with data!"

### ISSUE THREAD

**Issue by meisterheister** [znuny/Znuny#173]
Since updating from Znuny 6.0.36 to 6.0.38 I experience the same error in my logs every time I just run "/bin/otrs.Console.pl Maint::Cache::Delete".

Possibly found the change that's now leading to the error, _SanitizeConfig() has been introduced in the following change in 6.0.37

[2021-09-27 JavaScript in the error message of regular expression checks for dynamic field values now will be removed instead of being executed when showing the error message. Thanks to Stefan Härter (OTOBO) for reporting the issue.](https://github.com/znuny/Znuny/commit/513aed0473b66f3e205265b928176cf3deb725fb)

### Environment

- OS:           Ubuntu 18.04
- Browser:      Does not matter
- Znuny version: 6.0.38

### Expected behaviour

I expect to get no error.

### Actual behaviour

ERROR: OTRS-otrs.Console.pl-Maint::Stats::Dashboard::Generate-10 Perl: 5.26.1 OS: linux Time: Mon Nov 22 12:30:12 2021

```
 Message: Parameter 'Config' must be a hash ref with data!

 Traceback (16944): 
   Module: Kernel::System::DynamicField::_SanitizeConfig Line: 1728
   Module: Kernel::System::DynamicField::DynamicFieldGet Line: 303
   Module: Kernel::System::DynamicField::DynamicFieldListGet Line: 1021
   Module: Kernel::System::Stats::Dynamic::TicketAccountedTime::new Line: 44
   Module: Kernel::System::Stats::GetObjectBehaviours Line: 1134
   Module: Kernel::System::Stats::StatsGet Line: 273
   Module: Kernel::System::Stats::StatsResultCacheCompute Line: 1676
   Module: Kernel::System::Console::Command::Maint::Stats::Dashboard::Generate::Run Line: 150
   Module: (eval) Line: 461
   Module: Kernel::System::Console::BaseCommand::Execute Line: 455
   Module: (eval) Line: 145
   Module: Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker::Cron::Run Line: 124
   Module: Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker::Run Line: 236
   Module: (eval) Line: 331
   Module: main::Start Line: 331
   Module: /opt/otrs/bin/otrs.Daemon.pl Line: 152
```

### How to reproduce

Just need to run `/bin/otrs.Console.pl Maint::Cache::Delete` and get:
`Mon Nov 22 12:51:27 2021;;error;;OTRS-CGI-10;;Parameter 'Config' must be a hash ref with data!`

**Comment by meisterheister** [comment]
Issue is related to Dynamic Fields created by importing Ready2Adopt process [Import Ready2Adopt process](https://doc.otrs.com/doc/manual/admin/6.0/en/html/process-management.html#id-1.7.3.6) in Process Management.

**Workaround:** Open the Dynamic Fields PreProcDaysRemaining, PreProcDaysUsed, PreProcEmergencyTelephone and PreProcProcessStatus and just press 'Save' which will update the Configuration and set the required keys and values.

Opened PR: https://github.com/znuny/Znuny/pull/174

**Comment by dennykorsukewitz** [comment]
Hello @meisterheister,

thanks for your issue and the pull request.
I will definitely merge your PullRequest.

According to the original code, the `Config` does not have to be filled.
Therefore, the new code is actually too strict [here](https://github.com/znuny/Znuny/blob/dev/Kernel/System/DynamicField.pm#L1727-L1733 ).

I will discuss this with my colleagues and probably remove this check again.

Thanks 🚀

**Comment by meisterheister** [comment]
Hi @dennykorsukewitz,

> According to the original code, the `Config` does not have to be filled. Therefore, the new code is actually too strict [here](https://github.com/znuny/Znuny/blob/dev/Kernel/System/DynamicField.pm#L1727-L1733).

Yes I was actually thinking the same. My PR would not solve this issue for everyone already having Dynamic Fields without `Config ` and since there is a Community Post [Parameter 'Config' must be a hash ref with data!](https://community.znuny.org/viewtopic.php?f=35&t=42837) showing this is not an issue only related to Process Management I would assume there are many cases where this issue arises.

**Comment by dennykorsukewitz** [comment]
Fixed via https://github.com/znuny/Znuny/commit/e6c477c5c5f6a7b8085f2c644710306b74b80d59 and https://github.com/znuny/Znuny/commit/87592e8d97560298e0831cd119d1ba8bdc9e886b

- 6.0.39
- 6.2.2
- 6.3.1
