### ISSUE TITLE
Bug - The page refresh stops the fulltext search via toolbar.

### ISSUE THREAD

**Issue by iwillforce** [znuny/Znuny#182]
### Environment

- OS:    Windows 11 Pro       
- Browser:   Chrome 96   
- Znuny version: Znuny 6 Lts 

### Expected behaviour

When i started a search and the result takes some time, the reloading from autorefresh should have no impact, and in turn not interrupt the search.

### Actual behaviour

If i set autorefresh to a low interval time to reload (5-10 seconds), the search is stopped.
This happens in next views (as i can see): AgentDashboard and AgentTicketQueue

### How to reproduce

I add more refresh interval times due to some specification of my organization. In this case, we are using 10 seconds (image above).
Here: PreferencesGroups###RefreshTime
Next: We set this refresh interval time in personal preferences on each agent
![image](https://user-images.githubusercontent.com/33241171/148193452-2115621d-4137-4167-8600-563d9ab39fbf.png)

### Screenshots

![image](https://user-images.githubusercontent.com/33241171/148192136-68842552-cff2-4747-8171-7c45d3a7ad2b.png)

**Comment by dennykorsukewitz** [comment]
Hi, @iwillforce

I could not reproduce the bug in either LTS 6.0.39 or the latest Znuny 6.2.2. 
Please let me know your version.

Can you please check if you have enabled the 'JS loader cache'. SysConfig: 'Loader::Enabled::JS'.  

You can execute the following commands on the console to delete the cache.

bin/otrs.Console.pl Maint::Cache::Delete
bin/otrs.Console.pl Maint::Loader::CacheCleanup

Otherwise you would have to check whether the var/httpd/htdocs/js/Core.App.js is identical to the framework version. 

Best regards 🚀

**Comment by iwillforce** [comment]
> 
Version --> 6.0.29
Loader::Enabled::JS --> Enable
bin/otrs.Console.pl Maint::Cache::Delete --> Done
bin/otrs.Console.pl Maint::Loader::CacheCleanup --> Done
/httpd/htdocs/js/Core.App.js --> Checked
![image](https://user-images.githubusercontent.com/33241171/148262187-30e3431a-c2ad-42ba-b004-ef6b85a40a03.png)

Moreover, the search is done via "toolbar"
![image](https://user-images.githubusercontent.com/33241171/148263988-e130e983-3b51-44ef-a02c-9ade149085f4.png)

**Comment by dennykorsukewitz** [comment]
Hi @iwillforce,

It's all in the way the search is done.
There is no problem with the pop-up search.

Via the TicketSearchFulltext toolbar, the page is then updated without checking.
To prevent this, we can include the following code.

Could you check this in your test environment and give me feedback accordingly?

Please replace the content of the function `TargetNS.Init` with the code below in `var/httpd/htdocs/js/Core.App.js`

```js

    /**
     * @name Init
     * @memberof Core.App
     * @function
     * @description
     *      This function initializes the special functions.
     */
    TargetNS.Init = function () {
        var RefreshSeconds = parseInt(Core.Config.Get('Refresh'), 10) || 0;

        if (RefreshSeconds !== 0) {
            window.setInterval(function() {

                // If there are any open overlay dialogs, don't refresh
                if ($('.Dialog:visible').length) {
                    return;
                }

                // If there are open child popup windows, don't refresh
                if (Core && Core.UI && Core.UI.Popup && Core.UI.Popup.HasOpenPopups()) {
                    return;
                }

                // If there is an input value in the toolbar TicketSearchFulltext, don't refresh
                if ($('#Fulltext') && $('#Fulltext').val().length) {
                    return;
                }

                // Now we can reload
                window.location.reload();
            }, RefreshSeconds * 1000);
        }

        // Initialize return to previous page function.
        TargetNS.ReturnToPreviousPage();
    };

```

**Comment by iwillforce** [comment]
Hi @dennykorsukewitz,
Super! Works like a charm

**Comment by dennykorsukewitz** [comment]
Thank you for the feedback. 🚀 
I will prepare the code change internally.
