### ISSUE TITLE
Bug - No Ticket-Agent notification sent out despite selected queues in personal preferences from agent user

### ISSUE THREAD

**Issue by safespace022025** [znuny/Znuny#186]
### Environment

- OS:           centOS 7 
- Browser:     Firefox ESR, brave, edge
- Znuny version: 6.0.39

### Expected behaviour

After sending an e-mail to a queue ticket agents normally get an E-Mail-Notification that there is a new ticket. If I look at the ticket history from version 6.0.38 there as an action for agent notification:
![image](https://user-images.githubusercontent.com/93199366/148792664-d7350a07-1ce7-4fbb-b979-945387db6fb1.png)

### Actual behaviour

currently there are no notification an agent can select under personal preferences:
![image](https://user-images.githubusercontent.com/93199366/148792228-a87415ab-b28f-4431-ba68-c9d4701d0d4e.png)

Under Ticket history its visable that no notification has been sent:
![image](https://user-images.githubusercontent.com/93199366/148792454-6319b441-d54a-4387-8321-a4fb173457e0.png)

### How to reproduce

use release 6.0.39

**Comment by rkaldung** [comment]
@dignin Please verify

**Comment by dignin** [comment]
I cannot verify this. If the user has subscribed to the queue, and a new ticket is created, then a mail is sent. Check the user and notification settings and resave them. Maybe that helps. @mainik27 

### History
![image](https://user-images.githubusercontent.com/891283/148975669-bbbe518a-7044-4dd9-8329-0de9ff3a37f7.png)


### User Settings
![image](https://user-images.githubusercontent.com/891283/148975832-2715e5a5-4465-4790-ba68-f7a6d02f7c5a.png)


###  Notification Settings

![image](https://user-images.githubusercontent.com/891283/148975917-f1714ae5-eb6b-4fb1-9808-68be0fe26f73.png)

**Comment by hanneshal** [comment]
@mainik27 Maybe we can discuss this "live" at discord at some time. After you checked and re saved the notifications, it would help to have a look at the communication protocol. What actually happens when processing the mail.

**Comment by safespace022025** [comment]
Hello @dignin, sorry I didnt mention that I already tried to resave these personal preferences -> still no notification.
As I didnt touch the Ticket Notification Management it is enabled like it should:
![image](https://user-images.githubusercontent.com/93199366/149084411-ef823387-3815-421b-8356-2185832677e9.png)

@hanneshal here an communication log for an incomingf TestMail

1		Kernel::System::PostMaster	From: XYZ <XYZ>	01/12/2022 08:33:13
2		Kernel::System::PostMaster	To: OTRS <>	01/12/2022 08:33:13
3		Kernel::System::PostMaster	Subject: TestMsail	01/12/2022 08:33:13
4		Kernel::System::PostMaster	Message-ID: <XXXX>	01/12/2022 08:33:13
5		Kernel::System::PostMaster	Message-Id: <XXX>	01/12/2022 08:33:13
6		Kernel::System::PostMaster::FollowUpCheck::BounceEmail	Searching for header X-OTRS-Bounce.	01/12/2022 08:33:13
7		Kernel::System::PostMaster::FollowUpCheck::Subject	Searching for TicketNumber in email subject.	01/12/2022 08:33:13
8		Kernel::System::PostMaster::FollowUpCheck::References	Searching for TicketID in email references.	01/12/2022 08:33:13
9		Kernel::System::PostMaster::Filter::DetectBounceEmail	Checking if is a Bounce e-mail.	01/12/2022 08:33:13
10		Kernel::System::PostMaster::Filter::MatchDBSource	Filter: 'Filter it-support auto response' 'XXXY <>' =~ /XXXY/i matched NOT!	01/12/2022 08:33:13
11		Kernel::System::PostMaster::Filter::MatchDBSource	Filter: 'Filter XXX auto response' 'XXX <>' =~ /XXX/i matched NOT!	01/12/2022 08:33:13
12		Kernel::System::PostMaster::FollowUpCheck::BounceEmail	Searching for header X-OTRS-Bounce.	01/12/2022 08:33:13
13		Kernel::System::PostMaster::FollowUpCheck::Subject	Searching for TicketNumber in email subject.	01/12/2022 08:33:13
14		Kernel::System::PostMaster::FollowUpCheck::References	Searching for TicketID in email references.	01/12/2022 08:33:13
15		Kernel::System::PostMaster::NewTicket	Take UserLogin (XXX) from customer source backend based on (XXX).	01/12/2022 08:33:13
16		Kernel::System::PostMaster::NewTicket	Take UserCustomerID (XXXX) from customer source backend based on (XXXX).	01/12/2022 08:33:13
17		Kernel::System::PostMaster::NewTicket	Going to create new ticket.	01/12/2022 08:33:13
18		Kernel::System::PostMaster::NewTicket	New Ticket created: TicketNumber: 4232198 TicketID: 47963 Priority: 3 normal State: new CustomerID: XXX CustomerUser: XXX	01/12/2022 08:33:14
19		Kernel::System::PostMaster::NewTicket	Going to create new article for TicketID '47963'.	01/12/2022 08:33:14
20		Kernel::System::PostMaster::NewTicket	Charset: utf-8	01/12/2022 08:33:14
21		Kernel::System::PostMaster::NewTicket	Content-Type: text/plain	01/12/2022 08:33:14
22		Kernel::System::PostMaster::NewTicket	EmailFrom: XXXX	01/12/2022 08:33:14
23		Kernel::System::PostMaster::NewTicket	From: xxx <>	01/12/2022 08:33:14
24		Kernel::System::PostMaster::NewTicket	Message-ID: <xxxx>	01/12/2022 08:33:14
25		Kernel::System::PostMaster::NewTicket	Message-Id: <xxxx>	01/12/2022 08:33:14
26		Kernel::System::PostMaster::NewTicket	SenderEmailAddress: xxx 01/12/2022 08:33:14
27		Kernel::System::PostMaster::NewTicket	Subject: TestMsail	01/12/2022 08:33:14
28		Kernel::System::PostMaster::NewTicket	To: OTRS <>	01/12/2022 08:33:14
29		Kernel::System::PostMaster::NewTicket	X-OTRS-AttachmentCount: 0	01/12/2022 08:33:14
30		Kernel::System::PostMaster::NewTicket	X-OTRS-AttachmentExists: no	01/12/2022 08:33:14
31		Kernel::System::PostMaster::NewTicket	X-OTRS-CustomerNo: xxx	01/12/2022 08:33:14
32		Kernel::System::PostMaster::NewTicket	X-OTRS-CustomerUser: xxx	01/12/2022 08:33:14
33		Kernel::System::PostMaster::NewTicket	X-OTRS-FollowUp-SenderType: customer	01/12/2022 08:33:14
34		Kernel::System::PostMaster::NewTicket	X-OTRS-SenderType: customer	01/12/2022 08:33:14
35		Kernel::System::PostMaster::NewTicket	X-Sender: xxx	01/12/2022 08:33:14

**Comment by hanneshal** [comment]
Hi @mainik27 
if set a specific recipient in the notification, different from the actual sender. Is it sent? 

regards
Johannes

**Comment by safespace022025** [comment]
Hello @hanneshal, no. I also discovered that Ticket notes also not beeing sent to an Agent, while its enabled:
![image](https://user-images.githubusercontent.com/93199366/149089735-7152b213-994c-4a30-a6fa-2af9848cdb16.png)

**Comment by hanneshal** [comment]
I would say: contact support@znuny.com we need to have a look on your system. 

We will find a slot somewhere this week.

**Comment by hanneshal** [comment]
Follow Up: After setting the notifications to invalid and back to valid again, everything works fine.

**Comment by Oestle** [comment]
We noticed the same issue. Seems to have appeared after we updated from 6.0.37 to 6.0.39.
We already tried setting all notifications to invalid then back to valid again, apply/change agent notification settings, restarting the otrs daemon, disabling and reenabling some (potentially) related settings in the system configuration, but so far our agents are not receiving notifications.
Any more ideas what we could check?

**Comment by hanneshal** [comment]
Trigger a notification event and please check the Logfile if there is anything to be found. 
It is not triggered at all or just not sent?

Question: Did you used the migrate.pl script after the update?

**Comment by Oestle** [comment]
Thanks for the quick response.

I'm guessing you're talking about the DBUpdate-to-6.pl script?
I don't think we ran it during the update from 6.0.37 to 6.0.39, but i just ran it and it didn't change the behaviour.

When i trigger a notification event (by creating a new ticket via email) i can't seem to find any notification related logs. 
I can see the auto response in the communication log being sent to the address that created the ticket and i would expect to see more entries in that log with all the notification mails going to the agents but there are none.

**Comment by hanneshal** [comment]
Please have a look at the Znuny Log (Admin->System Log)

The communication log wont help here.

**Comment by Oestle** [comment]
There's just these three lines (names and addresses removed):
`

Tue Mar 1 16:48:21 2022 (Europe/Berlin) | info | OTRS-CGI-10 | Sent auto response (SendAutoReply) for Ticket [2022030110000361] (TicketID=57416, ArticleID=255150) to 'xxx <xxx>'.
-- | -- | -- | --
Tue Mar 1 16:48:21 2022 (Europe/Berlin) | info | OTRS-CGI-10 | Queued email to 'xxx <xxx>' from 'xxx <xxx>'. HistoryType => SendAutoReply, Subject => RE: Notification-Test [Ticket#2022030110000361];
Tue Mar 1 16:48:20 2022 (Europe/Berlin) | info | OTRS-CGI-10 | New Ticket [2022030110000361/Notification-Te] created (TicketID=57416,Queue=xxx,Priority=3 normal,State=new)

`

**Comment by hanneshal** [comment]
Ok, thats not much :D
Please send your contact details to bugreport@znuny.com, we get in touch and have a look together on your instance. maybe we can find an easy solution.

**Comment by akmet** [comment]
@Oestle @hanneshal I noticed the same behaviour on my instance. Did you solved your problem? Any hint would be helpful. Otherwise I would contact bugreport@znuny.com too.

**Comment by hanneshal** [comment]
No, we scheduled a date for next week.
But you can post the information I requested from @Oestle before.

Edit: to be more precise.
- what did you change before the behavior was first noticed
- what do the log(s) say at the time you expect the notification
- what kind of notifications are you missing (triggered event, Recipients...)
- what version are you using

**Comment by hanneshal** [comment]
@akmet we resolved the issue. The setup on @Oestle instance was a bit of. 
It used an old sysconfig, dated from 2018, and not the new files. So basically a setup / user error.
