### ISSUE TITLE
Bug - Notifications: Empty Variable <OTRS_CUSTOMER_Body[30]> when creating Phone/Process Tickets

### ISSUE THREAD

**Issue by lukaskress** [znuny/Znuny#188]
### Environment

- OS:           Ubuntu 20
- Znuny version: 6.2.1

### Expected behaviour

A ticket gets created via AgentTicketPhone and I configured a Ticket Notification, so the customer user gets an email with the content of the ticket (Body). The customer user should get a notification with the body that was filled in at AgentTicketPhone.

### Actual behaviour

The variable <OTRS_CUSTOMER_Body[30]> is empty and only shows "-".

### How to reproduce

1. Create a ticket notification that sends a mail to the customer user (see screenshots below)
2. Create a PhoneTicket (see sceenshots below)
4. Look at the notification in the frontend/received email

### Screenshots
![Notification1](https://user-images.githubusercontent.com/38035605/149489614-0064837e-c7de-46c1-87c7-d67bc1493f41.PNG)
![Notification2](https://user-images.githubusercontent.com/38035605/149489619-583f93ee-f1a9-4fa6-a116-8caed53f8e4b.PNG)
![TicketCreate](https://user-images.githubusercontent.com/38035605/149489621-5889f7b2-2d0f-40f4-a800-abca6b5dc8dc.PNG)
![zoom1](https://user-images.githubusercontent.com/38035605/149489623-a0324221-7a87-4feb-83b1-674f2ad39b52.PNG)
![zoom2](https://user-images.githubusercontent.com/38035605/149489626-7d445145-f7aa-4575-b49c-7346ce74ceea.PNG)

**Comment by hanneshal** [comment]
Hi @lukaskress 

could you please try  this tag:
<OTRS_CUSTOMER_BODY[30]>

Body vs BODY

**Comment by lukaskress** [comment]
Hi   @hanneshal 

Thanks for the reply. You are right, it is case sensetive.
I tried this in my notifications:

<OTRS_CUSTOMER_REALNAME> wrote:
Email:
<OTRS_CUSTOMER_Email[30]>
BODY:
<OTRS_CUSTOMER_BODY[30]>
EMAIL:
<OTRS_CUSTOMER_EMAIL30]>
Body:
<OTRS_CUSTOMER_Body[30]>
![notification_all](https://user-images.githubusercontent.com/38035605/149497550-24e928a4-bfb2-4f3f-8e21-ebe34e3c3fba.PNG)
![zoom_all](https://user-images.githubusercontent.com/38035605/149497567-47924304-48d4-4c08-8cb4-700da57ea78f.PNG)

It is working with BODY, so I am wrong and it's not a bug. I would suggest to edit the example notification, that gets displayed in the notification settings. 

![notification_example](https://user-images.githubusercontent.com/38035605/149497578-96c4e403-f3d0-419b-859e-39115fcdafad.PNG)

**Comment by hanneshal** [comment]
Perfect. Thanks for the feedback.

>  I would suggest to edit the example notification, that gets displayed in the notification settings.

will do: @dignin can you put this on the list for future updates. 
The template shown in the notifications (and maybe somewhere else) needs to be updated

**Comment by dignin** [comment]
Issue fixed in [PR 191](https://github.com/znuny/Znuny/pull/191)
