### ISSUE TITLE
Bug - double encoding for dynamic field filters in ticket overviews 

### ISSUE THREAD

**Issue by J-Beckmann** [znuny/Znuny#194]
### Environment

- OS:           Windows 
- Browser:     Firefox 
- Znuny version: 6.0.x LTS 

### Expected behaviour

Dynamic Fields with "withespaced values" should filter the Tickets correcty...

### Actual behaviour

The actual behavior is very common to Bug #51 : Instead of %20 the URL encodes to %2520 if a dynamicField value contains a whitespace.

### How to reproduce

-     Create a dynamic field (type dropdown) and create the key "value 1".
-     Create a Ticket and add the dynamic field value with the key "value 1".
-     Add the dynamic field to the settings for "AgentTicketStatusView".
-     Go to the TicketStatusView and filter the Tickets for "value 1"
-     Expected result: the created ticket is shown.
-     Current result: no ticket is shown.

### Additional information

Current URL Example:
....znuny/index.pl?[SomeMoreValues...]ColumnFilterDynamicField_Anlagennummer=value**%2520**1;

Excpected and working URL Example:
....znuny/index.pl?[SomeMoreValues...]ColumnFilterDynamicField_Anlagennummer=value**%20**1;

**Comment by hanneshal** [comment]
Hi @J-Beckmann 
can you please specify the exact version you are using. 

Thanks

**Comment by J-Beckmann** [comment]
Hi @hanneshal ,

our Demo-System seems to be running on Version 6.0.31. Would be nice if it would be noted in the JavaScript-Console or via the Logo-Mouseover, but all I get is:

![grafik](https://user-images.githubusercontent.com/32959383/151234083-1fc4a0ce-4908-4f64-b0f5-22feb3735154.png)

**Comment by hanneshal** [comment]
I would suggest you test it against 6.0.37+ the reference to #51  you posted is a merge request, not an issue. 
It should be fixed in 6.0.37+

Regards

**Comment by J-Beckmann** [comment]
Ah I see.
I tried to check wether the bug was reported before an found it, but didn't notice it was already taken care of.
After updating our Instance I will check again!
Thank you for the explanation.
