### ISSUE TITLE
Feature request: Automatic setting of the owner in the ticket process

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#201]
The ticket owner should be automatically changed to the logged-in agent when clicking "submit" in the activity dialog. This prevents the owner agent from potentially still being the default agent until the end of the process because eventually the agents forgot to change the ownership.

![image](https://user-images.githubusercontent.com/72391822/151837598-39496b69-46b5-492b-91d5-025532c8b562.png)

For that I expanded the https://github.com/znuny/Znuny/blob/dev/Kernel/System/ProcessManagement/TransitionAction/TicketOwnerSet.pm near the line 95:

`

    my $Success = $Self->_CheckParams(
        %Param,
        CommonMessage => $CommonMessage,
    );
    return if !$Success;
    ########
    if ($Param{Config}->{Owner} eq "<OTRS_CURRENT_UserLogin>"){
        # Take logged-in agent as new owner
        $Param{Config}->{OwnerID}=$Param{UserID};
    }
    ########
    # override UserID if specified as a parameter in the TA config
    $Param{UserID} = $Self->_OverrideUserID(%Param);

    # use ticket attributes if needed
    $Self->_ReplaceTicketAttributes(%Param);
    $Self->_ReplaceAdditionalAttributes(%Param);

`
The configuration of the transaction-actions for the TicketOwnerSet is:
![image](https://user-images.githubusercontent.com/72391822/151835292-ac6728ea-d921-49d8-86f3-28b9b3d42fa7.png)

My solution is just a rudimentary suggestion that shows how it works. It is prooven on version 6.2.2. The code might have to be improved to be included in the next Znuny version.

**Comment by rkaldung** [comment]
Hi @schnudd31do3,

There is no need for this change. The transition action your screenshot is showing already works. The value of <OTRS_CURRENT_UserLogin> is already replaced. Have you tried it?

**Comment by schnudd31do3** [comment]
Today I tested it once again.

Without my extension:
![image](https://user-images.githubusercontent.com/72391822/151920163-76d5aade-4575-46a4-90a6-f9d0e4485069.png)

With my extension:
![image](https://user-images.githubusercontent.com/72391822/151920302-ef445997-1b25-4141-a587-a4b86e92f6e1.png)

Did you use an other keyword but <OTRS_CURRENT_UserLogin>?

**Comment by rkaldung** [comment]
@schnudd31do3 Here's the process is used to check which works. 

[Export_ProcessEntityID_Process-7f6dd9be4c2d9cb8d2a9d3c209715be2.yml.txt](https://github.com/znuny/Znuny/files/7976461/Export_ProcessEntityID_Process-7f6dd9be4c2d9cb8d2a9d3c209715be2.yml.txt)

**Comment by schnudd31do3** [comment]
Hi rkaldung, thanks for your sample process. It worked as expected and it also worked in my process. My mistake was the additional entry key/value - UserID/1 in the transaction action of the "Owner"
