### ISSUE TITLE
Bug - i18n: Improve a couple of 2FA-related Spanish translations

### ISSUE THREAD

**Issue by MarcoAurelioWM** [znuny/Znuny#202]
### Environment

- OS: n/a
- Browser: n/a
- Znuny version: all; in `dev` and up to `rel-6_2_2` included.

### Expected behaviour

The strings mentioned below to appear correctly translated/understandable. See https://github.com/MarcoAurelioWM/Znuny/commit/c13ecf3f9dafb7b15c047bf758b240a597fb40e2 for the proposed translation. If you'd accept those I can propose a Pull Request but I can't run local tests.

### Actual behaviour

Some 2FA-related messages in Spanish make are not understandable. In particular:

https://github.com/znuny/Znuny/blob/dev/Kernel/Language/es.pm#L2878-L2879

and

https://github.com/znuny/Znuny/blob/dev/i18n/otrs/otrs.es.po#L9688-L9694

### How to reproduce

1. Spanish being your browser language, then
2. Go to e.g. https://ticket.wikimedia.org/otrs/index.pl
3. See the bad translation in the two-factor authentication token input box.

### Screenshots

Thank you.

**Comment by rkaldung** [comment]
@dennykorsukewitz Any recommendation regarding update translations? Via PR or Weblate?

**Comment by MarcoAurelioWM** [comment]
@rkaldung Hello. Do you use Weblate to translate Znuny? If so, I can try to fix it from there if it's more convenient.

Edit: Found it. I sent two suggestions via Weblate to fix those two messages.

**Comment by rkaldung** [comment]
@MarcoAurelioWM The translations you provided via our weblate are integrated and available from Znuny 6.3.2
