### ISSUE TITLE
Bug - Ticket Artikel Attachments disappeared after execution of otrs.Console Admin::Article::StorageSwitch  --target ArticleStorageFS

### ISSUE THREAD

**Issue by MarcPahnke** [znuny/Znuny#203]
### Environment

- OS:           any
- Browser:     any
- Znuny version: 6.0.39 LTS, 6.2.2

### Expected behaviour

Tickets should be displayed equal - no matter which Article-Attachment-Frontend is used

### Actual behaviour

If Article-Attachment-Frontend was changed to FS (Filesystem) the Article Attachments seems to be dissapeared

### How to reproduce

1. Create a new Ticket or a Note-Article to an already existing Ticket - attaching some data such images as direct attachements or as inline images includes in the richtext editor to this Ticket or Note.

2. change to the Konsole/CLI and execute

sudo -u otrs /opt/otrs/bin/otrs.Console.pl Admin::Article::StorageSwitch  --target ArticleStorageFS

3. reload the Ticket in the Browser

### Additional information

The attachments seems to be away. But they aren't - change the Storage Backend back ot DB and the
attachments appear again.

Internally, if Storage was changed to FS, the generated files, seems to get a wrong filename which does not correspond with the filename-entry which is stored and used in the database. - But during the contrary action, (push back in the DB) the files are read and assigned correctly to the articles attachment entries.

The issue seems to be rooted somewhere in ArticleStorageFS->ArticleWriteAttachment()
Ticket::TicketArticleStorageSwitch mit Source=ArticleStorageDB und Destination=ArticleStorageFS

### Screenshots

The same Article with different Attachment Storage Backends

![grafik](https://user-images.githubusercontent.com/89537707/152377082-aa07587b-0e2e-4caf-99e9-91c4f4c8c79d.png)
![grafik](https://user-images.githubusercontent.com/89537707/152377474-c0d237f6-e8b7-4c2e-ba19-6990c6d6d97e.png)

**Comment by BuTzZ** [comment]
Did you also change Ticket::Article::Backend::MIMEBase::ArticleStorage to Filesystem after migration to filesystem?

**Comment by rkaldung** [comment]
> Did you also change Ticket::Article::Backend::MIMEBase::ArticleStorage to Filesystem after migration to filesystem?

Or at least use enable `Ticket::Article::Backend::MIMEBase::CheckAllStorageBackends` for the time of the migration...

**Comment by hanneshal** [comment]
Just my 2cts:

Fresh install:
**Exported to FS**
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/804939/152642114-f2aa2681-4af3-41ef-be0e-533d9d136096.png">

**Updated config:** 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/804939/152642158-d6632447-bc8c-463c-99ab-2912d706f41b.png">

works perfect:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/804939/152642191-506768ea-80ad-4a6d-9cd3-65c6260a6117.png">

Maybe to clarify: the console command just **exports** the attachments. To make Znuny read the attachments, you need to modify the Sysconfig also.

Regards
Johannes
