### ISSUE TITLE
Bug - "No such article!" with TicketArticleCreate when creating an article out of a empty text field

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#204]
### Environment

- Znuny version: 6.2.2

### Expected behaviour
It should be configurable whether no note or a note with a standard text is created from an **empty** text field by TicketArticleCreate in the transition action.

### Actual behaviour
1. **NOK**: If there is text field in a process dialog which remainded **empty** (in case of not mandatory), a note with an error message is created.
![image](https://user-images.githubusercontent.com/72391822/152380350-2b6effac-1002-4d69-a3c5-4df1f5feb72e.png)

2. **OK**: If the text field is **not empty**, a note with the content of the text field is created.
![image](https://user-images.githubusercontent.com/72391822/152380679-4288e8ea-6679-4911-96f4-62e4fe4c9af9.png)

### How to reproduce
Activity dialog:
![image](https://user-images.githubusercontent.com/72391822/152381104-b156bd24-e4f2-46a1-b166-3dd3d023063f.png)

Transaction action:
![image](https://user-images.githubusercontent.com/72391822/152381192-0729f477-949d-4537-b0cc-aedcc7bd0fb5.png)

Dynamic field:
![image](https://user-images.githubusercontent.com/72391822/152381384-fe378925-701b-455d-9cc3-b614280c9a69.png)

Transaction action with TicketArticleCreate:
![image](https://user-images.githubusercontent.com/72391822/152381535-e98e260b-4c2a-4469-ac51-4fb0da4e4351.png)

**Comment by hanneshal** [comment]
I'm sorry but I don't see this as a bug. We cant create empty articles using the process management API (at the moment) and I doubt that this would be "easy" to implement. We check for empty strings, on several places, down the stream in the API. 
The confusion would be the mostly the same if the article is empty. 
Article is empty vs no article => No information was added. 

We could implement a "DefaultIfEmptyBody" field but I don't see this coming in the near future. 
I mark it as "help appreciated". Maybe someone of the community will add this.

IMHO It would be a good practice to:
- prefix the text with a field name "TextComment" : <YOURTAGHERE>
- Check in the Transition if the field is there and the create the article or not. 


Regards

**Comment by schnudd31do3** [comment]
In my opinion, an empty text field should never lead to an error message like this. In the case of an empty text field, I would expect no article to be created. Attached is my sample process as a text file. 
[Export_ProcessEntityID_Process-de41a5de592d4213bcc7549f4c9c0154.txt](https://github.com/znuny/Znuny/files/8013845/Export_ProcessEntityID_Process-de41a5de592d4213bcc7549f4c9c0154.txt)
The file extension must be renamed to ".yml" so that the process can be imported.

Test process ticket created:
![image](https://user-images.githubusercontent.com/72391822/152798053-6204b13a-1cf7-400a-b43c-c1b5445cff07.png)

**Comment by hanneshal** [comment]
We discussed this also:
there are two sides of the medal here. 
1) We can silently drop the article creation without any error
2) We can offer an option for a default value

1 - what seems to be your favourite way to go  has a major downside: one has to know why no article is created. If we do not throw the error, no one will notice it. Could be intended or not. We can not know this. For your case it may be valid to just drop it, for several others it may be not. 

2 - We leave the error as it is and offer an alternative|additional option to prevent it.  
Somewhere around [here](https://github.com/znuny/Znuny/blob/dev/Kernel/System/ProcessManagement/TransitionAction/TicketArticleCreate.pm#L253) an additional check could performed to handle this case. 
Set a default text if body is empty. 


Regards
Johannes

**Comment by rkaldung** [comment]
> 2 - We leave the error as it is and offer an alternative|additional option to prevent it. Somewhere around [here](https://github.com/znuny/Znuny/blob/dev/Kernel/System/ProcessManagement/TransitionAction/TicketArticleCreate.pm#L253) an additional check could performed to handle this case. Set a default text if body is empty.

There is no need for a code change. Use the common parameter [ProcessManagementTransitionCheck](https://doc.znuny.org/manual/admin/processmanagement/transitionactions/common/index.html#additional-check-for-transition-actions) which is exactly designed to have a transition action only executed when the given field has a value.

**Comment by hanneshal** [comment]
Good solution. I missed that. 🤦‍♂️
Does that work for you @schnudd31do3 or do you need a default text?

**Comment by schnudd31do3** [comment]
I feel misunderstood. The ProcessManagementTransitionCheck does not meet my requirements. Entering text is not mandatory (in my case). Only when text is entered, an article should be created. If no text has been entered, no article should be created. I don't need a useless article saying there is no article. I therefore ask you very much that you reconsider my request for correction.

**Comment by hanneshal** [comment]
Hi @schnudd31do3 
you haven't even looked at the documentation, haven't you?
The parameter @rkaldung posted does exactly this.

regards

**Comment by schnudd31do3** [comment]
I already have read it.
"which is exactly designed to have a transition action only executed when the given field has a value." is different from my needs.

My needs are to leave the dialog **with** having a value **OR** **without** having a value. It means, it must be tolerant. In case of left empty, no error-article must be created.

**Comment by hanneshal** [comment]
This is exactly what happens I would say: 
No article is created when the DF is empty
An article is created when the DF has a value?

What am I missing?

**Comment by hanneshal** [comment]
A clarification for better understanding: 
1) What you describe as an error article is no article. This is an iFrame showing you an error message. There is no real article
2) Transition != Transition Action

We just dont trigger the given Transition Action (article creation), the transition (from A->B) is triggered

**Comment by schnudd31do3** [comment]
I sent you a sample process which shows it. Please try it again.
![image](https://user-images.githubusercontent.com/72391822/152981913-dd05377f-56f8-4afc-81fd-97e6965f6bba.png)
Emptying the text filed leads to the error article on submit. Otherwise a article was created from the content of the text filed.

**Comment by hanneshal** [comment]
Works like a charm. 

Added:
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/804939/152983683-19d42d88-d98f-4cb2-991b-dbeb3f54a3da.png">

Result:
https://user-images.githubusercontent.com/804939/152983479-25313d20-d5d1-47a8-9bfc-1cb25f3f6c1b.mp4

EDIT: GIF Version
![screencast 2022-02-08 13-03-08](https://user-images.githubusercontent.com/804939/152984269-b544a328-d4e0-4adc-8f37-d928f46a9a84.gif)

**Comment by schnudd31do3** [comment]
Hi thank you very much for your presentation. I would like to ask you, if you could please help me finding out was it is?

The coresponding message in the apache2 log is:
ERROR: OTRS-CGI-104996 Perl: 5.32.1 OS: linux Time: Tue Feb 8 13:17:56 2022

 Message: No such article!

 RemoteAddress: 10.49.100.6
 RequestURI: /otrs/index.pl?Action=AgentTicketArticleContent;Subaction=HTMLView;TicketID=1014;ArticleID=4270;FileID=;

 Traceback (35264):.
   Module: Kernel::Modules::AgentTicketArticleContent::Run Line: 83
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 1136
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 39
   Module: (eval) (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 173
   Module: ModPerl::Registry::handler (v1.99) Line: 32

The other logs does not have an error message regarding this.

**Comment by hanneshal** [comment]
This is related to the previous configuration. There is a article entry in the database without content. This article can not be shown -> error is thrown

**Comment by schnudd31do3** [comment]
Is it possible to delete the defective item?

**Comment by hanneshal** [comment]
Only via the database. 
The article id should in the article table, but has no entry in article_data_mime

```sql
DELETE FROM article WHERE ID=4270;
```
and clear the cache

bin/otrs.Console.pl Maint::Cache::Delete

Can i close this issue then?

EDIT: 
Or you can delete the ticket via the GA. But this might not be helpful on production

**Comment by schnudd31do3** [comment]
Thanks for investigating. I always deleted the whole ticktet, assuming the related articles are automatically removed. The result is ever the same when I create a new ticket.

I am alrready deleting tickets using the GA (for testing). The productive system has no access to this function.

I cleared the cache multiple times.

Please wait for closing until the real reason is found.

**Comment by hanneshal** [comment]
Question: 
When you delete the ticket via the GA all related information are deleted to. 

So where do you get the error when the ticket is deleted?

**Comment by schnudd31do3** [comment]
Each created ticket in that way has got the same error. Even if deleted the privious one or not.

I have no doubt that my sample process will not produce the error for you. But then why is the same process producing the error for me? Shouldn't it be possible to tell the difference? Is there an extended possibility for debugging?

This is my GA
![image](https://user-images.githubusercontent.com/72391822/153015663-b173137d-5679-477e-a037-7895d8af4c30.png)

**Comment by hanneshal** [comment]
You can post your ArticleCreate Transition Action and the ticket history (complete, pers. info redacted) here. 
This is the reason for the error. 

For some reason the `ProcessManagementTransitionCheck` seems not to be configured properly so it still tries to create an article. Which leads to the error.

**Comment by schnudd31do3** [comment]
Hi Johannes, this was it. I extended my transistion action for creating the note with the new parameter ProcessManagementTransitionCheck to check the dynamic field variable for the textbox. Now no useless error article was created any more.

One question left. What was the reason for adding this new parameter?

**Comment by hanneshal** [comment]
Hello @schnudd31do3 

I must confess I'm a bit shocked to read this. 😨  

@rkaldung has explained it [here](https://github.com/znuny/Znuny/issues/204#issuecomment-1031817010) and linked the documentation.  We then explained it for the over the next **17** Comments and now you ask what this parameter doing. :octocat: Which basically means you have not read anything before. 🙈 

For further support questions I would recommend, before you open the next issue you come to our discord chat or ask in the forum first. This is free and may be a better place to handle this kind of question. 💵 
If you believe you need more help in the future, a support contract with one of the companies who offer support for Znuny might be a good invest. 

Have a good day. 
Johannes

**Comment by schnudd31do3** [comment]
Hello Johannes,
I'm also a bit surprised to assume that I haven't read the documentation. I already wrote that I read them. I used it too, but it didn't work because I used it in the way I understood it. Apparently it wasn't precise enough for me to use properly. It wasn't clear to me in which transaaction action to apply this. I provided you my process in which my transaction action of the textbox was in it. If you would have pointed out to me here that the corresponding entry is missing, this could have saved many loops.  Incidentally, I would have expected that there would be a clear reference to the documentation of the migration from 6.0 to 6.1 about the new parameter. This deficit has cost me many hours of work unnecessarily.

Thank you all in support for your help and I wish you all a nice day too.

**Comment by hanneshal** [comment]
> I would have expected that there would be a clear reference to the documentation of the migration from 6.0 to 6.1 about the new parameter. This deficit has cost me many hours of work unnecessarily.

Ok, we always want to improve things. What would be your proposal to make this better? 

Summary of what we did:
This parameter was added in 6.2 (not 6.1) and is linked in the documentation. Every release has a certain "theme". 6.2 was process management. 

From the release overview:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/804939/153160249-945f3463-4be8-48e1-a86e-1e6d357a7324.png">

Some more details are also mentioned in the [blog post](https://www.znuny.org/en/news/release_6_2_1-6_0_38).

The process management improvements are linked [here](https://docs.znuny.org/manual/releases/6_2_1/features.html), in the release information -> feature area

Which [links to](https://docs.znuny.org/manual/admin/processmanagement/index.html).

Which [points to.](https://docs.znuny.org/manual/admin/processmanagement/transitionactions/common/index.html#common-parameters)

As you can see, the list of features we added is huge. There is no way to add everything somewhere else than in the documentation. 

We are open for proposals where to put such information. Until now I thought we did a good job at this. 

> I used it too, but it didn't work because I used it in the way I understood it. Apparently it wasn't precise enough for me to use properly. It wasn't clear to me in which transaaction action to apply this. I provided you my process in which my transaction action of the textbox was in it. If you would have pointed out to me here that the corresponding entry is missing, this could have saved many loops. 

We are opening the documentation soon. So you can make a proposal for the wording. 
We thought that this note was exactly the hint+the documentation were the hints needed.
![image](https://user-images.githubusercontent.com/804939/153161145-fb867c74-940b-43d3-97e9-769d9470f27b.png)

Sorry for wasting your time. This was not intended.

**Comment by schnudd31do3** [comment]
This is the original explanation from your dokumentation "If this parameter exists. the attribute exists in the ticket object and contains a value." and "...This module only checks if a value is set for the field. ..." It only describes what the parameter does. It does not describe how it is to be used and what the complex interrelationships are that I have found out.

It was not clear to me in which of the transaction actions this parameter should be set and what value should be used for this parameter. I found out that this parameter has to be set in the very transaction action that is supposed to create a note from the DF. In addition, the name of the DF must be entered in the same transaction as the value for this parameter.

Perhaps it might be useful to include a usage example similar to this one in the documentation.
![image](https://user-images.githubusercontent.com/72391822/153596894-7c59c44d-7eee-4225-9dea-766ff955954c.png)

**Comment by hanneshal** [comment]
Hi @schnudd31do3 

thanks for the explanation. We fix the first sentence you mentioned:
![image](https://user-images.githubusercontent.com/804939/153597212-1971a20e-6f17-4329-b9c6-da9592295495.png)

The parameter is not limited to your usecase, mabye this left you confused.
Your usecase is: don't start this Transition Action (CreateArticle) when a given DynamicField is empty. 

In our example:
The ticket state is only set if the dynamic field Example1 contains a value.

We discussed this in the team and think that the example is a good explanation.

Thanks for your feedback!

Have a good weekend.
Johannes
