### ISSUE TITLE
Bug - Incorrect setting of ticket properties by the Generic Agent?

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#205]
### Environment
- Znuny version: 6.2.2

For reopening a process ticket I used the Generic Agent to select the ticket by the process, any closed status and the Raw queue on TicketQueueUpdate. The Generic Agent then updates the activity to the first process state and sets the ticket to unlock and new state.

### Expected behaviour
In ZnunyLTS 6.0.33 it is working es expected. The ticket remains in the first proces state until the agent uses the "submit" from the first process dialog.

### Actual behaviour
For about one second, the ticket remains in the first proces state. Then the process state has changed **itself** to the second proces state automatically. It seems that the field values of the activity dialogs has been kept at its last content in combination with the last pressed "submit". The result is an automatic change to the second process status, without user's action.

**Comment by rkaldung** [comment]
@schnudd31do3 Are you using the same process on both system? After updating the activity via GenericAgent all transition are checked. Maybe there is one that has a matching condition.

**Comment by hanneshal** [comment]
I doubt that this has anything to do with a bug related to the generic agent. I would have a look at the TransitionActions in the first run. What is the trigger for the Move vom A1->A2?

To be sure, please post a sample processes and the GA rules.

**Comment by schnudd31do3** [comment]
@rkaldung: No I don't have both versions running in parallel. On 6.0.33 I didn't run in this issue. After Upgrading to 6.2 the issue came up.
@hanneshal: I appended my sample process, the file has to be renamed in ".yml". When the text field contains at least one character, a note without error is created. When the text field is left empty, I receive the described error message.

[Export_ProcessEntityID_Process-de41a5de592d4213bcc7549f4c9c0154.txt](https://github.com/znuny/Znuny/files/8013751/Export_ProcessEntityID_Process-de41a5de592d4213bcc7549f4c9c0154.txt)

**Comment by schnudd31do3** [comment]
I think it would be best to provide you a sample process.
[Export_ProcessEntityID_Process-de41a5de592d4213bcc7549f4c9c0154.txt](https://github.com/znuny/Znuny/files/8013845/Export_ProcessEntityID_Process-de41a5de592d4213bcc7549f4c9c0154.txt)
The file extension must be renamed to ".yml" so that the process can be imported.

This is my GA:
![image](https://user-images.githubusercontent.com/72391822/152762937-b8dfa31e-0d2e-45cc-87fe-00810886a82b.png)
"closed *" || "meged"
![image](https://user-images.githubusercontent.com/72391822/152762812-46a9b7f7-ee8d-4089-a623-820d88436b9e.png)
![image](https://user-images.githubusercontent.com/72391822/152762895-1e1471ca-7abe-4302-aa26-0df2fd877e10.png)

In this example, if the ticket is in the "Process complete" state, it has been moved to the "Test" queue. Then, when the ticket for restarting the process is moved to the "Raw" queue, the ticket is immediately back in the "Process complete" state and the previously reached "closed *" state, and it is in the "Test" queue, without that the user got to see the activity dialog of the first process state.

Test process ticket created:
![image](https://user-images.githubusercontent.com/72391822/152798202-573349c8-d172-4c84-8d87-2095d6d79e05.png)

**Comment by hanneshal** [comment]
Hi @schnudd31do3,

we had a look at your process and your GA settings: 

To make sure we are on the same task here, this is what we did:
- Created the GA as you described it
![image](https://user-images.githubusercontent.com/804939/152852119-4a1704db-f9a0-45c6-9056-94f2416552e0.png)


- Imported your process
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/804939/152851437-7add04f4-eb23-480d-8572-6ea9662dbe22.png">

1) Created a process ticket
2) Closed the ticket
3) Moved the queue
4) Ticket is reopened (GA)
5) Ticket is moved back (GA)

Result:
<img width="2516" alt="image" src="https://user-images.githubusercontent.com/804939/152852901-8bf067d5-01a8-4708-b262-501869fa0036.png">

Works all the time without any problem. 

Note: We tried the GA with 2 variations:
1) Only set the activity id
2) Set activity and process 

Result is unchanged.
Tried it on 6.2, 6.1 and 6.0.39 The behaviour is identical. 

Regards
Johannes

**Comment by hanneshal** [comment]
Note: tested on vz1826

**Comment by schnudd31do3** [comment]
Hi Johannes, thanks for testing. I forgot to use the useful ticket history feature for testing. This made me realize that the problem was that the user did not have access to the "Test" queue. After I changed that, everything worked as expected. Thank you for your patience and support. I'm closing the case.

![image](https://user-images.githubusercontent.com/72391822/152938264-8cc2e4c2-1965-455c-a125-56d2d9ca0114.png)

**Comment by schnudd31do3** [comment]
Unfortunately, I have to open the case again because the error is still there in the "real" process and I can't see why the process seems to skip the first dialog and is switched on immediately.

![image](https://user-images.githubusercontent.com/72391822/152951948-9a6a63f9-39bb-4658-88f2-43f9c10ea10f.png)

**Comment by schnudd31do3** [comment]
I found it by myself, but it is a workaround. I had to preset a dynamic field value with a default value 
![image](https://user-images.githubusercontent.com/72391822/152955715-561972ec-ccc6-4a9f-aaf7-e2f7ff109423.png)
which ensures that the dialog cannot be closed. The transition is designed in such a way that the input in the dialog cannot be completed if the dynamic field variable contains the default value. This means that my assumption is now proven. If the process is restarted via the GA, the dynamic field variables are not automatically assigned their default variables.

**Comment by hanneshal** [comment]
>  This means that my assumption is now proven. If the process is restarted via the GA, the dynamic field variables are not automatically assigned their default variables.

Why should we reset DynamicFields automatically and effectively loose data, which are stored in the Ticket as separate entities, when you change the two fields for a process ? 

If you want to reset values, you have to change them in the GA. As you did for the process fields. 
This is not a workaround, this is the correct way 👍 

Greetings

**Comment by schnudd31do3** [comment]
I have now found a second way to get it working. If you want to assign a default value to the last saved value, you must specify the default value when defining the dynamic field variable.
![image](https://user-images.githubusercontent.com/72391822/152961012-6955ae10-8020-4c37-b291-10b16ba16384.png)

I assumed that the given default value would be honored in the activity dialog when reopening, which didn't happen.
![image](https://user-images.githubusercontent.com/72391822/152960157-05fe2814-14bd-4b88-aff7-cf4b2ec3ed2b.png)
Is that intentional?

**Comment by hanneshal** [comment]
If there is already a value in the DF, then a given default value is ignored. 
Again: We don't remove/clear any existing data.

**Comment by schnudd31do3** [comment]
I had not defined a default value in the DF. I had expected that the default value given in the activity dialog would be taken then, but that has not happen.

**Comment by hanneshal** [comment]
if the DF is shown in the GUI (and shown to a user) and it does not already have a value, the default is used. 
If you trigger it, via manual setting changing the activity id it is not triggered. 
It may also depend on the type of field you use. A textfield is no problem. A dropdown or multiselect has to have the value in the possible keys.

**Comment by schnudd31do3** [comment]
Thanks for the explanation
