### ISSUE TITLE
Feature request: Ability for admins to delete articles.

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#208]
If, for example, incorrectly created articles have to be removed when processes are started in real tickets, as an administrator I need the option of being able to remove such articles. There are certainly other use cases for administrators where such a function is required.

I'm not sure if I'm allowed to show third party links in this forum. I just want to give you an example of what already exists on this subject: 
![image](https://user-images.githubusercontent.com/72391822/152825160-91608b05-bbb2-41e6-933a-f7c764ef504a.png)

Since this package is not compatible with Znuny 6.2.x, I rudimentarily corrected it to make it executable in the 6.2.x framework.
![image](https://user-images.githubusercontent.com/72391822/152825758-1512edce-7d8b-452a-a0de-f2701957bb65.png)

In addition, I replaced all words with "Otrs" with "Znuny". After that I was able to install the package.

An entry is created with the installation in the system configuration:
![image](https://user-images.githubusercontent.com/72391822/152826162-5a46e0e0-f912-44be-9e72-40abf4a13b86.png)

By changing "users" to "admin" I make sure only administrators have this feature.
![image](https://user-images.githubusercontent.com/72391822/152826474-430fe7fc-e17a-4df7-9a1b-6dadaca18f70.png)

Now you only have to become the owner of the ticket and the desired function is already available:
![image](https://user-images.githubusercontent.com/72391822/152827618-d5d5dca7-ae68-45a2-8b2e-b9d2b2ac9e13.png)

**I want to reiterate that it is not my intention to misuse anyone else's intellectual property. This is meant to be a demonstration only.**

**Comment by hanneshal** [comment]
Hi @schnudd31do3,

first of all: you can post external add ons as you want.

But we wont implement this feature. We had the discussion several time in discord and I believe here somewhere too. 
Thats exactly the reason why those external add-ons are used and are totally legit to use.
Znuny is used in so many contexts where it, in some cases, was selected exactly for the lack of this feature. 

We might add a feature for editing notes created by an agent (to remove typos). But even this is far in the future. 
Sorry to disappoint, but you have to use the plugin. 

Regards Johannes

**Comment by reneeb** [comment]
BTW: There is a 6.2.x compatible version of the addon: https://opar.perl-services.de/dist/ArticleCopyMoveDelete-6.0.4

**Comment by schnudd31do3** [comment]
@hanneshal: I understand. I have the need for this feature because Znuny created erroneous articles with the content "No article found!", which I wanted to remove.

@reneeb: I tried exactly this one but during installation, Znuny throws an error. Looking inside shows, that all the encrypted parts are missing from the original one. Only my version is able to run.

**Comment by reneeb** [comment]
@schnudd31do3  I just downloaded the package from OPAR and tested it on a plain Znuny 6.2.2 and it works. If you need further support for that addon, please contact me at info@perl-services.de

**Comment by schnudd31do3** [comment]
Did you use this: https://opar.perl-services.de/package/download/1538 ? When trying to install this one, Znuny throws an error, saying the framework is not compatible to 6.2. Therefore I modified it in order to be accepted by the packet manager.

**Comment by reneeb** [comment]
No, I used the version 6.0.4. That version is compatible with Znuny 6.2.x. You used 6.0.2 (https://opar.perl-services.de/dist/ArticleCopyMoveDelete-6.0.2) that one is not compatible with Znuny 6.2.x.

**Comment by schnudd31do3** [comment]
Yes, you are right. I did not find the new one 6.0.4. Instead of this I found one on Git where the contributor says it will be working for 6.2, but it didn't.

**Comment by reneeb** [comment]
You can't find the .opm (the addon you can install) file on github. There is just the code. I've posted the correct link above.

**Comment by schnudd31do3** [comment]
Thanks for the support. I found the link above and tested it successfully.
