### ISSUE TITLE
Feature request: Show complete menu after deleting a ticket

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#209]
After deleting a ticket using the GA e. g. by moving to a "Trash" queue:
![image](https://user-images.githubusercontent.com/72391822/153138467-a19bf752-244a-4899-8f46-46c81a65d968.png)

an uncomplete menu bar is shown in addition with  a pointless message:
![image](https://user-images.githubusercontent.com/72391822/153138854-bfaffb9d-e1b4-450b-916a-ebcfb84fa21e.png)

I would prefer that no message comes up and you will be taken straight to the dashboard with full menu bar instead.

**Comment by reneeb** [comment]
* Showing the menu is a good idea
* redirecting to the dashboard is a bad idea because then you don't know what went wrong
* What would you suggest for the title of the error message?

**Comment by rkaldung** [comment]
> After deleting a ticket using the GA e. g. by moving to a "Trash" queue:

There is a difference between deleting a ticket and moving a ticket, an essential one. Since I do not see the use case here and a valid description (AFAIK there is no redirect from a generic agent execution to a ticket's detail view) I think this issue can be closed.


Info why we close this:
What you describe as pointless, is on purpose. 
It prevents external enumeration of ticket ids / ticket numbers. Ticket does not exist vs you don't have permission is an information disclosure. 

So we wont change or fix this.

Regarding the error message itself. There is no relation between the deletion of the ticket and this error. 
This is shown error is shown on every non-existing ticket id / ticket number. 

We create a bug for the menu and close this FR.

**Comment by schnudd31do3** [comment]
@rkaldung: For deeper explanation, the only sensible way for users to delete tickets is to move the ticket to a "garbage" queue. The GA recognizes a queue change to the "garbage" queue and then deletes the ticket. The user then receives this error message, which I think is misleading. From a technical point of view, the error message is understandable. From the user's point of view, it is incomprehensible that an authorization problem should have arisen after the ticket was deleted. It would be better to confirm the deletion to the user instead of acknowledging it with a meaningless error message.

I appreciate: "We create a bug for the menu and close this FR."

@reneeb: A separate information message for deleting tickets may be required here instead of a collective error message for missing authorizations.

Thanks.

**Comment by reneeb** [comment]
@schnudd31do3 No, this has security implications: If you use two distinct messages, users can know how many tickets are in the system and they could try to get the data. If they don't know if the ticket is deleted or they just don't have the permission to view it, it's more effort to get data.

**Comment by schnudd31do3** [comment]
@reneeb: I feel a little missunderstood. "If they don't know if the ticket is deleted or they just don't have the permission to view it, it's more effort to get data."

My intention is not to remove the error message, just to change the text. The text should read as follows: The ticket with the ID xyz was deleted.

**Comment by hanneshal** [comment]
@schnudd31do3 we don't know if a ticket is deleted because all information for the ticket is gone. **They are deleted.** 
This includes the history and all other information.

**Comment by dignin** [comment]
Hi, @schnudd31do3 I do understand, as I had this thought many years ago. 

 😄  We do take your requests and isuses seriously!  😄 

Please understand that the way you are handling your GA is the real issue. It's not good practice to just delete upon queue move. This sounds like what you do. (if not, I apologize for the assumption.)

**Comment by schnudd31do3** [comment]
@dignin What would be your suggestion how a ticket can be deleted immediately and in a "clean" way? No other function is available to the user other than to move to a queue. Alternatively, you could think of a custom button that the user can then use to delete the ticket. However, this seems to be the greater effort. In addition to that, I would like to restrict this function to e. g. a role.

**Comment by schnudd31do3** [comment]
@hanneshal "we don't know if a ticket is deleted because all information for the ticket is gone. They are deleted.
This includes the history and all other information." Would it be possible to save the ticket number before deleting it, e.g. in a  cache in order to then display it in the confirmation window after deletion? Then no error can be generated because the ticket number of the application is available from the cache.

**Comment by hanneshal** [comment]
It would be possible, but we have no plans for that. The use-case, as @dignin wrote, is pretty edgy here. 
You could easily modify your Generic Agent to run time based, not event based. And the issue would not be there anymore. 
It is also, at least in our customer base, pretty uncommon for agents to be allowed to delete tickets. 

If they are allowed to move tickets to a special queue, where a GenericAgent deletes them, this is with a time difference of at least 14 days. Just for the fact that they might delete the wrong ticket, or "slipped with the mouse" and selected the wrong menu entry or the wrong queue. 

So if you need it, a developer surely can modify it. 
But the cost vs value, at least for us as maintainer, is not very attractive here. 

Regards

**Comment by schnudd31do3** [comment]
Deleting tickets is not available to agents, only to admins. It is necessary in order to be able to delete the test tickets when the processes are started up, which would otherwise be kept in the list of closed tickets and would unnecessarily inflate the database. I will adopt the timed deletion in the GA, that's a practical suggestion.

While this time-based solution is a way to bypass the error output, I think it's still a bug for the application to complain about a non-existent ticket that it just deleted itself.

**Comment by hanneshal** [comment]
> While this time-based solution is a way to bypass the error output, I think it's still a bug for the application to complain about a non-existent ticket that it just deleted itself.

We accept your opinion, but wont change the behaviour, for the reasons we explained before.
