### ISSUE TITLE
Bug - Show menu items when showing the error screen.

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#210]
### Environment

- OS:          macOs
- Browser:      Safari
- Znuny version: 6.2.2

### Expected behaviour

The menu items should always be visible

### Actual behaviour

If a (fatal) error is shown, the menu is not shown. 
![image](https://user-images.githubusercontent.com/804939/153155018-4b8e7ac1-f34c-4c98-b1fb-180961b2a072.png)

[Reference](https://github.com/znuny/Znuny/issues/209)

### How to reproduce

Steps to reproduce the behaviour:

1. Try to open a non existing ticket by attaching a non existing ticket id
2. Sample_ index.pl?Action=AgentTicketZoom;TicketID=433333423423423234
3. See error

### Additional information

None

**Comment by dennykorsukewitz** [comment]
Hi @reneeb,

the issue has already been solved internally.
Thanks anyway 🚀
