### ISSUE TITLE
Feature request: Possibility for configuration of a custom email template folder

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#211]
Email templates are stored in
/opt/otrs/Kernel/Output/HTML/Templates/Standard/NotificationEvent/Email

When creating ticket notifications, like
![image](https://user-images.githubusercontent.com/72391822/154056348-5bf33fbc-b2e3-476a-9e2e-6aa2a1f7b667.png)
email templates only can be selected from the named folder (see above).

I created my own templates in this folder in order that I can select them when creating ticket notifications. I also modified Alert.tt, Default.tt, and Unformatted.tt for my needs. But when updating the framework the modifications of Alert.tt, Default.tt, and Unformatted.tt are gone and I have to restore them manually. I wold like to configure a path to my custom templates e. g. using the sys config.

**Comment by rkaldung** [comment]
Hi @schnudd31do3 ,

There is no need for this.
Place your files into  /opt/otrs/**Custom**/Kernel/Output/HTML/Templates/Standard/NotificationEvent/Email 

This is the typical way how framework files in Znuny can be modified and "survive" framework updates.

**Comment by hanneshal** [comment]
Or you could add them in a custom package, which you reinstall after an upgrade.

**Comment by schnudd31do3** [comment]
It seems that this folder isn't existing:
cd: /opt/otrs/Custom/Kernel/Output/HTML/Templates/Standard/NotificationEvent/Email: No such file or directory

**Comment by hanneshal** [comment]
Correct. We don't create an unneeded Folder structure. You create it yourself, when it is needed. /opt/otrs/Custom/README should be there. 

```
cat Custom/README
If you need to modify already existing framework Perl module files or tt template files
or unit test files for customizations, you can do this in the $OTRS_HOME/Custom/ directory.

Example:

  You need to modify Kernel/System/Service.pm to add an customization, copy
  Kernel/System/Service.pm to Custom/Kernel/System/Service.pm and modify it.
  This module will be used instead of the original Service.pm.

This method also works for tt files. Just place them in Kernel/Output/HTML/$ThemeName,
and they will be used if the theme is selected.

It also works for unit test files. Just place them in Custom/scripts/test.

If you use Apache + mod_perl or PerlEx, any Perl module files placed in this directory
will only be loaded by your web server after you restarted it.
```

**Comment by dignin** [comment]
you must make the directory

```
znuny@dev-loc:~$ mkdir -p Custom/Kernel/Output/HTML/Templates/Standard/NotificationEvent/Email
znuny@dev-loc:~$ ls -al Custom/Kernel/Output/HTML/Templates/Standard/NotificationEvent/Email
total 0
drwxr-sr-x 2 otrs www-data  6 Feb 15 12:37 .
drwxr-sr-x 3 otrs www-data 19 Feb 15 12:37 ..
```

Are you on our Discord Server? You should really try it out. https://discord.gg/XA5P2u27

**Comment by schnudd31do3** [comment]
I wasn't sure if it's allowed to create custom paths within the application. I tried it, the templates in /opt/otrs/Custom/Kernel/Output/HTML/Templates/Standard/NotificationEvent/Email are now recognized. However, templates in "Kernel/Output/HTML/$ThemeName" are not displayed (e.g. in Appointment Notification Management).

The working solution (thanks dignin, rkaldung) has the advantage that I only have to create the folder again when updating the framework and put my custom templates back there. I can leave the standard files unchanged after an update.

**Comment by schnudd31do3** [comment]
@dignin "You should really try it out. https://discord.gg/XA5P2u27" Thanks, that was I am looking for.
