### ISSUE TITLE
Contribution? For migration?

### ISSUE THREAD

**Issue by dpalic** [znuny/Znuny#213]
Watching the forum posts about migrations I would like to contribute a preparation & migration script for the configurations from OTRS5 to Znuny 6.

Are you interested for the scripts, so that they are usable manually but also usable e.g. for a dockerized environment?

**Comment by hanneshal** [comment]
Hi @dpalic,

we usually do not make changes to a well working migration mechanism especially on older version (we don't even support anymore). 
5->6 is on of the most solid migrations compared to previous versions. 
If your scripts do not change the current behaviour feel free to propose something. 

Maybe the forum or discord would be a better place for this discussion, but feel free. 

Regards

**Comment by IuriSalla** [comment]
Bom dia.
A migração do OTRS 5 para o Znuny 6 traz muita instabilidade e complicações ou o processo é simples?

**Comment by hanneshal** [comment]
Hi, if you work by the docs and do not have custom code in place. No.
But please move to Discord or to the forum if you have questions. GitHub is primary used for issues / bugs

**Comment by IuriSalla** [comment]
Olá, você consegue me encaminhar o link para o canal do discord?
Obrigado.

**Comment by joserribeiro26** [comment]
> Olá, você consegue me encaminhar o link para o canal do discord? Obrigado.

Olá, não traz problemas não. Pelo contrário, tem recursos novos e esta bem estável.

Só se atende aos AddOns que você usa, pois deve verificar se já estão portados para a versão para onde você esta migrando.

Outro ponto é que por enquanto, talvez seja melhor atualizar para o Znuny LTS 6.0.40 até que todos seus AddOns estejam portados para Znuny 6.1, 6.2 ou 6.3.

Abraços.

**Comment by hanneshal** [comment]
> Olá, você consegue me encaminhar o link para o canal do discord?
> Obrigado.

https://github.com/znuny/Znuny/blob/dev/README.md
