### ISSUE TITLE
Feature request: Selectable person for "Sender" in the ticktet view

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#215]
Current behaviour is that the last contact person of the ticket is shown.

For example, "Hartmut" was the last contact person.
![image](https://user-images.githubusercontent.com/72391822/155121749-0348960d-c937-4aa4-bb05-c063e2d8616f.png)

"Dieter" has created the ticket and in the meantime it was forwarded to "Hartmut".
![image](https://user-images.githubusercontent.com/72391822/155122024-ae56f357-fd12-4109-925d-d9d8e225f395.png)

Disadvantage: When searcing for tickets created by "Dieter", "Hartmut" is shown under "Sender", see first screenshot. Users may be confused that the name they are looking for is not displayed in the "Sender" section. They would have expected the name they were looking for.

I would like to have a setting option to decide whether the ticket creator or the last contact person should be displayed under "Sender".

**Comment by hanneshal** [comment]
Hi @schnudd31do3 ,

we wont change the behaviour of the Sender field. It shows the last customer sender. And we really don't need more confusing Sysconfigs. We already have plenty of them

But there is a simple and easy way to achieve what you need. 
Create a Dynamic Field, call it lets say: 
- Name: 'OriginalSender'
- Label: 'Original sender' 

Enable it in the Overviews, Dashboard Widgets or in the Search the Reporting... wherever you like.

Create a Postmaster Filter like this:
<img width="1872" alt="image" src="https://user-images.githubusercontent.com/804939/155134713-76de7790-0f55-452d-872a-1766833012b0.png">
 
 And for every new incoming ticket the "From+Realname (if submitted)" is stored. 
 This would be your origin contact. 
 


P.S.
If you run in the problem that the field value is not shown completely, increase the value for the Sysconfig: DynamicFieldsZoomMaxSizeSidebar

**Comment by schnudd31do3** [comment]
Hi, 
sorry for delayed answer, I was too busy. 

Back to your suggest. So far I am the only one who noticed the problem. I'll wait until users get too bothered by it. I will keep in mind.

I would like to comment on your statement. I made a test. For a ticket-closed message I used the OTRS_CUSTOMER_REALNAME  tag for salution in the answer. It works as expected.

When the ticket is forwarded to s. o. else,  the name this person was set in as salution. But if I use OTRS_OWNER_UserFirstname + OTRS_OWNER_UserLastname, the name of the customer is used. In this case it seems that OTRS_CUSTOMER_REALNAME will be overridden by the name of the person the ticket was forwarded to.

You've already decided not to fix this error, which I regret. So I'm closing the case now.

**Comment by hanneshal** [comment]
> When the ticket is forwarded to s. o. else, the name this person was set in as salution. But if I use >OTRS_OWNER_UserFirstname + OTRS_OWNER_UserLastname, the name of the customer is used. In this case it seems >that OTRS_CUSTOMER_REALNAME will be overridden by the name of the person the ticket was forwarded to.


I'm sorry. I cant follow. In your issue you were talking about the sender field in the overview / article overview. Thats what my proposal was solving. Because the sender field has a fixed purpose and we wont change it in the near future. I did not have closed the issue and waited for your feedback. Maybe I misunderstood something?

Are you still talking about this or something different?

> OTRS_OWNER_UserFirstname + OTRS_OWNER_UserLastname, the name of the customer is used
You in your template, the OTRS_OWNER is replaced with the customer, not the agent?

> In this case it seems that OTRS_CUSTOMER_REALNAME will be overridden by the name of the person the ticket was forwarded to.
I cant follow with this one. Maybe you can explain this with a set of screenshots or come to discord and we can chat about it.
