### ISSUE TITLE
Doubt about versions and branchs

### ISSUE THREAD

**Issue by samueldc** [znuny/Znuny#220]
Hi guys,
I would like to know for sure which branch corresponds to the LTS version, and which corresponds to the Feature version.
Thanks in advance.
Best regards!
Samuel

**Comment by hanneshal** [comment]
Hi @samueldc ,

rel-6_0-dev -> is the LTS dev branch. This is the base for the next version. (mostly used for bugfixes or patches)
rel-6_3-dev -> is the branch for the current supported version (mostly used for bugfixes or patches)
dev -> the Feature branch (without LTS extension) for upcoming versions (mostly used for feature extensions)

We will update the dev doc (https://doc.znuny.org/manual/developer/index.html) soon to make this more clear.

Regards

**Comment by samueldc** [comment]
Ok. Thanks for the fast reply. So I assume the rel-6_0 corresponds to the stable release of LTS version, and the rel-6_3 corresponds to the stable release of Feature version. Regards!

**Comment by samueldc** [comment]
All clear now.
