### ISSUE TITLE
Bug - Reset of pending time is not done when pending check interval is too short

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#221]
### Environment

- OS:           any
- Browser:     any
- Znuny version:  6.0.+ 

### Expected behaviour

If I set a pending auto state and the auto state resolves to a state of type closed, it should reset the pending time in any case.

### Actual behaviour

There is an edge case that, when the Sysconfig for the ticket pending is set to "every minute".
It may happen that the action is performed at exactly 00 seconds, which may lead to a failed check, which stops the reset event module.

### How to reproduce

Steps to reproduce the behaviour:

1. Modify Sysconfig pending check to be executed every minute
2. create a pending auto close ticket for a given time in the future
3. It may happen that the check fails, if the state change and the reset are started in the same second

t compares 2022-03-04 15:44:00 against the current run time 2022-03-04 15:44:00 

Example from Discord, where this bug was found:
![image](https://user-images.githubusercontent.com/804939/157665421-4a0134e4-8dc5-4eaf-a77d-40603a9fc3fa.png)

Ticket 2 is modified exactly at 2022-03-04 15:44:00.
So the event module compares the until time, which is 2022-03-04 15:44:00 against the current run time, which is 2022-03-04 15:44:00. This results in 0 and a "failed" check for the module.

https://github.com/znuny/Znuny/blob/dev/Kernel/System/Ticket/Event/TicketPendingTimeReset.pm#L76

### Additional information

This was hard to find, is a valid bug and we thank @Guilherme on our discord channel for the research he put into this.

**Comment by rkaldung** [comment]
Fixed with today's release of Znuny LTS 6.0.41/Znuny 6.3.2

**Comment by iwillforce** [comment]
> Fixed with today's release of Znuny LTS 6.0.41/Znuny 6.3.2

Hey Roy, can you tell me what files was been updated to fix that?

**Comment by rkaldung** [comment]
> > Fixed with today's release of Znuny LTS 6.0.41/Znuny 6.3.2
> 
> Hey Roy, can you tell me what files was been updated to fix that?

Hi, this is the commit I found: https://github.com/znuny/Znuny/commit/b3a9425b449846bd33e48eff1efeef49b0a51dc2
