### ISSUE TITLE
Bug - Automatic Answer by State Update

### ISSUE THREAD

**Issue by Mueke666** [znuny/Znuny#223]
### Environment

- OS:          ubuntu 20.04 
- Browser:      Firefox 
- Znuny version: 6.2.2 

### Expected behaviour

Before the Update to 6.2.2 the Automat Answer are only send, if the Ticket has a Cutomer User

### Actual behaviour

After the Update the Automatic Answer send every time even in tickets without a Customer User (In this Case to the Customer ID, but in case of Spam i only want to close the Ticket without a Notification to the Sender).
At the Ticket Notifictions in the Admin Settings i set the Event "TicketStateUpdate" and the Recipients to "Customer user of the ticket"

### How to reproduce

Set the Ticket Notification Settings as described above an Create a Ticket without a Customer User

2. Click on '...'
3. Scroll down to '...'

### Screenshots

![grafik](https://user-images.githubusercontent.com/89984304/157835971-033715f3-8ad7-48e3-a51a-c0ef48d4447e.png)
![grafik](https://user-images.githubusercontent.com/89984304/157836067-322befd9-41ea-49ce-831e-63aae80a1180.png)

**Comment by hanneshal** [comment]
Hi @Mueke666 

I tested it on a 6.0.38 / 39 & 6.1.2 & 6.3.1 the behaviour is exactly the same. If you select CustomerUser and no CustomerUser is set/found, the FROM is used. This is the "wanted" behaviour.  
The label is pretty irritating, I second that. But it is not an exclusive filter for "if a customer user exists" and (as far as I know) never was. 

But we did not changed anything related to this logic. 

Greetings
Johannes

**Comment by Mueke666** [comment]
Hi @hanneshal,

thanks for your answer.
Before the Update i was on 6.0.37 or 6.0.36 (I´m not sure).
Do you have an idee how i can fix this Problem for me?

**Comment by hanneshal** [comment]
Hi,
a possible solution would be DynamicFieldFromCustomerUser, if you have a fixed value for your customers or could add one. 
Mail is processed -> CustomerUser is found-> DF from CustomerUser is set with the given value. You can use this "fixed" value in the notification check. For example the valid_id

Regards
Johannes
