### ISSUE TITLE
Bug - otrs-znuny inconsistency after upgrade.

### ISSUE THREAD

**Issue by jczmok-iag** [znuny/Znuny#224]
### Environment

- OS:          Debian10.11
- Browser:     Chrome, but independent of Browser
- Znuny version: 6.0.40

### Expected behaviour

No error message after upgrade from otrs5 -> znuny6.0.40

### Actual behaviour

Upon performing the preparation and update via database dump & filesystem one process is reporting "missing" files. But those parts were uninstalled. (ITSM/GeneralCatalog)

```[Mon Mar 14 07:10:14 2022][Error][Kernel::System::PostMaster::Filter::SystemMonitoring::_IncidentStateNew][192] Can't locate Kernel/System/GeneralCatalog.pm in @INC (you may need to install the Kernel::System::GeneralCatalog module) (@INC contains: /opt/znuny-6.0.40/Custom /opt/znuny-6.0.40/Kernel/cpan-lib /opt/znuny-6.0.40 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /opt/znuny-6.0.40/Kernel/System/Main.pm line 86.
[Mon Mar 14 07:10:14 2022][Error][Kernel::System::PostMaster::Filter::SystemMonitoring::_IncidentStateNew][199] Can't locate Kernel/System/ITSMConfigItem.pm in @INC (you may need to install the Kernel::System::ITSMConfigItem module) (@INC contains: /opt/znuny-6.0.40/Custom /opt/znuny-6.0.40/Kernel/cpan-lib /opt/znuny-6.0.40 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /opt/znuny-6.0.40/Kernel/System/Main.pm line 86.

[Mon Mar 14 07:10:15 2022][Error][Kernel::System::PostMaster::Filter::SystemMonitoring::_IncidentStateNew][192] Can't locate Kernel/System/GeneralCatalog.pm in @INC (you may need to install the Kernel::System::GeneralCatalog module) (@INC contains: /opt/znuny-6.0.40/Custom /opt/znuny-6.0.40/Kernel/cpan-lib /opt/znuny-6.0.40 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /opt/znuny-6.0.40/Kernel/System/Main.pm line 86.

[Mon Mar 14 07:10:15 2022][Error][Kernel::System::PostMaster::Filter::SystemMonitoring::_IncidentStateNew][199] Can't locate Kernel/System/ITSMConfigItem.pm in @INC (you may need to install the Kernel::System::ITSMConfigItem module) (@INC contains: /opt/znuny-6.0.40/Custom /opt/znuny-6.0.40/Kernel/cpan-lib /opt/znuny-6.0.40 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /opt/znuny-6.0.40/Kernel/System/Main.pm line 86.
```

### How to reproduce

Take an old Otrs5 installation and make a new directory with new otrs version and migrate everthing, then uninstalll ITSM Modules and GeneralCatalog.

### Additional information

I assume a leftover somewhere in the System but don't know where to look.

### Screenshots

n/a

**Comment by hanneshal** [comment]
Hi, 

Znuny or in the Past OTRS CE will not touch modified Sysconfigs. The problem here is probably that you had modified the Postmaster Filter Setting for the System Monitoring package. 

To be more precise, this setting: 
https://github.com/znuny/SystemMonitoring/blob/dev/Kernel/Config/Files/XML/SystemMonitoring.xml#L49

Or it has been, somewhere in the past, migrated to your modified settings. 

You can just disable this one. The problem here is the following:
When a user uninstalls a package, we wont remove modified sysconfigs. This is a design decision made in the early days, to make it easy to transfer / uninstall / reinstall settings. 


To resolve such errors it is recommended to use: 
`bin/otrs.Console.pl Maint::Config::Rebuild --cleanup` 

This removes such config entries. As far as I can tell at the moment, is not related to the migration but to the package install/remove process. 

Regards
Johannes

**Comment by jczmok-iag** [comment]
okay, i did not find anything with ITSM in the named config file but i did execure the Config::Rebuild.
Will monitor the logfile and report back.

**Comment by rkaldung** [comment]
> okay, i did not find anything with ITSM in the named config file but i did execure the Config::Rebuild. Will monitor the logfile and report back.

My guess it you have the add-on SystemMonitoring installed and the system configuration setting SystemMonitoring::SetIncidentState is enabled. But this requires the ITSMConfigurationmanagement add-on. Just reset this setting.

**Comment by jczmok-iag** [comment]
Actually SystemMonitoring is installed. But I do not need the Plugin. So i removed it, we'll see if the error is gone.

**Comment by rkaldung** [comment]
> Actually SystemMonitoring is installed. But I do not need the Plugin. So i removed it, we'll see if the error is gone.

If you remove this add-on the you need definitely toe execute `bin/otrs.Console.pl Maint::Config::Rebuild --cleanup` to get rid of the changes on non-existing settings.
