### ISSUE TITLE
Bug: ckeditor plugin codemirror missing since 6.0.40

### ISSUE THREAD

**Issue by meisterheister** [znuny/Znuny#225]
### Environment

- OS:           unkown
- Browser:      any
- Znuny version: 6.0.40 / 6.0.31

### Expected behaviour

The XSLT editor should be shown when editing webservices

### Actual behaviour

The editor is not loaded due to a missing plugin: "CodeMirror"

### How to reproduce

Steps to reproduce the behaviour:

1. Open Webservice
2. Edit XSLT

### Additional information

Now lots of additional plugins have been packaged with the new release (from 64 to 124!) but one has been removed '[codemirror](https://ckeditor.com/cke4/addon/codemirror)'. 

Is there any reason why this happened?

It seems to me that you moved to integrate not only specific but all plugins from [ckeditor4 pre-release repository](https://github.com/ckeditor/ckeditor4/tree/4.17.1/plugins) plus some extra (contextmenu_linkopen, exportpdf, scayt, splitquote, wsc).
No ckeditor version before included 'codemirror' plugin by default so it seems it has been added before as well.
BTW: Release repository is ckeditor/[ckeditor4-releases](https://github.com/ckeditor/ckeditor4-releases) with less [plugins for 4.17.1](https://github.com/ckeditor/ckeditor4-releases/tree/4.17.1/plugins).

Since the last update to znuny 6.0.40 the ckeditor was also updated from reportedly 4.16.0 to 4.17.1.
See commit: [Updated CKEditor from version 4.16.0 to 4.17.1.](https://github.com/znuny/Znuny/commit/8f8b29aefa30cfe441bdf95043549a034ed9a94b)

Could you please integrate  the 'codemirror' plugin again?

**Comment by dennykorsukewitz** [comment]
@hanneshal Thank you for using the github issue template!

**Comment by hanneshal** [comment]
Hi @meisterheister 

thanks for reporting this. We are already working on this (reference internal issue#217).

> Is there any reason why this happened?

Yes. Bugs happen. We are on it. 


Just a note: please don't delete the bug template when you create issues. It is there for a reason ;)

**Comment by meisterheister** [comment]
@hanneshal  many thanks for the quick update!
I did not delete the bug template just clicked "new issue". This seems to be a github bug since when you click **before** being logged in you will not be presented with any templates.

**Comment by dignin** [comment]
Fixes

https://download.znuny.org/releases/packages/Znuny-Bugfix225-6.0.1.opm
https://download.znuny.org/releases/packages/Znuny-Bugfix225-6.3.1.opm

Documentation

https://doc.znuny.org/manual/releases/installupdate/update/update-6.3.html#install-hotfix

**Comment by rkaldung** [comment]
@meisterheister This is fixed with today's release of Znuny LTS 6.0.41 / Znuny 6.3.2

**Comment by beingbaban** [comment]
> @meisterheister This is fixed with today's release of Znuny LTS 6.0.41 / Znuny 6.3.2

Can we also install this fix on OTRS 6.0.40?

**Comment by rkaldung** [comment]
> > This is fixed with today's release of Znuny LTS 6.0.41 / Znuny 6.3.2
> 
> Can we also install this fix on OTRS 6.0.40?

The bugfix add-on mentioned above is for Znuny LTS 6.0.40
