### ISSUE TITLE
Bug - wrong default value for column in table mail_account

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny#227]
### Environment

- OS:           n.a.
- Browser:      n.a.
- Znuny version: 6.3.1

### Expected behaviour

When inserting data into the table mail_account there is a default value for the column authentication_type.

### Actual behaviour

The expected default value belongs to the wrong column: account_type

### Additional information

SQL for mail_accounts is only used during automatic deployment for test environments. Accounts created in the GUI are not affected.

Accounts migrated from prior version are properly migrated, only the default value for the column is still missing.

**Comment by jepf** [comment]
Will be fixed for release 6.3.2.
