### ISSUE TITLE
Owner field does not appear in reports

### ISSUE THREAD

**Issue by andresantini2022** [znuny/Znuny#229]
Hello Znuny community
When I make a report, the owner field does not appear in any option. I need to know the number of tickets per owner.
Thanks

**Comment by mo-azfar** [comment]
Hi,
Check System Configuration > Stats::UseAgentElementInStats

**Comment by hanneshal** [comment]
Hi @andresantini2022 

thanks for your interest in Znuny and welcome to the community. ❤️ 
Please use GitHub only for issues or bugs. 
If you do so, please use the issue template. This is important for us. 

For questions related to the software, please visit:
- [Community forum](https://community.znuny.org)
- [Discord Server](https://discord.gg/XTud3WWZTs)

or have a look at the documentation. 

- [Documentation](https://doc.znuny.org/)

Thanks
Johannes
