### ISSUE TITLE
Bug - OAuth 2 refresh token deleted by accident

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny#230]
### Environment

- OS:           n.a.
- Browser:      n.a.
- Znuny version: 6.3.1

### Expected behaviour

An existing refresh token is keep available until he is invalid.

### Actual behaviour

The refresh token is deleted if a new token is requested manually in the GUI.

### How to reproduce

1. Create an OAuth token
2. Initially request a token
3. Request a token again in the GUI
4. See the missing refresh token in the GUI

### Additional information

This issue could only be confirmed for Google Mail / Google Workspace OAuth credentials.

### Workaround

Do **NOT** obtain a token manually, the automatic mechanism works as expected. To fix a missing refresh token an new OAuth Client ID w/ credentials and an new OAuth token needs to be created.

**Comment by jepf** [comment]
Fixed for release 6.3.2: https://github.com/znuny/Znuny/commit/f2f7dbddb1e55c5f0ac153b48d4184f843e35565
