### ISSUE TITLE
Bug - Sisimai version check error in 6.3.1 otrs.CheckModules.pl

### ISSUE THREAD

**Issue by michieltimmers** [znuny/Znuny#234]
### Environment

- OS:           Ubuntu 20.04.4 LTS
- Browser:      n/a
- Znuny version: 6.3.1

### Expected behaviour
"/opt/otrs/bin/otrs.CheckModules.pl --all" should report versions correctly

### Actual behaviour
/opt/otrs/bin/otrs.CheckModules.pl --all
...
...
Argument "v4" isn't numeric in sprintf at /opt/otrs/bin/otrs.CheckModules.pl line 946.
  o Sisimai..........................ok (vv4.25.11)
..
..

### How to reproduce

Execute /opt/otrs/bin/otrs.CheckModules.pl --all on Ubuntu 20.04.4 LTS

### Additional information

Not sure if this is a problem with Sisimai reporting the version incorrectly. Just letting you know.

**Comment by hanneshal** [comment]
Hi, 

this is fixed for upcoming versions:

https://github.com/znuny/Znuny/commit/2cc08972ee77005e124df498385e413d1840b1d9

Regards

**Comment by hanneshal** [comment]
Fixed in 6.3.2+
