### ISSUE TITLE
Bug - Refresh in Overviews wont work if FullTextSearch in Toolbar is not enabled

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#237]
### Environment

- OS:           all
- Browser:      all
- Znuny version: 6.0.40+

### Expected behaviour

If a user sets a refresh time, the overviews should refresh

### Actual behaviour

A JS error is thrown.

### How to reproduce

1. Configure a refresh time in the personal settings
2. Open AgentTicketQueue
3. Send mail
4. Wait for refresh time to be reached, at least once
4. See error in the JS console

### Additional information

This is a regression produced by https://github.com/znuny/Znuny/issues/182

### Screenshots

![image](https://user-images.githubusercontent.com/804939/163138123-02ead58c-e6aa-4d37-99a7-469f4dca5fa2.png)

**Comment by rkaldung** [comment]
Fixed with today's release of Znuny LTS 6.0.41 / Znuny 6.3.2
