### ISSUE TITLE
Bug - scripts/DBUpdate-to-6.pl broken in 6.0.41

### ISSUE THREAD

**Issue by michieltimmers** [znuny/Znuny#239]
### Environment

- OS:  Ubuntu 20.04.4 LTS
- Browser:   Chrome 
- Znuny version: 6.0.41

### Expected behaviour

I'm was trying to upgrade from Otrs 5.0 to Znuny 6.0.41 using these instructions [1]. And with version 6.0.40 the scripts/DBUpdate-to-6.pl works without any problems.

### Actual behaviour

`
    scripts/DBUpdate-to-6.pl
    Migration started ...

    Checking requirements ...

    Requirement check for: Check framework version ...
    Requirement check for: Check required Perl version ...
    Requirement check for: Check required database version ...
    Requirement check for: Check database charset ...
    Requirement check for: Check required Perl modules ...
    Requirement check for: Check if database has been backed up ...

        Did you backup the database? [Y]es/[N]o: y

    Requirement check for: Migrate PostMaster pre-filters that execute system commands ...
    Requirement check for: Remove Generic Agent system commands ...
    ERROR: OTRS-DBUpdate-to-6.pl-10 Perl: 5.30.0 OS: linux Time: Sat Apr 23 07:55:02 2022

    Message: Dynamic field configuration is not valid! 
    
    Traceback (17460):
    Module: Kernel::System::DynamicField::Backend::new Line: 61
    Module: Kernel::System::ObjectManager::_ObjectBuild Line: 307
    Module: Kernel::System::ObjectManager::Get Line: 201
    Module: Kernel::System::GenericAgent::new Line: 63
    Module: Kernel::System::ObjectManager::_ObjectBuild Line: 307
    Module: Kernel::System::ObjectManager::Get Line: 201
    Module: scripts::DBUpdateTo6::RemoveGenericAgentSystemCommandCalls::_GetJobsToMigrate Line: 89
    Module: scripts::DBUpdateTo6::RemoveGenericAgentSystemCommandCalls::CheckPreviousRequirement Line: 63
    Module: scripts::DBUpdateTo6::_ExecuteComponent Line: 162
    Module: scripts::DBUpdateTo6::Run Line: 68
    Module: scripts/DBUpdate-to-6.pl Line: 88
    ERROR: OTRS-DBUpdate-to-6.pl-10 Perl: 5.30.0 OS: linux Time: Sat Apr 23 07:55:02 2022
 
    Message: The constructor of Kernel::System::DynamicField::Backend returned undef.

    Traceback (17460):
    Module: Kernel::System::ObjectManager::_DieWithError Line: 628
    Module: Kernel::System::ObjectManager::_ObjectBuild Line: 315
    Module: Kernel::System::ObjectManager::Get Line: 201
    Module: Kernel::System::GenericAgent::new Line: 63
    Module: Kernel::System::ObjectManager::_ObjectBuild Line: 307
    Module: Kernel::System::ObjectManager::Get Line: 201
    Module: scripts::DBUpdateTo6::RemoveGenericAgentSystemCommandCalls::_GetJobsToMigrate Line: 89
    Module: scripts::DBUpdateTo6::RemoveGenericAgentSystemCommandCalls::CheckPreviousRequirement Line: 63
    Module: scripts::DBUpdateTo6::_ExecuteComponent Line: 162
    Module: scripts::DBUpdateTo6::Run Line: 68
    Module: scripts/DBUpdate-to-6.pl Line: 88

    The constructor of Kernel::System::DynamicField::Backend returned undef. at /opt/znuny-6.0.41/Kernel/System/GenericAgent.pm line 63.

`
### How to reproduce

upgrade from otrs 5 to Znuny 6.0.41. Running the DBUpdate-to-6.pl scripts produces errors.

### Additional information

[1] https://doc.znuny.org/doc/manual/admin/6.0/en/html/updating.html

**Comment by hanneshal** [comment]
Hi @michieltimmers ,

Should be fixed in the current release

https://www.znuny.org/en/releases/znuny-6-3-3

Regards

**Comment by darim92** [comment]
Same error when trying to update from 6.0.37 to 6.0.42

**Comment by hanneshal** [comment]
Hi @darim92 

sadly you are right. This is on me, I forgot a merge request. 
We update the branch and I will post the "how to patch" notes here.

**Comment by hanneshal** [comment]
Hi @darim92 @michieltimmers 

we released 6.0.43 which finally includes the correct merge request.

Please test and let me know if everything is working fine again.

Regards
Johannes

**Comment by darim92** [comment]
@hanneshal could update with no errors.  Thanks!
