### ISSUE TITLE
Update Sisimai

### ISSUE THREAD

**Issue by reneeb** [znuny/Znuny#24]
If a mail is bounced from Google and the bounce email doesn't include a reason or Sisimai doesn't know the reason yet, the module tries to dereference a non-existent arrayreference (https://github.com/znuny/Znuny/blob/2fd5b6d39955590a4c14ba9348b5500b59c51a78/Kernel/cpan-lib/Sisimai/Rhost/GoogleApps.pm#L119). Hence Postmaster can not handle that email.

A sample mail was posted to the Otterhub forum at https://community.znuny.org/viewtopic.php?p=171385#p171385

This was fixed in Sisimai in April 2020: https://github.com/sisimai/p5-sisimai/commit/f2ec10f9b47d03dfcd0bd54d6cc2893b4ab4d9e9

**Comment by dennykorsukewitz** [comment]
Hi @reneeb,

i had the cheek to set you as assignees. 😄

**Comment by reneeb** [comment]
I will prepare a PR next week (this week is German Perl Workshop ;-) )
