### ISSUE TITLE
Bug - No comma in Cache-Control headers

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#240]
### Environment

- OS:           any
- Browser:      any
- Znuny version: 6.0.x

### Expected behaviour

Cache-Control headers shoudlAccording to

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
https://datatracker.ietf.org/doc/html/rfc7234#appendix-C

directives in `Cache-Control` header should be separated with comma i.e.
```
Cache-Control: max-age=604800, must-revalidate
```
but there there is no comma in `Cache-Control` headers set in

https://github.com/znuny/Znuny/blob/dev/scripts/apache2-httpd-plack-proxy.conf
https://github.com/znuny/Znuny/blob/dev/scripts/apache2-httpd.include.conf

### Actual behaviour

The comma in the headers is missing

### How to reproduce

See linked files

### Additional information

None

### Screenshots

None

**Comment by jepf** [comment]
@pboguslawski 

Thank you. Has been fixed and will be part of Znuny 6.0.44 and 6.4.1.
