### ISSUE TITLE
Bug - Bulkaction while using accounted time not working

### ISSUE THREAD

**Issue by bjko** [znuny/Znuny#241]
### Environment

- OS: debian 11  server, windows 10 client         
- Browser:  firefox 99, chrome 100     
- Znuny version: 6.3.1

### Expected behaviour

As soon as it is necessary to enter the accounted time, this should also be available in the note when executing the bulk action (by the way, this was still the case in v 6.1) and not only in the e-mail. As soon as a value has been entered in the accounted time, the bulk action should be able to be executed as usual.

### Actual behaviour

In the bulk action note, the input field for the accounted time is missing. This means that you can only enter a value in the e-mail. Since sending a mail is usually not desired, the bulk action can no longer be executed. The error occurs that the accounted time is to be entered in the e-mail, although this is not desired.
The error can be reproduced repeatedly with activated account time.

### How to reproduce

1. activate Accountedtime, configure input as necessary
2. Select several tickets for the bulk action.
3. Open the tab Note, the input field for the Accountedtime is missing. Open the tab Email, the input field for Accountedtime is available.
4. Close both tabs again without input and continue input (e.g. close tickets) for bulk action. 
5. execute Bulkaction
6. an error message is displayed for the entry of the accounted time in the e-mail tab. 7.
Bulkaction cannot be executed without completely filling out the e-mail tab, even though this was not desired.

**Comment by rkaldung** [comment]
Fixed with https://github.com/znuny/Znuny/commit/884540db38a7874f5bfb98e3c17fbd34d921aec5 and part of the next release
