### ISSUE TITLE
Bug - Log Message for public calendar items

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#242]
### Environment

- OS:          macOS
- Browser:      Chrome
- Znuny version: 6.3.2

### Expected behaviour

No error message should be logged, if a public calendar item - feed is loaded

### Actual behaviour

A log message is shown. 

[Mon Apr 25 21:14:24 2022][Error][Kernel::System::Calendar::Plugin::Ticket::Link::LinkList][311] Need URL!

### How to reproduce

1. Create calender
2. Create event
3. Copy public link
4. Open Link in  a browser 
5. Error is logged

### Additional information

The reason for this is the refactored plugin hierarchy. 
The LinkList is called, without a needed URL attribute:

K/S/C/Export/ICal.pm

```perl
        # include plugin (link) data
        my $PluginList = $PluginObject->PluginList();
        for my $PluginKey ( sort keys %{$PluginList} ) {
            my $LinkList = $PluginObject->PluginFunction(
                PluginKey      => $PluginKey,
                PluginFunction => 'LinkList',
                PluginData     => {
                    AppointmentID => $Appointment{AppointmentID},
                    UserID        => $Param{UserID},
                }
            );

            my @LinkArray;
            for my $LinkID ( sort keys %{$LinkList} ) {
                push @LinkArray, $LinkList->{$LinkID}->{LinkID};
            }

            if (@LinkArray) {
                $ICalEvent->add_properties(
                    "x-otrs-plugin-$PluginKey" => join( ',', @LinkArray ),
                );
            }
        }

```

**Comment by jepf** [comment]
Fixed in upcoming release 6.3.4.
