### ISSUE TITLE
Bug - Missing menue on package installation errors

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#243]
### Environment

- OS:           Linux
- Browser:      Chrome
- Znuny version: 6.3.3.22.118
- Plugin: ArticleCopyMoveDelete
### Expected behaviour

The menu items must not disappear on errors during package installation

### Actual behaviour

When an error was occured during package installation, the menu items have disappeared

### Screenshots

![image](https://user-images.githubusercontent.com/72391822/165941671-6d7f1bfb-9a54-48f5-9bcb-86b13f757f9d.png)

**Comment by jepf** [comment]
Internal MR: 517

**Comment by jepf** [comment]
@schnudd31do3 

Thank you. The fix will be part of the next release.
