### ISSUE TITLE
Bug - Two dashboard widgets enabled after Update

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#247]
### Environment

- OS:           any
- Browser:      any
- Znuny version: 6.0.43

### Expected behaviour

Changed default behaviuour. 
Previously enabled Dashboard Widgets should not be enabled during an update.

### Actual behaviour
Consider disabling `DashboardBackend###0200-Image` and `DashboardBackend###0210-MOTD` by default again to avoid too many unnecessary items.

See Commit: https://github.com/znuny/Znuny/commit/42458dad68f330e3f94294348de29e48cc9432c8
### How to reproduce

1. Widgets are enabled directly after an patch level update

### Additional information

None

### Screenshots

None

**Comment by hanneshal** [comment]
Hi @pboguslawski 

I changed your report to the template, which should be used for all kinds of issues.
We will have a look into it. 

Also I removed your duplicate comment to an irrelevant site.

**Comment by jepf** [comment]
@pboguslawski 

Thank you! This was by accident (and only in the 6.0 version, not in 6.3). The fix will be part of Znuny 6.0.44.

**Comment by pboguslawski** [comment]
Still not fixed in rel-6_0-dev. See https://github.com/znuny/Znuny/pull/248 for fix.

**Comment by hanneshal** [comment]
thats why @jepf wrote:
> The fix will be part of Znuny 6.0.44.

It is already available in an internal branch
