### ISSUE TITLE
Bug - CmdOutput.t should be removed

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#249]
### Environment

- OS:           any
- Browser:      any
- Znuny version: 6.0.43

### Expected behaviour

Unit test for parameter removed in 42458dad68f330e3f94294348de29e48cc9432c8 should be removed to.

### Actual behaviour

Unit test scripts/test/Selenium/Output/Dashboard/CmdOutput.t still exists.

**Comment by jepf** [comment]
@pboguslawski 

Thank you!
Will be fixed in 6.0.46 and 6.4.3.
