### ISSUE TITLE
how to migrate from otrs 3.3.7 to lates znuny lts release?

### ISSUE THREAD

**Issue by AlBundy33** [znuny/Znuny#254]
Are there any guides or best practices available?

**Comment by rkaldung** [comment]
Hi @AlBundy33,

You have to migrate to each single major and minor version. This is 3.3.7 => 4.0 => 5.0 => Znuny LTS 6.0
Download the manuals for older releases which contain details on how to upgrade, at https://download.znuny.org/releases/doc/doc-admin/
I recommend a test migration with your production data to determine the required downtime. Just make sure that no e-mails are fetched or sent. Preventing the daemon and cronjobs from starting should do the trick. 
Deleting the content of the database table mail_account and configuring the SendmailModul to DoNotSendEmail is an alternative.
