### ISSUE TITLE
Suggestion: Consider not referring to $HttpType in OAuth2Token.pm's GetAuthorizationCodeRequestRedirectURL subroutine

### ISSUE THREAD

**Issue by jmoeller-ua** [znuny/Znuny#256]
The subroutine [GetAuthorizationCodeRequestRedirectURL in OAuth2Token.pm](https://github.com/znuny/Znuny/blob/bbbf5a0df0d1927c744d661639e767c6868f784e/Kernel/System/OAuth2Token.pm#L238) relies on the Frontend::Base::HttpType setting, but the Redirect URIs will always begin with "https" regardless of end-user configuration; [Microsoft](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url) and [Google](https://developers.google.com/identity/protocols/oauth2/web-server#uri-validation) require that (non-local) URIs begin with "https" when configuring the URIs on their end. 

I believe "http" is the default HttpType setting, so as its written now this sub will generate the redirect URIs incorrectly and then OAuth2 configuration fails with an error. In Microsoft's OAuth2, this is error code 50011: _The {redirectTerm} '{replyAddress}' specified in the request does not match the {redirectTerm}s configured for the application '{identifier}'._ redirectTerm will have a leading http:// , but https:// is needed. 

It might make sense to disregard the HttpType setting in this submodule so that the URI generated is always correct. We were able to find our mistake eventually, and update our HttpType to be "https" so the OAuth2 integration works, but it took us a while, and it seems like they should be decoupled in this particular case. I'm not sure if changing that setting leads to any unintended consequences.

**Comment by dignin** [comment]
Thanks for your input, we are adding this to the documentation.
