### ISSUE TITLE
Bug - Custom translation xx_Custom.pm is not loaded when xx_Survey_Custom.pm is present

### ISSUE THREAD

**Issue by sergiykhan** [znuny/Znuny#260]
### Environment

- OS: Windows
- Browser: Chrome (latest)
- Znuny version: 6.0.40

### Expected behaviour
Custom translation files for the Survey package should not be preventing loading custom translation files for the web-interface. For example, `fr_Survey_Custom.pm` prevents  `fr_Custom.pm` from being loaded.

### Actual behaviour
Let's take `fr` as an example. If the file `fr_Survey_Custom.pm` is present in `Kernel/Language`, it works for the survey page that users see, as expected (based on their browser's language priority). However, it prevents loading `fr_Custom.pm` for the web-interface. None of the custom translations appear in the web-interface and the file `fr_Custom.pm` does not appear to be read by Znuny at all.

### How to reproduce
1. Create a custom language file for `fr`: `Kernel/Language/fr_Custom.pm`, make sure that it works in the web-interface when `Français` is set in the preferences of an agent.
2. Install the Survey package
3. Create a custom language file for the Survey `Kernel/Language/fr_Survey_Custom.pm`
4. Verify that custom translations set in `Kernel/Language/fr_Custom.pm` do not appear in the web-interface anymore
5. Delete `Kernel/Language/fr_Survey_Custom.pm`
6. Verify that custom translations set in `Kernel/Language/fr_Custom.pm` appear in the web-interface once again

**Comment by hanneshal** [comment]
Hi,

I don't think this is a bug, but how it is implemented (and so somewhat intended). 
There is no special handling for custom translations. The name determines the processing order.
So your file is loaded but the content is "overridden" by the Survey, which is loaded after your custom file.

Thats one of the reasons there are ZZZ_* files ins the Kernel/Config/Files Folder. So that they are loaded at the end. 
Not ideal, I agree. But we can't change the whole mechanism at the moment. 

Back to your issue:
For example: If you name your file fr_ZZZ_Custom.pm it should load just fine.

let me know if this helps.

Regards 
Johannes

**Comment by hanneshal** [comment]
Edit: Can you paste an example of the strings please. Maybe they are related to the JS Translatable core.

**Comment by sergiykhan** [comment]
# 1
Renaming `fr_Custom.pm` to `fr_ZZZ_Custom.pm` did not help.

Also note that both `fr_Survey_Custom.pm` and `fr_Custom.pm` contain

```
    $Self->{Translation} = {
        %{$Self->{Translation}},
        <settings>
    };
```

so, there is no overwriting of an entire file.

# 2
Furthermore, if I introduce a syntax error into `fr_Custom.pm` (say, double trailing `'` at the end of a string), I see no errors in `otrs.log` provided `fr_Survey_Custom.pm` is present.

If I remove `fr_Survey_Custom.pm`, then I start seeing errors in `otrs.log`, such as this one
```
[Tue Jun 21 13:35:01 2022][Error][Kernel::Language::new][201] Bad name after Administration' at /opt/otrs//Kernel/Language/fr_Custom.pm line 17.
Compilation failed in require at /opt/otrs//Kernel/System/Main.pm line 86.
```

Therefore, I conclude that when `fr_Survey_Custom.pm` is present, `fr_Custom.pm` is not being read at all.

# 3
Here is a minimum reproducible example
```
$ cat fr_Custom.pm

package Kernel::Language::fr_Custom;

use strict;
use warnings;
use utf8;

use vars qw(@ISA $VERSION);

sub Data {
    my $Self = shift;

    # $$START$$
    $Self->{Translation} = {
        %{$Self->{Translation}},
        'Customer User Management' => 'Recherche dans le LDAP'',
        'Customer User Administration' => 'Recherche dans le LDAP',
    };

    # $$STOP$$
    return;
}

1;
```

```
$ cat fr_Survey_Custom.pm

package Kernel::Language::fr_Survey_Custom;

use strict;
use warnings;
use utf8;

use vars qw(@ISA $VERSION);

sub Data {
    my $Self = shift;

    # $$START$$
    $Self->{Translation} = {
        %{$Self->{Translation}},
        'Introduction' => 'Introduction',
        'Please answer these questions' => 'Veuillez répondre aux questions suivantes',
    };

    # $$STOP$$
    return;
}

1;
```

**Comment by hanneshal** [comment]
Question... is there a reason why you use:
```
    $Self->{Translation} = {
        %{$Self->{Translation}},
      ...
    };

```
and not just add only your translations to the new file?

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/804939/174816631-217d9097-7e4b-424c-abd9-2be9a10237c9.png">

**Comment by sergiykhan** [comment]
`xx_Custom.pm` distributed with Znuny offers two ways to construct a custom language file. We picked the way that is more concise for a file with many lines. Why do you ask? It makes no difference for the bug reported here. Were you able to reproduce it?

**Comment by hanneshal** [comment]
I can reproduce it not quite.... 

this works fine - Filename: fr_Survey_Custom.pm

```perl
# --
# Copyright (C) 2001-2020 OTRS AG, https://otrs.com/
# --
# This software comes with ABSOLUTELY NO WARRANTY. For details, see
# the enclosed file COPYING for license information (GPL). If you
# did not receive this file, see https://www.gnu.org/licenses/gpl-3.0.txt.
# --

package Kernel::Language::fr_Survey_Custom;

use strict;
use warnings;
use utf8;

sub Data {
    my $Self = shift;

    # Template: AgentSurveyAdd
    #$Self->{Translation}->{'Create New Survey'} = 'Créer un nouveau sondage - Znuny';
    $Self->{Translation} = {
        %{$Self->{Translation}},
        'Create New Survey' => 'Créer un nouveau sondage - Znuny',
    };

    return;

}

1;
```


My question is more does the "first" way, I showed in my screenshot and which is enabled by default work in your environment?

Question: did you try to restart the webserver process after your change?

**Comment by sergiykhan** [comment]
No, it makes no difference. See below.

Translations from `fr_Custom.pm` do not appear in the Znuny interface for as long as `fr_Survey_Custom.pm` is present.

For example, if both files (see below) are present, the survey interface correctly shows "Veuillez répondre aux questions suivantes", however, the Znuny interface does not show "Recherche dans le LDAP" but rather "Administration des utilisateurs client" from `fr.pm`.

If `fr_Survey_Custom.pm` is deleted, the Znuny web-interface correctly shows "Recherche dans le LDAP" under the "Clients/Customers" menu.


## `fr_Custom.pm`

```
package Kernel::Language::fr_Custom;

use strict;
use warnings;
use utf8;

use vars qw(@ISA $VERSION);

sub Data {
    my $Self = shift;

    # $$START$$
    $Self->{Translation}->{'Customer User Management'} = 'Recherche dans le LDAP';
    $Self->{Translation}->{'Customer User Administration'} = 'Recherche dans le LDAP';

    # $$STOP$$
    return;
}

1;
```

## `fr_Survey_Custom.pm`
```
package Kernel::Language::fr_Survey_Custom;

use strict;
use warnings;
use utf8;

use vars qw(@ISA $VERSION);

sub Data {
    my $Self = shift;

    # $$START$$
    $Self->{Translation}->{'Introduction'} = 'Introduction';
    $Self->{Translation}->{'Please answer these questions'} = 'Veuillez répondre aux questions suivantes';

    # $$STOP$$
    return;
}

1;
```

**Comment by hanneshal** [comment]
Hi,

now we got it. The reason for this, the system/the code allows only one _Custom file to be present:
https://github.com/znuny/Znuny/blob/dev/Kernel/Language.pm#L165

So it gets loaded at the end and not, like I wrote before, by name. 
We learned something. 
We don't run into this issue, because we usually simply create new ones and deploy them with a package.
Example: fr_SURVEY_YOURCOMPANYNAMEGOESHERE.pm would work fine, if you need multiple files.

So the solution, because we don't want to change this mechanism, use only one "_Custom" file or modify the name of your file.

We will update the docs for this.

**Comment by sergiykhan** [comment]
Thanks! Indeed, both solutions worked:
- multiple files: rename  `fr_Survey_Custom.pm` to `fr_Survey_Custom1.pm`
- single file: remove `fr_Survey_Custom.pm`, and add custom translation strings for the Survey package into `fr_Custom.pm`

I actually prefer the single file approach!
