### ISSUE TITLE
No packages found in repository

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#261]
### Environment

- OS:           Linux
- Browser:      Chrome
- Znuny version: 6.3.4

### Expected behaviour

List of available packages is full, not containing the installed packages

### Actual behaviour

Empty list, message "No packages found in repository"
![image](https://user-images.githubusercontent.com/72391822/175308687-49624bc5-df86-427a-a494-f3a72feffb0e.png)

Error message in the system log:
![image](https://user-images.githubusercontent.com/72391822/175310218-9cd5ec97-ff6e-4e07-ae80-b16b03cbcc4d.png)

When open the requested URL manually I get
![image](https://user-images.githubusercontent.com/72391822/175309539-0f74b1a8-4b6a-4b95-9d53-db9e70afddba.png)

Reason:
Double slashes in the URL at the position bevore "otrs.xml". But when calling the URL with one slash at this position, I get the content of the otrs.xml

#### Modification for solving
**Package.pm**
_line ~ 1460:_
Change
URL => $Param{Source} . '/otrs.xml',
to
URL => $Param{Source} . 'otrs.xml',
_Line ~ 1468:_
Change
$DownloadParams{URL}             = $Repository->{URL} . '/otrs.xml';
to
$DownloadParams{URL}             = $Repository->{URL} . 'otrs.xml';

**Comment by hanneshal** [comment]
Hi @schnudd31do3 ,
this was only a temporary problem on the load balancer during a maintenance and is resolved by now.

Edit: we will update the code upstream and don't modify LTS. 

Regards
Johannes
