### ISSUE TITLE
Bug - Statistics Help Link Opens OTRS Documentation instead of Znuny Documentation

### ISSUE THREAD

**Issue by jtrumm** [znuny/Znuny#263]
### Environment

- OS:           Windows
- Browser:      Firefox
- Znuny version: 6.0.40

### Expected behaviour

The help button "Read more about statistics in OTRS" links to the corresponding Znuny manual page "https://doc.znuny.org/doc/manual/admin/6.0/en/html/statistics-module.html" and is renamed, replacing "OTRS" with "Znuny"

### Actual behaviour

The help button "Read more about statistics in OTRS" open the OTRS documentation page "https://doc.otrs.com/doc/manual/admin/6.0/en/html/statistics-module.html".

### How to reproduce

1. Go to 'Reports -> Statistics -> Add Statistics'
2. Verify the link for button 'Read more about statistics in OTRS'. It links to doc.otrs.com instaed of doc.znuny.org.

### Additional information

Please regard this issue as a minor inconvenience.

### Screenshots

![Statistics Help Link Pointing to OTRS Documentation](https://user-images.githubusercontent.com/5574410/177167241-2a74ffc5-2c2e-4f5e-b1ed-b0576e1c4a30.png)

**Comment by NiklasSchmitt** [comment]
all affected links was changed in the meantime. I'll close this issue now.
