### ISSUE TITLE
Bug - Dynamic field web service selection list is not filled with display values returned

### ISSUE THREAD

**Issue by samueldc** [znuny/Znuny#264]
### Environment

- OS:          Windows 10 | WSL2 | Debian Bullseye Container
- Browser:      Chrome
- Znuny version: 6.3.4

### Expected behaviour

The dynamic field web service selection list must be filled with display values returned by invoker.

### Actual behaviour

The field test show the values returned, but no entry is found at the list.

### How to reproduce

1. Set up a new dynamic field web service.
2. Click on test settings.
3. Verify the test table below is filled with entries.
4. Verify the field list is empty.

### Additional information

None.

### Screenshots

![image](https://user-images.githubusercontent.com/1208323/177628231-2c283dc5-12dd-4049-a4ce-46c05bee6cb3.png)

**Comment by hanneshal** [comment]
Hi @samueldc 
can you post the complete for this field. This would help us a bit.

Thanks

**Comment by samueldc** [comment]
Sure! Here it goes:

![image](https://user-images.githubusercontent.com/1208323/177769741-b504967f-5ad4-46f5-8d48-ea7d7f327357.png)

![image](https://user-images.githubusercontent.com/1208323/177769824-b9231e62-1c1b-4281-ac34-50d16ada5c18.png)

![image](https://user-images.githubusercontent.com/1208323/177769973-77deeaa4-65cd-41c7-a45a-1dbc9bc19b9f.png)

Also, here it goes the web service config. It's a public one:

[DadosAbertos.zip](https://github.com/znuny/Znuny/files/9063393/DadosAbertos.zip)

**Comment by samueldc** [comment]
Hi,

Just to inform I've upgraded to version 6.3.4 and verified the same behavior.

**Comment by rkaldung** [comment]
Hi @samueldc,

There are two issues here with your configuration, none of them is a bug.

1.) You have selected ResponseValues as a backend but there is no inbound mapping to create the [required data structure](https://doc.znuny.org/manual/admin/dynamicfields/webservice.html):
```
{
    "response": {
        "returncode": "200",
        "returnmessage": "Success"
    },
    "values": [
        {
            "ID": "1",
            "Name": "John",
            "City": "Berlin"
        },
        {
            "ID": "2",
            "Name": "Jane",
            "City": "Coronado"
        }
    ]
}
```
Here a configuration updated for this [DadosAbertos.yml.zip](https://github.com/znuny/Znuny/files/9069035/DadosAbertos.yml.zip)


2.) You do not have an invoker that retrieves the record for a stored id (invoker to get a record). The stored id needs to be retrieved by accessing https://dadosabertos.camara.leg.br/api/v2/deputados/:ID regarding the web service you're using.

I only created a part of it in the attached web service, there's still work to do.
