### ISSUE TITLE
Different "From" in article and email

### ISSUE THREAD

**Issue by chrign** [znuny/Znuny#267]
### Environment

- Znuny version: 6.3.4

### Expected behavior

I have a web form where a user can create a support request. 
The backend of this form uses the web interface with the Ticket::TicketCreate action to create a new ticket in our Znuny system. 
The user should receive an email with all the information of the ticket and he should be able to reply to that email to add information to the ticket. 
The ticket in Znuny should contain 1 article with the "From:" set to the customers email. 

### Actual behavior

I'm trying to use this extension (or the version that is integrated in later versions of Znuny) to accomplish the expected behavior.
I fill out the "ArticleSend" and "To" with the customers email.
But I have the following problem: 

If I set the "From" field in the REST request to the customers email address:
 :white_check_mark: The agent can click on "Reply" in Znuny and the "To" field is automatically populated with the email address of the customer
 :x: The initial email received by the customer by this extension is send "from" the customer himself. He cannot easily reply to that email.

If on the other hand I leave the "From" field in the REST request empty:
 :x: When the agent clicks on "Reply" in Znuny the "To" field is empty. He has to manually enter the customers email address.
 :white_check_mark: The email send to the customer is received from the znuny system, and the customer can simply click on reply in his email software to add something to the ticket.

Is there a possibility to split the "From" from the article and the initial "ArticleSend" email? 

### How to reproduce

```php
$data = [
    'UserLogin' => OTRS_USER,
    'Password' => OTRS_PASSWORD,
    'Ticket' => [
        'Title' => 'test',
        'CustomerUser' => $customerEmail,
        'CustomerID' => $customerEmail,
        'Queue' => 'Raw',
        'State' => 'new',
        'Priority' => '3 normal',
    ],
    'Article' => [
        'Subject' => 'test',
        'Body' => 'test body',
        'MimeType' => 'text/plain',
        'Charset' => 'utf8',
        //'From' => $customerEmail,
        'SenderType' => 'customer',
        'CommunicationChannel' => 'Email',
        'ArticleSend' => '1',
        'To' => $customerEmail,
    ]
];

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, OTRS_URL . "/TicketCreate");
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
curl_exec($ch);
```

**Comment by hanneshal** [comment]
Hi @chrign ,

I transferred the issue to the main project because the addon itself is integrated in the Znuny Core.

Regarding you issue:
I understand your use case, but don't understand the two ways of answering.

The REST API allows you to send Article, as Mail, to a an external source.
So the "To" should always be your customer mail.
The "FROM" is the system sender address you want to use.
An E-Mail is then sent to the customer and he should be able to reply. 


```
curl -X "PATCH" "https://ZNUNYHOST/nph-genericinterface.pl/Webservice/GenericTicketConnectorREST/Ticket/1" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "Password": "USERPASWORD",
  "UserLogin": "USERLOGIN",
  "Article": {
    "ArticleSend": 1,
    "To": "community@znuny.com",
    "ContentType": "text/html; charset=utf8",
    "From": "devnull@znuny.com",
    "Subject": "Test Notiz 2",
    "Body": "<b>abcdef</b>ghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
  }
}'
```

Will send an E-Mail to the User (community@znuny.com) and the sender is a system address (devnull@znuny.com).
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/804939/179783068-c44a0fdf-0343-470c-8e7d-565d1dc35483.png">

So maybe I miss something, but it works exactly as designed and correct (IMHO).

Regards and let me know where I miss it :D 

Johannes

**Comment by chrign** [comment]
Hi @hanneshal, 

Your example has nudged me in the right direction. 
I have to change the "SenderType" to "agent" or omit it. When doing so, and also omitting the "From" field, both the reply button in Znuny and the customers email client work as expected!

I guess one could argue that the message direction arrow in Znuny for that message is wrong, as it is actually a customer message and not an agent message. But that doesn't really matter to me. :) 

Thank you for helping me out.
