### ISSUE TITLE
Bug - Last agent article created using a process dialog is ignored by the notification mechanism that substitutes tags

### ISSUE THREAD

**Issue by samueldc** [znuny/Znuny#275]
### Environment

- OS:           Windows | WSL2 | Docker | Debian 11
- Browser:      Chrome
- Znuny version: 6.3.4

### Expected behaviour

A triggered notification using <OTRS_AGENT_BODY[100]> tag should (IMHO) capture the last agent article even if it was created using a process activity dialog with a article field. 

### Actual behaviour

<OTRS_AGENT_BODY[100]> tag only captures the last agent article created using the available Note menu option. An agent article created using a process activity dialog is ignored by the notification mechanism that substitutes tags.

### How to reproduce

1. Create a notification using <OTRS_AGENT_BODY[100]> with some trigger rule (maybe using a dropdown dynamic field).
2. Create and deploy a process with two activity dialogs: the first with a article field using OTRS channel (note) and the second activity with some field that triggers the notification.
3. Start the process and create a note article using the Note menu option.
4. Using the second activity, trigger the notification.
5. Check if the last agent article body is properly captured in the notification message (it is).
6. Using the first activity dialog, create another note.
7. Using the second actitivy, trigger the notification again.
8. Check if the last agent article body is properly captured in the notification message (it is not).

**Comment by hanneshal** [comment]
HI @samueldc 

I tried this and it works like it should. I used an article with the "OTRS Channel", not visible for the customer. 
And a new notification. 
My trigger is the ticket title.

[Sample_process.txt](https://github.com/znuny/Znuny/files/9254486/Sample_process.txt)
[Export_Notification_Sample_Notification_GH.txt](https://github.com/znuny/Znuny/files/9254496/Export_Notification_Sample_Notification_GH.txt)
Note: To import the process or the notification, you have to rename the file to yml. 

Can you please post a sample process where this error is triggered and your notification please. 
This would help to find the error. 

Thanks

**Comment by samueldc** [comment]
Created another process in a clean installation and couldn't replicate the previus behavior. I'll close the issue until I figure it out for certain. Sorry bother.
