### ISSUE TITLE
Bug - ???

### ISSUE THREAD

**Issue by tune6688** [znuny/Znuny#28]
Dear supporter
Systme: Centos7+Znuny6.032+Chrome
Descriptions: From Adimin-System Configuration to edit the systme configuration settings,it took about afew minutes and clicked the "Deploy selected changes"button,the the system  jumps to the login page.

Please confirm and help solve it.

Thanke you!

**Comment by reneeb** [comment]
Are cookies allowed? Is a session id present in the URL in the admin area?

**Comment by tune6688** [comment]
Dear Reneeb
Thanks for your help. I  using the  web browser to access the otrs6.30 ,all the time.I just cleaned up the browser cache， it now works normally.
Thanks again for your help!
