### ISSUE TITLE
Bug - Attachments to tickets will not be sent

### ISSUE THREAD

**Issue by lhanschen** [znuny/Znuny#282]
### Environment

- OS:           Windows
- Browser:      Edge
- Znuny version: 6.3.x

### Expected behaviour

It should be possible to use edge and add attachments via drag and drop.

### Actual behaviour

When i use znuny in edge browser and create or reply to a ticket and attach a file it is not sent with it.
If I drag and drop the file, no file is sent, if I select the file directly in explorer only the first file is sent if there are more than one file.
The problem is only since the new version 6.3... noticed.

### How to reproduce

1. Create ticket (ATPhone)
2. Drag a file to the attachment area
3. Submit ticket
4. No attachment is added

### Additional information

none

### Screenshots

none

**Comment by tipue-dev** [comment]
I did not see any Issues or PRs related to something like this, so i tried to replicate the bug in the dev-version of Znuny and Znuny-6.3.4 with Edge version 104.0.1293.54. Everything worked on my end as expected.

- Are the attachments visible under the article body in the table before you send the mail?
- Is the type and the size listed in the table
- Does the attachment just not arrive at the recipient, or are they already missing in the article overview of the ticket? 
- Did you test this with other browsers and they are working? 
- Whats the exact Znuny and Edge version. 

This may help finding the problem, if someone else doesn't already know more about the problem and in the case that it isn't just a problem on your end.

**Comment by hanneshal** [comment]
Hi,

thanks for the report. 
Two questions:
- Does the browser console in the developer tab show an error?
- is this independent from file size / name ?

A note: please use the issue template for you next issue. It helps us to get things sorted.
Thanks

**Comment by lhanschen** [comment]
> Hi,
> 
> thanks for the report. Two questions:
> 
> * Does the browser console in the developer tab show an error?
> * is this independent from file size / name ?
> 
> A note: please use the issue template for you next issue. It helps us to get things sorted. Thanks

hi,

thanks for the quick reply the problem is probably not due to znuny, but thank you very much.
