### ISSUE TITLE
Bug - Problem with Log Messages on Debian / Ubuntu (Forum Report)

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#286]
### Environment

- OS:           Debian 22
- Browser:      Any
- Znuny version: 6.0.44

### Expected behaviour

Log messages should be written without an error.

Reported here:
https://community.znuny.org/viewtopic.php?p=174991#p174991

### Actual behaviour

An error is reported in the webserver log, if perl 5.34.0+ is used.

[Exception while processing mail: Wide character in shmwrite at /opt/znuny-6.0.44/Kernel/System/Log.pm line 264]

### How to reproduce

1. Setup Znuny on Ubuntu 22.04.1 
2. Check perl version
3. Trigger any log message that includes UTF8 characters

### Screenshots
Who knows what happens, so I posted the analysis by @bschmalhofer here:
![image](https://user-images.githubusercontent.com/804939/186668099-664265af-accb-457f-94c6-759a3fee89f4.png)

**Comment by jepf** [comment]
Will be part of release 6.4.3 (e65d317a5e17a65dab51cd90aceb51dd24a985d4) and 6.0.46 (792d380997469935a8675e5041c2183177be3c2a).
