### ISSUE TITLE
Bug - Field 'customer_ids' doesn't have a default value

### ISSUE THREAD

**Issue by AlBundy33** [znuny/Znuny#287]
### Environment

- OS:             Any
- Browser:    Any
- Znuny version: 6.045

### Expected behaviour

It should be possible to add a customer user in the GUI without throwing an error.

### Actual behaviour

An error is thrown.

```
Field 'customer_ids' doesn't have a default value, SQL: 'INSERT INTO customer_user (title, first_name, last_name, login, email, customer_id, phone, fax, mobile, street, zip, city, country, comments, valid_id, create_time, create_by, change_time, change_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '2022-08-29 16:17:45', ?, '2022-08-29 16:17:45', ?)'
```
### How to reproduce

1. Go to 'Admin'
2. Click on 'Cusomer User'
3. Add Customer User for DB Backend

### Additional information

We recently did a test-migration from our slightly outdated OTRS 3.3.7 to Znuny 6.0.45 (I think).

It seems that all is working as expected but I cannot create a new customer user because of this error:

And yes - I did set a Customer ID on the AdminCustomerUser-page :-)
-> I've tried an existing and also a new Customer ID - both result in the same error. :-(

**Comment by hanneshal** [comment]
HI @AlBundy33 

first a short note: please always use the "Bug Template". I edited your question to match the template.

Regarding your question:
- The field customer_ids is not a default field. Is is/was created by someone in your db. 
- Please also check your Config.pm / Customer User Mapping for the correct values and variables. 
I think there is an issue there with your mapping
- Please check if you see any related log messages in the Admin->System log

I checked it against an 6.0.45 and works fine. So it must be config/change on your side.

This is a sample line, but the field is not created from OTRS and later Znuny. 
https://github.com/znuny/Znuny/blob/dev/Kernel/Config/Defaults.pm#L1539

Did you performed the migration on a fresh folder for this version or did you reused the old one or updated via RPM?

**Comment by AlBundy33** [comment]
I've checked our current (old) otrs-database with
```
select table_schema as database_name,
       table_name,
       column_name,
       column_default,
       is_nullable
from information_schema.columns
where column_name = 'customer_ids'
```
![image](https://user-images.githubusercontent.com/6294586/187401963-d34b0e5a-4bf1-452a-9997-cf937f00eefb.png)

and did a
```
select customer_ids, count(*) from customer_user group by customer_ids
```
which shows two "real" values and a lot of empty values ('')

We searched also in our otrs-installation
```
grep -Ri customer_ids
Kernel/Config/Defaults.pm:#            [ 'UserCustomerIDs', 'CustomerIDs', 'customer_ids', 1, 0, 'var', '', 0 ],
Kernel/Config/Defaults.pm:#            # [ 'UserCustomerIDs', 'CustomerIDs', 'second_customer_ids', 1, 0, 'var', '', 0 ],
Kernel/Config/Defaults.pm_test:#            [ 'UserCustomerIDs', 'CustomerIDs', 'customer_ids', 1, 0, 'var', '', 0 ],
Kernel/Config/Defaults.pm_test:#            # [ 'UserCustomerIDs', 'CustomerIDs', 'second_customer_ids', 1, 0, 'var', '', 0 ],
CHANGES.md: - 2014-04-10 Fixed bug#[9098](http://bugs.otrs.org/show_bug.cgi?id=9098) - The system still consider the customer_ids, even after field is empty on table customer_user.
```
The lines in Defaults.* are commented out and unfortunately the link from Changes.md doesn't exist anymore.

Because we already have a lot of empty `customer_ids` we'll try
```
ALTER TABLE customer_user ALTER COLUMN customer_ids SET DEFAULT '';
```

**Comment by hanneshal** [comment]
Hi, 
thanks for the infos. Please check the file "Kernel/Config.pm" most of this type of config should be done there.
Never, I repeat never change the Defaults.pm

Can you also answer this question I asked earlier.
>Did you performed the migration on a fresh folder for this version or did you reused the old one or updated via RPM?

thanks

**Comment by AlBundy33** [comment]
`grep -i customer Kernel/Config.pm` is empty.
I don't think that we've made changed on Defaults.pm - it was just a result from my grep-command. 😄 

The colleague who did the test-migration is currently on vacation.

**Comment by AlBundy33** [comment]
The upgrade was done woth a copy pf the current installation folder with the sources (so no rpm was used)

**Comment by hanneshal** [comment]
An important note: 
It is good practice to not use the "old" instance folder. Especially when the installations are that old. 
Always use a fresh one and copy the needed config files -> See upgrade path in the docs. 

When one reuses the old folder, old files and customisations might still be around.

Download the tar.gz, extract and symlink the folder to /opt/otrs

Regards

**Comment by AlBundy33** [comment]
We can try that but don't you think that the issue would still exists because the column customer_ids already exists in the database?

**Comment by hanneshal** [comment]
I think there are two things possible:
a) you missed a config during migration
b) some old file ist messing around with you

My guess is for a). An error during the migration. If you really can't find a custom config for your backend then the I bet this is what is missing. 
Is there a field "customer ids" in the gui, when you try to create a new customer?

**Comment by AlBundy33** [comment]
I have a field "CustomerID" where I can select one customer.
But there is no field customer-ids

As mentioned above in our current otrs 3.3.7 installation the column already exists but is also not visible in the gui.
When i create a new customer, the field gets an empty string in the database although no default is set for this column.
-> It seems that our OTRS is setting '' as default somewhere.

But according to my `grep -Ri customer_ids` there are no files with (enabled) customer_ids

**Comment by AlBundy33** [comment]
According to the thread this column seems to be a column from otrs.
https://community.znuny.org/viewtopic.php?t=7531

**Comment by rkaldung** [comment]
The mentioned post just says there is a column customer_ids that could be used. Following the link to the manual, there is clearly stated that you have to create the column on your own and, more important: 
> the new column has to be added to the MAP array in Kernel/Config.pm

If there is no CustomerUser configuration in your Kernel/Config.pm. My guess would be someone modified the Kernel/Config/Defaults.pm which never should be done.
And if you used the same folder for the migration the file Defaults.pm was overwritten.

**Comment by AlBundy33** [comment]
I cannot follow the link I get a "The requested URL was not found on this server."

This output is from the old otrs-installation
```
grep -i customerids Defaults.pm
#            [ 'UserCustomerIDs', 'CustomerIDs', 'customer_ids', 1, 0, 'var', '', 0 ],
#            # [ 'UserCustomerIDs', 'CustomerIDs', 'second_customer_ids', 1, 0, 'var', '', 0 ],
```
So the lines a commented out.

If the docs say, the the column was created manually maybe some has tried this feature in the past.

But it is a bit strange that the column is still filled in the old installation even though it is not configured (and there is also no default in the database)

If znuny doesn't need the column then I'll use the workaround with setting '' as default for the column.

**Comment by hanneshal** [comment]
It's hard to tell because we know anything about your setup / installation and it is much more a thing for the forum. 
But to be sure, you can just have a look in you customer user area. Create a customer and check if there is a customer ids field somewhere. If not, it might be filled from an external source or was configured some time ago. 
If there is also no customer ids field, then it is not configured and you could also simply drop the column. Because it is not needed anymore. 

And again the recommendation for your colleague who performed the migration:
Always use a clean folder and symlink them to /opt/otrs. Don't reuse the old one.
You should end up with:
- 3.3.
- 4.0
- 5.0
- 6.0
- 6.1
- 6.2 and so on


After the migration you can just delete all the old folders, if everything is ported.
If you have your attachments stored in the FS, you can copy them directly to the final folder or just use a mount for it. 

I will close this issue.
