### ISSUE TITLE
Bug - Some OAuth2 tokens can't be stored in the database

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny#289]
### Environment

- OS:           n.a.
- Browser:      n.a.
- Znuny version: 6.4.2

### Expected behavior

The obtained OAuth2 tokens (refresh and access) are stored in the database.

### Actual behavior

Some tokens' size exceeds 2000 characters. This is the limit of the columns token and refresh_token, table oauth2_token.
According to the RFC6749 there is no specified length:

> The sizes of tokens and other values received from the authorization
> server are left undefined.  The client should avoid making
> assumptions about value sizes.  The authorization server SHOULD
> document the size of any value it issues.

### How to reproduce

1. Create a new app in the Microsoft Azure Portal.
2. Assing way more API permissions as needed, this will "blow" up the token.
3. Check the application log for the error

### Additional information

1.) The mentioned columns type depends on the used DBMS, e.g. for MySQL a text column is generated which works, for PostgreSQL a VARCHAR(2000) is used which fails in some cases.

2.) As a workaround, the columns `token` and `refresh_token` can be manually altered to more than 2000 characters.

3.) This issue was reported 1st via the [forum](https://community.znuny.org/viewtopic.php?f=34&t=43261).

**Comment by jepf** [comment]
Internal issue: 343

**Comment by rkaldung** [comment]
Fixed with the release of Znuny 6.4.3  (https://github.com/znuny/Znuny/commit/9f6b30d55ca83f94dfad781fb72ebfdae276eb74)
