### ISSUE TITLE
Enable input of the required URLs for OAuth token in the UI

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny#294]
### Environment

- OS:           n.a.
- Browser:      all
- Znuny version: 6.4.2

### Expected behaviour

Creating an OAuth token configuration including the URLs without downloading, editing and uploading the configuration.

### Actual behaviour

The token configuration, e.g. for Microsoft, needs to be downloaded and the URL must be replaced with the URLs from the MS Azure portal. Then the token configuration file must be uploaded.

### How to reproduce

1. Go to Admin => OAuth token
2. Use any Microsoft template
3. Enter the app id and secret
4. Download the token configuration
5. Edit the token configuration
6. Upload the token configuration

### Additional information

Usually there are 3 URLs required:
- Authorize
- Refresh token
- Access token

**Comment by jepf** [comment]
Internal issue: 355

**Comment by rkaldung** [comment]
Fixed with Znuny 6.4.3 (https://github.com/znuny/Znuny/commit/ee4921089bc08cae11259cbea68e2792c51f0833)
