### ISSUE TITLE
Bug - DynamicField Type Webservice (Text) misbehaviour

### ISSUE THREAD

**Issue by eficht** [znuny/Znuny#297]
### Environment

- OS:           Windows
- Browser:      Chrome
- Znuny version: 6.4.3

### Expected behaviour

1. A dynamic field of this type should appear like a normal drop-down (font and size).
2. The value should be returned when using <OTRS_TICKET_DynamicField_[fieldname]_Value> (e.g. in a TransitionAction)

 
### Actual behaviour

1. I use a field of this type in a process in the customer interface - the items in the dropdown list appear in a different size.
2. <OTRS_TICKET_DynamicField_[fieldname]> and <OTRS_TICKET_DynamicField_[fieldname]_Value> both return the key.

### How to reproduce

1.1 Use a dynamic field of this type in a process in the customer interface 
1.2 See non-standard text in the dropdown box

2.1 Use a dynamic field of this type in a process
2.2 Create a TransitionAction (e.g. TicketsArticleCreate) and try to add both <OTRS_TICKET_DynamicField_[fieldname]> and <OTRS_TICKET_DynamicField_[fieldname]_Value>  
2.3 See result

### Additional information

n/a

### Screenshots

1. 
![image](https://user-images.githubusercontent.com/66409340/193027980-af6c8f74-22cb-483e-989c-005b5a7d5942.png)
2. 
![image](https://user-images.githubusercontent.com/66409340/193029288-a4348cdf-6ed9-4009-b072-860f91510240.png)

**Comment by rkaldung** [comment]
@eficht Thank you for reporting. I will create an internal issue with the following topics:
- Return the value which belongs to the key when <OTRS_TICKET_DynamicField_XX_Value> is used
- Add the option to configure a cache TTL per dynamic field to reduce the web requests against an API

**Comment by eficht** [comment]
@rkaldung Thank you for the confirmation, will the CSS-Issue also be fixed?

**Comment by jepf** [comment]
@eficht 

fyi: Replacement of placeholder `<OTRS_TICKET_DynamicField_XX_Value>`  has been fixed for dynamic field type WebserviceText in Znuny release 6.4.4.

**Comment by rkaldung** [comment]
Fixed since Znuny 6.4.4
