### ISSUE TITLE
Bug - [znuny-latest-6.0.tar.gz not updated to last version ]

### ISSUE THREAD

**Issue by joserribeiro26** [znuny/Znuny#30]
### Environment

- OS:           
- Browser:      
- OTRS version: 

### Actual behavior

znuny-latest-6.0.tar.gz not updated to last version

### How to reproduce

1. Go to https://download.znuny.org/releases/
2. Click on  znuny-latest-6.0.tar.gz
3. Decompress (today, with version 6.32 and not version 6.0.33)

**Comment by rkaldung** [comment]
@joserribeiro26 Thank you, it's fixed right know. I'll check our pipeline to prevent this in the future.
