### ISSUE TITLE
Inline images in drafts will not display for more than 24 hours

### ISSUE THREAD

**Issue by Andy-Mayer** [znuny/Znuny#309]
### Environment

- OS:           debian 11
- Browser:      Firefox
- Znuny version: 6.0.46

### Expected behaviour

Inline pictures in drafts are visible until draft is deleted after "FormDraftTTL###Ticket"

### Actual behaviour

Inline pictures in drafts are invisible or broken after 24h.

### How to reproduce

1. Add a inline picture in a draft (drag and drop).
2. Wait 24h and the picture is not displayed, only a border is displayed

### Additional information

If I change /opt/otrs/Kernel/System/Web/UploadCache/DB.pm in line 257:

 my $CurrentTile = time() - ( 60 * 60 * 24 * 1 );
to
 my $CurrentTile = time() - ( 60 * 60 * 24 * 7 );

The picture is displayed for seven days, because the DB entry in web_upload_cache will not deleted before seven days.

**Comment by rkaldung** [comment]
@Andy-Mayer Thank you for reporting. 
I can confirm this behavior and I would also classify this as a bug Znuny 6.0.x and Znuny 6.4.x.
The time to delete should use the system configuration `FormDraftTTL###Ticket` in the calculation if an upload belongs to a draft.

The functionality is implemented in FormIDCleanUp() of both modules Kernel/System/Web/UploadCache/DB.pm and Kernel/System/Web/UploadCache/FS.pm

**Comment by jepf** [comment]
Internal issue: 378

**Comment by NiklasSchmitt** [comment]
Hi @Andy-Mayer,
the issue was solved with commit https://github.com/znuny/Znuny/commit/f946d7e2db55386d76f74945f55b11313e41c507 and will be part of the next Znuny version 6.5.1

Best regards,
Niklas :robot:
