### ISSUE TITLE
Invalid znuny.CodePolicy.pl option

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#313]
`--all` used in https://github.com/znuny/Znuny/blob/e83e81a33c8b2c735f255088a4058a521c96a315/.github/workflows/ci.yaml#L49 is not present in https://github.com/znuny/ZnunyCodePolicy/blob/dev/bin/znuny.CodePolicy.pl#L69

Should be `--all-files`?

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski ,

thank you for the report.

>Should be --all-files?

Answer: yes 👍🏼 

Currently, the behavior is almost the same.
https://github.com/znuny/ZnunyCodePolicy/blob/dev/bin/znuny.CodePolicy.pl#L60
`By default it will process all changed files (staged and unstaged) that are already known to Git.`

We will change this to --all-files.

Thank you! :rocket:

**Comment by pboguslawski** [comment]
> By default it will process all changed files (staged and unstaged) that are already known to Git.

Just tested that without any parameters znuny.CodePolicy.pl does not find any files to test. Something wrong problably. No such problem when undocumented `--all` is used.
