### ISSUE TITLE
Bug - ACL misbehaviour in processes

### ISSUE THREAD

**Issue by eficht** [znuny/Znuny#316]
### Environment

- OS: Windows        
- Browser: Chrome     
- Znuny version: 6.4.3 

### Expected behaviour

ACLs in process tickets should not be overridden after customer user selection

### Actual behaviour

An ACL matching process and activity is ignored/reset after selecting the customer user in a process activity dialog.

### How to reproduce

I have attached 2 yml-files

- one for a very simple process (1 activity, 1 activity dialog, no dynamic fields, no transitions, no transition actions)
- one with an ACL which just matches process and activity and reduces queue seletion to "Raw" and type selection to "Incident" 

1. Import the process
2. Import the ACL
3. Change the values for ProcessEntityID and ActivityEntityID in the ACL match settings according to the values generated by process import.
4. Create a process ticket in the agent interface for the process "ACL misbehaviour Demo"
5. According to the ACL the values for queue and type are restricted ("Raw"-queue, "Incident"-type)
6. select a customer user
7. click on queue - see the error - the ACL is ignored and you see all queues you have rights for 
8. click on type - see the error - the ACL is ignored and you see all ticket types

### Screenshots

[Process & ACL to reproduce the issue.zip](https://github.com/znuny/Znuny/files/9973671/Process.ACL.to.reproduce.the.issue.zip)

**Comment by dignin** [comment]
I'm not sure what happens yet, but as a workaround remove the ActivityID from your ACL. If you need, you can re-add the other options at a later date with PossibleAdd.

**Comment by NiklasSchmitt** [comment]
Hi @eficht,

the mentioned issue is resolved by commit https://github.com/znuny/Znuny/commit/1eee38f9b991f0236b902abceea8393f453d8f2c and will be released within the next Znuny version 6.5.

Best regards,
Niklas Schmitt :rocket:
