### ISSUE TITLE
Bug: Search results are covered by my input fields

### ISSUE THREAD

**Issue by joergflorian** [znuny/Znuny#320]
### Environment

- OS: Windows 10           
- Browser: Firefox 107.0, Chrome 107.0.5304.107,  Edge 107.0.1418.56     
- Znuny version:  6.4.4

### Expected behaviour

Results should not be covered by the search mask

### Actual behaviour

When open the customer / customer user search the dropdown is overlaid by the search itself:

### How to reproduce

1. Go to Dashboard
2. Click on Customers > Customer Information Center
3. Enter some chars of a know customer name on the customer search field

### Screenshots

![image](https://user-images.githubusercontent.com/118974183/203758184-72744c2c-2c73-4b14-aa72-80eeddf8990e.png)

**Comment by hanneshal** [comment]
@joergflorian please use the issue template. We need all the information there.
I modified your issue, please fill out the missing ones

**Comment by hanneshal** [comment]
for reference: https://github.com/znuny/Znuny/commit/b8b93bfc28546446ccca1264eed3e4ece87b28bf

**Comment by joergflorian** [comment]
Ok, I added what I know. Thanks

**Comment by hanneshal** [comment]
Hi @joergflorian 
ok, I can't reproduce this. 

Question: what skin do you use?

Default/Slim/blue/...

Can you please check the content of:
https://github.com/znuny/Znuny/blob/dev/var/httpd/htdocs/skins/Agent/default/css/Core.Default.css
https://github.com/znuny/Znuny/blob/dev/var/httpd/htdocs/skins/Agent/default/css/Core.Dialog.css
https://github.com/znuny/Znuny/blob/dev/var/httpd/htdocs/skins/Agent/default/css/Core.InputFields.css

Both, on your browser and you server. 
They should match the ones above.

They have been changed to address exactly this problem. 

Changes are here (may not be complete, but it's a start):
https://github.com/znuny/Znuny/commit/b8b93bfc28546446ccca1264eed3e4ece87b28bf
https://github.com/znuny/Znuny/commit/e4a795a7490002694e8d2fab0bb26de108b4fe23

You can temporary disable the CSS Loader (Sysconfig->Loader::Enabled::CSS => No)

**Comment by joergflorian** [comment]
Hi @hanneshal ,

Thanks. That was the missing link. We use a modified "blue" skin where the Core.Default.css was modified.
I had to made the change as show in you references:

.ui-overlay-autocomplete {
    z-index: 6103 !important;
}

Now everything works fine.

So no bug in Znuny, but in my Skin...

Thanks a lot
Florian
