### ISSUE TITLE
Bug - Web service header values are truncated.

### ISSUE THREAD

**Issue by Tronsy** [znuny/Znuny#321]
### Environment

- OS:           
- Browser:      
- Znuny version: 6.4.x and lower

### Expected behaviour

Additional headers in the network-transport configuration of the invokers and operators should not be shortened.

### Actual behaviour

Values of the additional headers in the network-transport configuration of the invokers and operators are truncated after 150 characters when these are stored in the GUI.
This leads to problems when using longer tokens.

### How to reproduce

1. Create new web service
2. Create an additional header with a value of more than 150 characters.  
3. Save and check again the value of the additional header (should be shorter now)
4. to double-check export the web service and check the length of the header in the YAML or run the web service and check the outgoing data. 

### Additional information

**Workaround:**
Add the header in the YAML configuration of the web service and import it again. (Do not save the network transport over the GUI)

**Comment by jepf** [comment]
Internal issue 489.

**Comment by jepf** [comment]
Part of Znuny 6.5.2 and upcoming 7.0.11.
