### ISSUE TITLE
Bug - 6.4.4 - Invisible Textbox

### ISSUE THREAD

**Issue by KrisChro** [znuny/Znuny#323]
### Environment

- OS:           Any
- Browser:     Any
- Znuny version: 6.4.4

### Expected behaviour

RichText Field should be visible and editable

### Actual behaviour
The unavailable field is marked in red.
However, there is also no description specifying the time spent on the task (marked in orange)

![image](https://user-images.githubusercontent.com/87808782/208077195-5c52e6fe-c710-4830-948f-db6c1e00eb1d.png)

### How to reproduce

The problem occurs at every operation, creating a ticket, holding a ticket, closing or changing the queue.

**Comment by hanneshal** [comment]
Hi @KrisChro 
JFI: I edited you bug report to match the template. 

Two questions:
1) Did you performed an upgrade or a fresh install?
2) Is the browser console showing missing files or JS errors?


What I can say from your screenshot, the RichText Editor is not loaded. Which often is the case on upgrades and older configs.

**Comment by KrisChro** [comment]
> Hi @KrisChro JFI: I edited you bug report to match the template.
> 
> Two questions:
> 
> 1. Did you performed an upgrade or a fresh install?
> 2. Is the browser console showing missing files or JS errors?
> 
> What I can say from your screenshot, the RichText Editor is not loaded. Which often is the case on upgrades and older configs.

1. I upgrade from 6.4.3. In version 6.4.3 everything works fine.
2. I only see the following errors in the browser.
![image](https://user-images.githubusercontent.com/87808782/208084797-82a51c8c-4089-41c6-9637-c9d9037e220b.png)

**Comment by hanneshal** [comment]
I think there is either an issue with your migration or with your config.

- Did you ran the migration script after you PL Update?
- Does this issue also occur when you use a private window?
- Can you please run bin/otrs.Console.pl Maint::Config::Rebuild --cleanup

To get more information, you can set those in your Config.pm
```
        $Self->{'Loader::Enabled::CSS'}  = 0;
        $Self->{'Loader::Enabled::JS'}   = 0;
        $Self->{'Frontend::TemplateCache'} = 0;
```

This disables the template and JS caches.

**Comment by NoobSpielt** [comment]
Hey,
I had the Problem too after a update to 6.4.4. I resolved them with following commands:

```
/opt/otrs/bin/otrs.Console.pl Maint::Session::DeleteAll
/opt/otrs/bin/otrs.Console.pl Maint::Cache::Delete
/opt/otrs/bin/otrs.Console.pl Maint::Config::Rebuild
/opt/otrs/bin/otrs.Console.pl Maint::Loader::CacheCleanup
```

**Comment by rkaldung** [comment]
> Hey, I had the Problem too after a update to 6.4.4. I resolved them with following commands:
> 
> ```
> /opt/otrs/bin/otrs.Console.pl Maint::Session::DeleteAll
> /opt/otrs/bin/otrs.Console.pl Maint::Cache::Delete
> /opt/otrs/bin/otrs.Console.pl Maint::Config::Rebuild
> rm /opt/otrs/var/httpd/htdocs/js/js-cache/*.js
> ```

Hey @NoobSpielt,

Your last step would be bin/otrs.Console.pl Maint::Loader::CacheCleanup which cleans up the Javascript and CSS cache.

**Comment by NoobSpielt** [comment]
> > Hey, I had the Problem too after a update to 6.4.4. I resolved them with following commands:
> > ```
> > /opt/otrs/bin/otrs.Console.pl Maint::Session::DeleteAll
> > /opt/otrs/bin/otrs.Console.pl Maint::Cache::Delete
> > /opt/otrs/bin/otrs.Console.pl Maint::Config::Rebuild
> > rm /opt/otrs/var/httpd/htdocs/js/js-cache/*.js
> > ```
> 
> Hey @NoobSpielt,
> 
> Your last step would be bin/otrs.Console.pl Maint::Loader::CacheCleanup which cleans up the Javascript and CSS cache.

I didn't know there is a way to do this with the otrs-console. I updated my last answer. Thanks^^

**Comment by KrisChro** [comment]
> $Self->{'Loader::Enabled::CSS'}  = 0;
>         $Self->{'Loader::Enabled::JS'}   = 0;
>         $Self->{'Frontend::TemplateCache'} = 0;

Thank you. This solution work perfectly.
