### ISSUE TITLE
Bug - Responsible(User)Id isn't set correctly during appointment ticket creation

### ISSUE THREAD

**Issue by MarcPahnke** [znuny/Znuny#324]
### Environment

- OS:           Linux
- Browser:      Firefox
- Znuny version: 6.4.4

### Expected behaviour

If you create an appointment ticket during appointment creation, and if the responsible user option is set in SysConfig, and you choose 
an responsible user different from admin with user id 1 - this user is set and assigned as repsonsible user in the created ticket.

### Actual behaviour

But this responsible user is and will never be assigned in the created ticket.

### How to reproduce

0. Make sure the **otrs.Daemon** is running.
1. Enable the Responsible option for tickets (Navigate to Core->Ticket then enable SysConfig Key: Ticket::Responsible )
2. Create a Test-Agent Account. Create a TestCustomerUser and a Test CustomerCompany.
3. In the Main-Menu goto Calendar->Manage Calendar and create a new valid calender in the Calender Manage Mask.
4. In the Main-Menu goto Calendar->New Appointent (AgentAppointmentCalendarOverview;Subaction=AppointmentCreate)
5. Enter some valid test Appointment-Data such as Title and From/To Dates, then choose the calendar from above; Then select "relative period' in the "Ticket creation" section/selection; the Dialog expands by the Ticket Creation input and selection form elements, enter 1 minute before appoinment starts, then choose a queue, an agent and the responsible User from above, choose the customer user from above and finally click on [Save].
7. Check if in the HoverDialog of the created Appointment that Apointment Ticket Cration is visible and  the ticket creation time is valid in the very near future. See Screenshot 1
8. Wait till the ticket creation should be done. Open the Ticket in the Ticket Menu via QueueView and choose the queue from above and then the created ticket.
9. You will see that the responsible User is always AdminUser 

### Additional information

The root cause of this Bug is in the TicketCreate - Method in the Calendar Appointment Plugin , which itself calls TicketObject->TicketCreate() with the wrong Param HashKey Name _ResponsibleUserID_ instead of the correct _ResponsibleID_ - see TicketObject->TicketCreate() - documentation.
- different 

### Screenshots
1)
![grafik](https://user-images.githubusercontent.com/89537707/208499298-39831dd4-7afa-4f8d-84fc-a21a93ee4db4.png)

**Comment by NiklasSchmitt** [comment]
related pull request merged.
