### ISSUE TITLE
Bug - Translation in AgentTicketMove partially working

### ISSUE THREAD

**Issue by lukaskress** [znuny/Znuny#328]
### Environment

- OS:           Ubuntu 22.04 LTS
- Browser:      Chrome/Firefox
- Znuny version: 6.4.2
- Language Setting: German

### Expected behaviour

Button "Move" should be translated.

### Actual behaviour

Button doesn't get translated.

### How to reproduce

Open the page AgentTicketMove with a User that has set German as language.

### Additional information

I checked the translation file and the template file but couldn't find the issue. 
[AgentTicketMove](https://github.com/znuny/Znuny/blob/dev/Kernel/Output/HTML/Templates/Standard/AgentTicketMove.tt#L245-L246)
[Translation](https://github.com/znuny/Znuny/blob/dev/Kernel/Language/de.pm#L2818-L2821)

I also checked another language (french) und the translation worked. So I assume that the translation-function for this button is working, but not for german translation.

### Screenshots
![image](https://user-images.githubusercontent.com/38035605/209295124-24005887-d594-4b14-aae6-e2855892c03c.png)

**Comment by rkaldung** [comment]
Hi @lukaskress,

I was not able to reproduce it with a fresh 6.4.2 or 6.4.5. 
Is there a custom template file or theme?

**Comment by eyazi** [comment]
If I'd have to guess, I'd say that you have some packages from OPAR installed, which have broken translations.

**Comment by lukaskress** [comment]
Hi @rkaldung @eyazi,

good guess, there is ArticleCopyMoveDelete (https://opar.perl-services.de/dist/ArticleCopyMoveDelete-6.0.6) installed, which is also missing some translation. I didn't see that the package comes with an own translationfile which is incomplete. I added the missing translation and it works now. 

So there is no issue with Znuny.
