### ISSUE TITLE
Bug - code policy fails in 6.0

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#336]
After https://github.com/znuny/Znuny/commit/29c22cccd32d012b36a8fd7f5180f0910f54dcd0 code policy fails:

https://github.com/znuny/Znuny/actions/runs/3741160315/jobs/6350407450

**Comment by NiklasSchmitt** [comment]
Hi @pboguslawski,

thank you for letting us know about that. I've fixed `rel-6_0` & `rel-6_0-dev` branch and it's fixed now:
https://github.com/znuny/Znuny/actions/runs/4053357354/jobs/6973880639
https://github.com/znuny/Znuny/actions/runs/4053344860/jobs/6973851808

Best regards,
Niklas :rocket:
