### ISSUE TITLE
Warning is shown with no need. - Proposal for fix

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#34]
### Environment

- OS:           Any
- Browser:      Any
- Znuny version: 6.0.33

### Expected behaviour

A user should not get a warning when answering a ticket, if there is no reason to show a warning. 

### Actual behaviour

A warning is shown to the user after (this)[https://bugs.otrs.org/show_bug.cgi?id=14659] has been implemented

![image](https://user-images.githubusercontent.com/804939/112288660-dcf12280-8c8d-11eb-90ec-da810156aa0a.png)

This is annoying and confusing for the Agents which are used to see warnings only when there is a reason for that. Not just as a note. 

I propose to delete this block in AgentTicketCompose:
https://github.com/znuny/Znuny/blob/rel-6_0/Kernel/Modules/AgentTicketCompose.pm#L1305

and just leave the "load template" and "error" case.

### How to reproduce
1) Create/ open a Ticket
2) Open AgentTicketCompose to reply

**Comment by reneeb** [comment]
Should the user get a warning when the subject is empty (or just the ticket hook)? This could be done with a few lines of javascript, I guess.

**Comment by hanneshal** [comment]
I personally don't think that we need the warning at all in ATCompose in this case. I accept that it might be the case when loading a template / draft, but If you just reply I dont see a need. 

A JS solution would be a nice way to even catch the cases where someone sent a mail without a subject.

**Comment by hanneshal** [comment]
@reneeb What do you think. Simply remove it for this case (ATCompose) or go for the JS way?

**Comment by reneeb** [comment]
I'll provide a PR early next week with a JS solution.
