### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by albert-github** [znuny/Znuny#344]
https://github.com/znuny/Znuny/blob/1b9b1566e4f22060aa940ebff5b3776f55a450bb/CONTRIBUTING.md?plain=1#L18-L29

The used references should all be in lowercase

https://github.com/znuny/Znuny/blob/1b9b1566e4f22060aa940ebff5b3776f55a450bb/CONTRIBUTING.md?plain=1#L48

Link points into nowhere

**Comment by rkaldung** [comment]
Fixed with 7dfbaa1f15f7959b972c2fc95763211686e0a789 since version Znuny 7.0.5
