### ISSUE TITLE
Znuny LTS 6.5.1- quick shot?

### ISSUE THREAD

**Issue by kolbma** [znuny/Znuny#345]
What's up with the [Znuny LTS 6.5.1](https://www.znuny.org/de/releases/znuny-lts-6-5-1)?

There is no release article in blog and there is no update information in manual, where the link from
https://github.com/znuny/Znuny/blob/dev/UPDATING.md points to.

**Comment by hanneshal** [comment]
Hi, 
we had a last minute change in the doc. It will be available shortly.

The news entry can be found here:
https://www.znuny.org/de/news/the-release-of-the-new-znuny-lts

Regards
