### ISSUE TITLE
Bug - regression - unnecessary log message

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#348]
### Environment

- OS:           any
- Browser:     any
- Znuny version: 6.5.1

### Expected behaviour

A check of a system address (SystemAddressLookup) should not trigger an error message.

### Actual behaviour

If SystemAddressLookup() is called with a "non" system address a log message is written.

### How to reproduce

Steps to reproduce the behaviour:

1. Create a autoresponder for a given queue "A"
2. Create a mail where the sender is a system address and route it to queue "A"
3. Log message is created

### Additional information

This is a regression introduced in a fix, when creating a ticket via GenericInterface, triggers an auto response to a system address.

**Comment by NiklasSchmitt** [comment]
Internal issue id: 495

fixed for Znuny LTS with commit https://github.com/znuny/Znuny/commit/1275d2b8f8e9ec1775fa801b03505febde07f587
