### ISSUE TITLE
Bug - Click on "Forward" jumps to first ticket article

### ISSUE THREAD

**Issue by paulfolkers** [znuny/Znuny#351]
### Environment

- OS:           MacOS Ventura 13.2, Microsoft Windows 10/11
- Browser:      Opera, Firefox, Chrome, etc.
- Znuny version: 6.5.1 and earlier

### Expected behaviour

When using templates of type "Forward" clicking on "Forward" article action (click the "Forward" label directly) I expect it to open the template selection to forward this article. This should work both ways, clicking directly into the template selection field and also when clicking on the forward label of the article action.

### Actual behaviour

I am assuming we have multiple e-mail articles in a ticket and I want to forward a newer article but not the first one. Clicking into the forward template selection field works well. If I click on the label "Forward" next to the selection field, it jumps to the first article of that ticket and opens the forward template selection field for it.

Instead it should open the selection field for the current article that I am viewing and that I want to forward.

### How to reproduce

1. Create a template of type "forward" and assign it to any queue.
3. Open any ticket of the assigned queue that has more than one email article.
4. Use the "all articles" view, not the single article view.
5. See the newest email article.
6. Click on the label(!) "Forward" in article actions - do not click into template selection directly.
7. It jumps to the first email article and opens the forward template selection for it.

### Additional information

This works as expected for article reply, by clicking on the "Reply" label the template selection opens up for this article.

### Screenshots
<img width="1498" alt="Xnip2023-03-30_09-22-37" src="https://user-images.githubusercontent.com/83212096/228760405-a1d8625f-d4df-4918-860f-d7e652983374.png">
<img width="1489" alt="Xnip2023-03-30_09-23-23" src="https://user-images.githubusercontent.com/83212096/228760426-b78d6f67-368b-4811-9740-8beb1935bfcc.png">

**Comment by hanneshal** [comment]
Requirement:
- Article Display: show articles
- Forward templates need to be assigned

**Comment by dennykorsukewitz** [comment]
internal Issue: 580

**Comment by NiklasSchmitt** [comment]
Hi @paulfolkers, thank you for your report.

I've fixed it with commit https://github.com/znuny/Znuny/commit/106301987413c47268062bd32f37c79187105029 and it will be part of the next Znuny LTS release. 

Best,
Niklas :rocket:
