### ISSUE TITLE
Bug - Dialog Option 'Customer User' should have no breadcrumb and should not show actions.

### ISSUE THREAD

**Issue by tipue-dev** [znuny/Znuny#352]
### Environment

- OS:           N/R
- Browser:      N/R
- Znuny version: 7.0.1 (and 6.x.x)

### Expected behaviour
Clicking on 'Customer user' under options when creating a ticket should create a dialog that only has functions meant to be shown in a dialog box.
The Size of the content should also follow the size of the dialog.

### Actual behaviour
Several links inside the dialog return the full page into the dialog.
Changing the size of the dialog doesn't change the size of Its content.
While trying to change the size, if the mouse button is released further than the dialog can be extended to, the dialog will close. This can be seen in the video when i resize the dialog the first time.

### How to reproduce

1. Go to 'AgentTicketPhone'
2. Click on 'Customer user' in the options under the subject
3. Click in the dialog on: 
- Any Breadcrumb
- One of the 'Related actions'
- 'Add Customer User' and then on 'Back to search results'

### Additional information
At least the problem with the breadcrumb exists also in OTRS 6.x.x.
The "Nav: None" parameter is used to only return the content, but is not used in all impacted links.
"Related actions" should probably not be shown in that case at all.

Using an existing page, which main use is its own full size page, in a dialog seems to be difficult to maintain, maybe a different solution should be considered here for the future.

### Video
https://user-images.githubusercontent.com/80031303/228835706-661b8a31-a6f2-4d1b-8dd0-6f5ebb7485f3.mp4

**Comment by dignin** [comment]
I've created an internal issue for you on this one. This was actually always the case, but with the new related articles and breadcrumb style, it's become more apparent. We are working on it.

**Comment by dennykorsukewitz** [comment]
internal Issue: 581

**Comment by dignin** [comment]
@tipue-dev , this issue existed in the other versions as well, it's just more prominent now. We are working on a resolution, to prevent users from accidentally navigating away.

**Comment by dennykorsukewitz** [comment]
Fixed with d8a39e8cab09e8acbf14ed51ab8d6608c68a191e
