### ISSUE TITLE
Bug - CSS - customer user address book content doesn't fit dialog

### ISSUE THREAD

**Issue by tipue-dev** [znuny/Znuny#353]
### Environment

- OS:           N/R
- Browser:      Chrome
- Znuny version: 7.0.1

### Expected behaviour
Customer user address book content should fit dialog

### Actual behaviour
Customer user address book content doesn't fit dialog

### How to reproduce

1. Go to 'AgentTicketZoom'
2. Open 'AgentTicketEmailOutbound'
3. Click on the address book icon for any recipient

### Video

https://user-images.githubusercontent.com/80031303/228850840-6e3677e7-4a89-456b-8da1-c38fe22ef679.mp4

**Comment by dennykorsukewitz** [comment]
internal Issue: 576

**Comment by dignin** [comment]
Resolved in 808969ad08ee29408f0ad2514687c3bcd98f90ac
