### ISSUE TITLE
Bug - AgentPreferences CSS - Pointy edges

### ISSUE THREAD

**Issue by JannisKleinrensing** [znuny/Znuny#354]
### Environment

- OS:           Ubuntu
- Browser:      FireFox and Chrome
- Znuny version: 7.0.1

### Expected behaviour

The upper edges of the boxes of the settings in all AgentPreferences groups should be rounded.

### Actual behaviour

The upper edges of the boxes of the settings in all AgentPreferences groups are pointy.

### How to reproduce

1. Go to "AgentPreferences"
2. Click on any group, like "Miscellaneous"
3. See error

### Screenshots

![grafik](https://user-images.githubusercontent.com/71767611/228855914-9ff99b5a-e708-4404-aed7-3630f8f0ddc8.png)

**Comment by dennykorsukewitz** [comment]
internal Issue: 575

**Comment by dignin** [comment]
Resolved by Commit: 808969ad08ee29408f0ad2514687c3bcd98f90ac
