### ISSUE TITLE
Bug - Empty menu dropdown in the customer interface

### ISSUE THREAD

**Issue by tipue-dev** [znuny/Znuny#355]
### Environment

- OS:           Linux
- Browser:      Chrome
- Znuny version: 7.0.2

### Expected behaviour
Menu in the customer frontend doesn't have a dropdown

### Actual behaviour
There is a residual, empty dropdown in the interface on every entry

### How to reproduce

1. Go to the customer frontend and log in
2. Mouse over 'Create Ticket'

### Screenshots
![image](https://user-images.githubusercontent.com/80031303/228986305-3f4148d6-f157-466f-b9a2-b49e47a07043.png)

**Comment by dennykorsukewitz** [comment]
internal Issue: 574

**Comment by dignin** [comment]
Hi, was this an update or a fresh install?

**Comment by tipue-dev** [comment]
> Hi, was this an update or a fresh install?

Hi Shawn, that was a fresh install (on a system with multiple frameworks, not new system)

![image](https://user-images.githubusercontent.com/80031303/231186800-bdc18f59-5166-4e7d-af9a-3df8ff36add8.png)

**Comment by tipue-dev** [comment]
I just made a new installation on a new server and i can see this there also

**Comment by dignin** [comment]
Fixed in the upcoming release 7.0.4
