### ISSUE TITLE
Znuny 7 shows the default logos instead of custom ones

### ISSUE THREAD

**Issue by cristalink** [znuny/Znuny#357]
### Environment

- Znuny version: 7.0.2

### Expected behaviour

AgentLogo and CustomerLogo should be shown if configured.

### Actual behaviour

Znuny's default logo is shown.

### Cause

The problem is that the default logo CSS has "!important" whereas the custom logo style does not:

![image](https://user-images.githubusercontent.com/27765666/229271554-519980ef-b3ec-4b77-b551-1b87fd3eac37.png)

### Hotfix

I fixed the issue by adding "!important" to the following files:

/opt/otrs/Kernel/Output/HTML/Templates/Standard/CustomerHTMLHead.tt
/opt/otrs/Kernel/Output/HTML/Templates/Standard/HTMLHead.tt
/opt/otrs/Kernel/Output/HTML/Templates/Standard/Login.tt

![image](https://user-images.githubusercontent.com/27765666/229271660-f4b9617a-544a-4228-9394-78f4bb2cdf0b.png)

Thanks!

**Comment by dignin** [comment]
Thanks for the report. We opened an internal issue 594.

**Comment by KaiHerlemann** [comment]
Fixed with https://github.com/znuny/Znuny/commit/38b60f59b7df7bb81ccf2c28426e574fe8608394, will be fixed in the next version of Znuny 7.
