### ISSUE TITLE
Bug - Message subject prefill on Activity dialog only works for Agent

### ISSUE THREAD

**Issue by lis975** [znuny/Znuny#363]
### Environment

- OS:  Linux         
- Browser:   Safari,Chrome   
- Znuny version: 6.5.1 

### Expected behaviour

On ActivityDialog there is a Message field, that has pre-filled subject. I want it to fill on both Agent and Client side when using this Dialog.

### Actual behaviour

subject is only filled on Agent side, when using dialog

### How to reproduce

1. Create ActivityDialog and make it available on both: client and agent sides.
2. place Message field on it
3. set properties to message field: Subject, Communication channel, is visible for customer, Template, autofill

Save the whole "process" and run Dialog on Agent and Customer side.  On Customer side, subject will not be set.

### Screenshots
<img width="851" alt="message filed definition" src="https://user-images.githubusercontent.com/118340942/229484459-92c47297-3c24-45bc-8856-d47355911b0f.png">
<img width="932" alt="client side" src="https://user-images.githubusercontent.com/118340942/229484467-76760756-3227-48fc-b166-e0e3789effdd.png">
<img width="942" alt="agent side" src="https://user-images.githubusercontent.com/118340942/229484472-8a1a7612-710d-4228-bf49-60187cd2d3ab.png">

**Comment by lis975** [comment]
Znuny ver is 6.5.2, my mistake

**Comment by dignin** [comment]
I could verify the issue and have created an internal issue 593.

**Comment by dennykorsukewitz** [comment]
Fixed in:

Znuny 6.5.4 - bb701da34cd0313c1877796a1f3f0196220a6898
Znuny 7.0.10 - b04b877714b3177abfe352702acd7ad9c03e6e7d
