### ISSUE TITLE
Znuny 7: Reports filter for Agents is unusable

### ISSUE THREAD

**Issue by lis975** [znuny/Znuny#364]
### Environment

- OS:  Linux Rocky         
- Browser:   Chrome, Safari   
- Znuny version: 7.0.1  

### Expected behaviour

I want to select agents from list

### Actual behaviour

the agents list is only one line high. It is just impossible to use it.

### How to reproduce

1. Go to reports
2. Click on edit any report
3. Click "Filter"
4. add Agent/Owner or Created by Agent filter

### Additional information

the dialog window for filters is just too narrow

### Screenshots

<img width="475" alt="Zrzut ekranu 2023-04-5 o 14 53 45" src="https://user-images.githubusercontent.com/118340942/230088284-e5714254-5972-4504-9a85-9a4054034ffa.png">
<img width="504" alt="Zrzut ekranu 2023-04-5 o 14 47 31" src="https://user-images.githubusercontent.com/118340942/230088292-9dbd6af2-1640-45d9-8475-a9805399c062.png">

**Comment by dignin** [comment]
Issue is not visible in the current build. Please reopen if you continue to have issues.
