### ISSUE TITLE
Znuny 7: Desktop widget ignores "Owned tickets" filter 

### ISSUE THREAD

**Issue by lis975** [znuny/Znuny#365]
### Environment

- OS:     macOS     
- Browser:   Chrome, Safari   
- Znuny version: 7.0.1 

### Expected behaviour

when selecting filter it should be displayed as currently selected

### Actual behaviour

on every widget on desktop, when selecting "Owned Tickets" filter there is "()" display instead of its name

### How to reproduce

1. Go to desktop
2. Click on filter dropdown list
3. Scroll down to Owned tickets and select it
4. () will be displayed

### Additional information

although () are displayed, the filter is applied!

### Screenshots

<img width="262" alt="Zrzut ekranu 2023-04-5 o 14 50 59" src="https://user-images.githubusercontent.com/118340942/230090831-f29b6c0f-cba9-4d01-8395-d59e23434fee.png">
<img width="1308" alt="Zrzut ekranu 2023-04-5 o 14 50 45" src="https://user-images.githubusercontent.com/118340942/230090839-154f7f99-d1c2-44ee-9561-b92a7c8f422f.png">

**Comment by dignin** [comment]
Thanks for the report, we've created an internal ISSUE 592.

**Comment by NiklasSchmitt** [comment]
Hi @lis975,

thank you very much for your report.
I've fixed the issue with commit https://github.com/znuny/Znuny/commit/55c7137e15cefe9846e585f1a37963178cbf9621 and it will be released within the next Znuny version 7.0.3.

Best, 
Niklas :rocket:
