### ISSUE TITLE
question SENDER column in queue view

### ISSUE THREAD

**Issue by gerald2545** [znuny/Znuny#373]
Hi,
we changed the displayed data in SENDER column of queue view because we thought it is not relevant...but maybe we are wrong.

My colleagues prefer to have the author (sender) of the last article written in the ticket : it helps them to see if some tickets need interest....and as the customer information is displayeds in "Customer User ID" colmun, it is redundant for us....

Is it a bug or a misunderstanding from our part?
 

To display the last contributor on a ticket, we changed Kernel/Output/HTML/TicketOverview/Small.pm by commenting SenderType => 'customer',

```
 my @Articles = $ArticleObject->ArticleList(
                TicketID   => $TicketID,
                #GS commented on 2023-04-20
                #SenderType => 'customer',
                OnlyLast   => 1,
            );
```

thanks for the discussion

**Comment by hanneshal** [comment]
Hi again, 

I have to say, I do not understand this change.

All you have changed is:
`Get me the last customer article` 
to 
`
Get me a list of all articles and give me the last entry.
`

This maybe something special to your use case but why would it matter who wrote the last article?
IMHO it would only matter if you do not set proper states (pending-customer, waiting for....) and so on. 

If you do not reset the owners, the last owner is always the last agent who wrote the article / made a change.

I would suggest, as this is not a bug, we move this to the forum or to discord. We do not handle discussions here , just issues.

If you really need exactly this info, there should be a better way to deal with this. 


@rkaldung Maybe you have an idea for this.
