### ISSUE TITLE
Did the value for $Method get mixed up in Auth::DB?

### ISSUE THREAD

**Issue by kjarex** [znuny/Znuny#379]
I assume `$Method` should be set to `'sha512'` in this line: https://github.com/znuny/Znuny/blob/9cadca40a1472d3e55544bedfa40b6866da3b9e1/Kernel/System/Auth/DB.pm#L170

**Comment by rkaldung** [comment]
@kjarex You're right, this looks odd. Maybe it's a ten year old, undetected bug. We'll dig into it

**Comment by eyazi** [comment]
At first glance, this only looks like a typo for the debugging.

https://github.com/znuny/Znuny/blob/9cadca40a1472d3e55544bedfa40b6866da3b9e1/Kernel/System/Auth/DB.pm#L166

sha512 is still getting used for hashing.

**Comment by NiklasSchmitt** [comment]
internal issue 827

**Comment by NiklasSchmitt** [comment]
Fixed with commits https://github.com/znuny/Znuny/commit/6b0d53ebfdd8df37ee69752b0a3bc9a598261e0c & https://github.com/znuny/Znuny/commit/fb33cbb32ea62588fbfc7b02f823800f53d5c25c.
