### ISSUE TITLE
Bug - Adding new appointment in calendar not possible.

### ISSUE THREAD

**Issue by dignin** [znuny/Znuny#381]
### Environment

- OS:             n.a.
- Browser:     n.a.
- Znuny version: 7.0.2

### Expected behaviour

It should be possible to enter a new appointment in the calendar.

### Actual behaviour

After saving the appointment data, the screen stops loading.

### How to reproduce

1. Go to Calendar => New Appointment
2. Add Title, Description and select calendar
3. Click save.

### Screenshots

![image](https://user-images.githubusercontent.com/891283/233967843-95dba127-4fc5-4539-92a7-a93d4fbd8191.png)

**Comment by NiklasSchmitt** [comment]
Fixed with commit https://github.com/znuny/Znuny/commit/fc37f74dcd6411f7c3b6020dd0a94a292352be43 and will be released within the next Znuny 7 version.
