### ISSUE TITLE
Bug - Selected file on ProcessManagementAttachment doesn't attach to article in transition action

### ISSUE THREAD

**Issue by lis975** [znuny/Znuny#385]
### Environment

- OS:     Linux      
- Browser:   Chromium, Safari   
- Znuny version:  6.5.1, 6.5.2 

### Expected behaviour

a files selected on Attachments field, on process dialog should be added to article or new ticket, depending on transition action, when "Attachments" setting is set to 1 on transition action.

### Actual behaviour

insted of adding attachment to article, transition action logs error:

Found no StdAttachment found for 1!

### How to reproduce

1. create proces with two dialogs and three activities
2. on first activity add message component (to add attachment to ticket)
3. on second activity define new dialog, and add Attachments component to it
4. in transition action to third activity call ArticleCreate or TicketCreate, setting Attachment setting to 1

### Additional information

This functionality last worked in version 6.4.5

### Screenshots

[Export_ProcessEntityID_Process-72f4e7bf1c0359175f7fb6037324b765.yml.zip](https://github.com/znuny/Znuny/files/11309781/Export_ProcessEntityID_Process-72f4e7bf1c0359175f7fb6037324b765.yml.zip)
![Zrzut ekranu z 2023-04-24 13-06-50](https://user-images.githubusercontent.com/118340942/233980181-bca26831-24ce-4264-91af-c5c656c7da9f.png)
![Zrzut ekranu z 2023-04-24 13-09-51](https://user-images.githubusercontent.com/118340942/233980241-4ae18d34-7685-4426-994e-6a05994e64ef.png)

**Comment by dignin** [comment]
There is an issue in the modules perl documentation.

Please use the following. I've created an internal issue  606 to fix the documentation.

```

  'Attachments' => 'Orderform.pdf,Acceptrules.pdf', #File names of standard attachments
  'AttachmentIDs' => '23,26', #ids of standard attachments
  'AttachmentsReused' => 'true' #use attachments selected in actiivty dialog

```

**Comment by lis975** [comment]
Thank you very much for this explanation. I think, that placeholders in Transition Actions need to be corrected as well as documentation. 
By the way, the correct parameter is AttachmentsReuse - without "d" ending. I've checked it in module source.
