### ISSUE TITLE
Bug - Sisimai to slow to handle big email

### ISSUE THREAD

**Issue by gody01** [znuny/Znuny#391]
### Environment

- OS:                       Linux CentOS 7.x
- Browser:              Chrome, Firefox, ...
- Znuny version:                                  6.0.34 and above (since Sisimai update)

### Expected behaviour

After pop3 Mail Fetch, mail should be deleted from server.

### Actual behaviour

When fetching large Email (15Mb+) after successful fetch, EmailBounce testing is taking so much time, that pop session is terminated (Server: Zimbra). Next pop command 'delete' is then unsuccessful.

Unfortunately, on Znuny side, bounce processing is eventually ended and converted to Ticket, but on mail server mail is still present in inbox. So the same ticket is created over and over again.

### How to reproduce
You need big Email, CentOS 7.x (on that, Bounce Checking is taking over 4minutes). 

1. Go to '...'   console
2. Click on '...'   enter: ./otrs.Console.pl   Maint::PostMaster::MailAccountFetch  --debug and 
3. Scroll down to '...' observer time  to fetch mail
4. See error  on server, if mail is big enough mail will still be present.  On faster infrastructure (and with CentOS 8 for example) only significant time delay before DELE command can be observed.

### Additional information

Slow EmailBounce processing is already confirmed by author of Sisimail:
https://github.com/sisimai/p5-sisimai/issues/492

**Comment by gody01** [comment]
For quick & dirty solution attached patch can be applied in 
Kernel/cpan-lib/Sisimai

[Message.pm.diff.gz](https://github.com/znuny/Znuny/files/11314036/Message.pm.diff.gz)

It will shorten mail messagebody to 32766 bytes and processing will be again under 1 second.


Author of Sisimail has estimated that he will fix Sisimai in about 2 weeks. However if someone has similar problem on production attached fix prevents this problem.

**Comment by hanneshal** [comment]
Hi @gody01,

thanks for the report and getting in touch already with the maintainers of the lib and providing a hotfix!

I have a look at this in some days


Thank You!

**Comment by gody01** [comment]
Hello, 

Author of Sisimai fixed the issue in v4.25.16 (https://metacpan.org/dist/Sisimai)
I tested fix and it is few orders of magnitude faster on my systems.

Is there any chance, to update cpan-lib with new version for 6.0.x and 6.5.x ?

**Comment by hanneshal** [comment]
Hi @gody01 
thanks for the feedback. We will test it and put it on the list for 6.5 and 7. 

6.0 is out of support and wont receive any updates. 

Regards and thank you!
Johannes

Edit:
Internal issue 627

**Comment by rkaldung** [comment]
Updated bundled Sisimai with Znuny LTS 6.5.3 and Znuny 7.0.6
