### ISSUE TITLE
Bug - "Reply All" doesn't apply CC/BCC recipients into new ticket form

### ISSUE THREAD

**Issue by frdmn** [znuny/Znuny#410]
### Environment

- OS: Ubuntu 20.04.6 LTS
- Browser: Brave latest
- Znuny version: 7.0.3

### Expected behaviour

When using the "Reply All" button to reply to all (regular/CC/BCC) recipients, all contacts (incl. CC and BCC) should be copied over to the reply form. 

### Actual behaviour

CC and BCC recipients are not copied over to the reply form. Might be related to the new UI?

### How to reproduce

1. Open an existing ticket / article that has CC/BCC recipients
2. Click "Reply all" within the article menu
3. Notice how the CC/BCC recipients are not applied in the form

##### Sender/recipient information that has CC/BCC contacts:

<img width="978" alt="Bildschirm­foto 2023-04-27 um 12 53 03" src="https://user-images.githubusercontent.com/944459/234842988-6a073eee-fb4c-4554-b79f-896152260f37.png">

##### Form that doesn't apply CC/BCC contacts:

<img width="821" alt="Bildschirm­foto 2023-04-27 um 12 55 49" src="https://user-images.githubusercontent.com/944459/234843111-88f482b2-26a2-495f-a64b-a02092a8f7f3.png">

**Comment by dignin** [comment]
Hi, BCC should never be visible in an incoming message, I guess. I have created an internal issue 605. As the CC is not being included, and at least this should be.

**Comment by frdmn** [comment]
Ah, right. The BCC one should only be copied over when it's an outgoing article of course.

**Comment by NiklasSchmitt** [comment]
Hi @frdmn,

thanks a lot for your report. I've fixed the issue with this commit https://github.com/znuny/Znuny/commit/6d55b56af58403d392d8fe55b323e3248322cebc and it will be part of the next Znuny version 7.0.5.

Best,
Niklas :rocket:
