### ISSUE TITLE
Bug - Znuny 7: Calendar items in Overview only orange and not in selected color

### ISSUE THREAD

**Issue by ghostbiker** [znuny/Znuny#411]
### Environment

- OS:           Ubuntu 20.04 LTS
- Browser:      Safari
- Znuny version: 7.0.3

### Expected behaviour

All Calendar Items in calendar overview displayed in selected color (red, green, ..)

### Actual behaviour

All Calendar Items in calendar overview only displaed in orange

### How to reproduce

1. Create a new calendar and select color i.E. Yellow
2. Create a date 
3. Color of date is orange

### Screenshots

<img width="1576" alt="2023-04-27_13-26-40" src="https://user-images.githubusercontent.com/15995107/234848659-82a26228-0bdf-4638-82dd-3a543aab2d55.png">

**Comment by dignin** [comment]
Internal issue 604

**Comment by NiklasSchmitt** [comment]
Hi @ghostbiker, thank you very much for your report. 

I've fixed it in commit https://github.com/znuny/Znuny/commit/80fcdf3814ca0fdef3c1e0b5d794b4a71dcebc9d what will be part of the next Znuny version 7.0.5.

Best regards,
Niklas :robot:
