### ISSUE TITLE
Bug - Znuny 7 Answer Ticket - Default Button not used when pressing enter key

### ISSUE THREAD

**Issue by ghostbiker** [znuny/Znuny#412]
### Environment

- OS:          macOS Ventura
- Browser:      Safari
- Znuny version: 7.0.3

### Expected behaviour

When answer a ticket, return/enter key on keyboard should use default button "Send Email".

### Actual behaviour

When answer a ticket, return/enter key on keyboard invoke "save as draft" button

### How to reproduce

1. Go to ticket
2. select answer -> empty answer
3. Typoe some text in Subject
4. Press key return/enter on keyboard

### Screenshots

<img width="1297" alt="2023-04-27_14-34-26" src="https://user-images.githubusercontent.com/15995107/234863318-078f422d-55f6-4e18-afc8-5bfe00340880.png">

**Comment by dignin** [comment]
Thanks for your report. Too many times has the enter key sent an ✉️ which was not finished 😫. Try the ACCESS KEY + g in your browser to submit. This should send the message. Arguably, this could be configurable. But currently it's not.

Hope this tip help.
