### ISSUE TITLE
Bug - Double display of email Adresses in Ticket View

### ISSUE THREAD

**Issue by ghostbiker** [znuny/Znuny#415]
### Environment

- OS:          macOS Ventura
- Browser:      Safari
- Znuny version: 7.0.3

### Expected behaviour

Email adress in From, To fields should display as "Test User <test@user.com>"

### Actual behaviour

Email is displayed as "Test User <test@user.com>Test User"

### How to reproduce

1. Open a Ticket
2. Click on an Email
3. Click on "i" to display from, To, ..)

### Screenshots

<img width="979" alt="2023-04-28_08-14-01" src="https://user-images.githubusercontent.com/15995107/235070139-357964d9-aca8-4295-904f-5df693b3566b.png">

**Comment by rkaldung** [comment]
@dignin Same procedure

**Comment by rkaldung** [comment]
This might be related to the feature that just the display name or display name + e-mail is show by clicking on the label.

**Comment by NiklasSchmitt** [comment]
internal issue: 665

**Comment by NiklasSchmitt** [comment]
Fixed with commit https://github.com/znuny/Znuny/commit/4f3baef3323b510ea012d0d6f290f579bc65449e.
Will be part of the next Znuny version 7.0.8
