### ISSUE TITLE
Bug - Znuny 7 - Not possible download attachments with long filenames (in Safari)

### ISSUE THREAD

**Issue by ghostbiker** [znuny/Znuny#416]
### Environment

- OS:           macOS Ventura
- Browser:     Safari
- Znuny version: 7.0.3

### Expected behaviour

In Article View, If you click on the download button of an attachment, attachment should download 

### Actual behaviour

If you click on the download button of an attachment, nothing happens (Info: Firefox Download is working)
Maybe only a bug in Safari

### How to reproduce

1. Go to an article
2. Click on Download button
3. See error

### Additional information

-Workaround is possible via right click an selecting "Save file"
-Bug only with "very" long filenames!

### Screenshots

<img width="853" alt="2023-04-28_09-16-02" src="https://user-images.githubusercontent.com/15995107/235082523-92e8017e-4342-4c9d-a9f6-f1fcc611fc83.png">

**Comment by rkaldung** [comment]
@dignin Confirmed, please pass to dev

**Comment by dignin** [comment]
Internal issue 618

**Comment by NiklasSchmitt** [comment]
This will be fixed within the next Znuny version 7.0.7
