### ISSUE TITLE
Bug - Mentions CSS problems

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#419]
### Environment

- OS:           Linux
- Browser:      Firefox ESR 102.10
- Znuny version: 6.5.2

### Expected behaviour

(1) CSS defined in var/httpd/htdocs/skins/Agent/default/css/Znuny.RichTextEditor.css should be applied to mentions context menu in rich editor only.

(2) No white background on mentions menu item after moving with arrow keys from item hovered with mouse.

### Actual behaviour

Ad (1)
`.Mention` defined in var/httpd/htdocs/skins/Agent/default/css/Znuny.RichTextEditor.css is applied to toolbar Mention icon `<li class="Mention">`. This bug is expecially visible on skins with nonstandard toolbar background colors.

Ad (2)
When mentions menu item is hovered with mouse and then user moves selection to different item using keyboard up/down arrows, items background that lost focus is broken (light background with not readable text).

### How to reproduce

Ad (1)
Generate some mentions for yourself to display mentions icon, open browser dev tools and see styles applied to mentions icon (`<li class="Mention">` element).

Ad (2)
As above.

**Comment by ghostbiker** [comment]
Mayby, same Problem in Znuny 7, After Typing "@someone" popup List shows a List of name, but it is not readable because Wihite Text on White Background. Only the highlighted name ist readable 
<img width="237" alt="2023-05-08_10-34-35" src="https://user-images.githubusercontent.com/15995107/236776679-1bd8a2b6-ed86-4b61-8e62-6c702e63cb83.png">

**Comment by dennykorsukewitz** [comment]
internal MR: 920

**Comment by dennykorsukewitz** [comment]
Fixed in rel-7_0_10. [69007f1738f21a6ea28642fcd4f09ab33e15af11](https://github.com/znuny/Znuny/commit/69007f1738f21a6ea28642fcd4f09ab33e15af11)
