### ISSUE TITLE
Bug - Lack of signature in new notification

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#420]
### Environment

- OS:           any
- Browser:      any
- Znuny version: 6.5.2

### Expected behaviour

All default notification templates should have standarized default signature.

### Actual behaviour

New mention notification (id=16) template [does not have](https://github.com/znuny/Znuny/blob/0253fa07c23226c2f31a6c6f3868fabb0673ef37/scripts/database/initial_insert.xml#L3992) `-- <OTRS_CONFIG_NotificationSenderName>` signature [present in other templates](https://github.com/znuny/Znuny/blob/0253fa07c23226c2f31a6c6f3868fabb0673ef37/scripts/database/initial_insert.xml#L3898).

**Comment by dignin** [comment]
Internal Issue 619

**Comment by dignin** [comment]
Fixed in 6_5_4 by 34a8b2a7dac7c433942b5f8ccb96792165575a04
