### ISSUE TITLE
Bug - AdminNotificationEvent: NotificationNewTicket sent twice since upgrading to 6.5.2 LTS

### ISSUE THREAD

**Issue by tgurr** [znuny/Znuny#422]
### Environment

- OS: Linux
- Browser: Chrome
- Znuny version: 6.5.2 LTS

### Expected behaviour

E-Mail only sent once and only one article being created.

### Actual behaviour

E-Mail sent twice and two articles being created.

### How to reproduce

1. Configure an AdminNotificationEvent: NotificationNewTicket
2. Content 
[Export_Notification_10_4_Benachrichtigung__ber_neues_Ticket_-_Kunde.yml.txt](https://github.com/znuny/Znuny/files/11430297/Export_Notification_10_4_Benachrichtigung__ber_neues_Ticket_-_Kunde.yml.txt)
3. See two articles being created and also two mails being sent on the respective ticket as soon as a customer creates one:

![ticketnotification](https://github.com/znuny/Znuny/assets/414984/4571c6b0-c347-42d5-af7f-383631b9ffd4)

### Additional information
This is on a test migration from 6.0.48 to 6.5.2 where it previously worked on 6.0.48 without this issue.

### Screenshots
See above.

**Comment by hanneshal** [comment]
Hi @tgurr 
1) can you please also post the history of the ticket. 
2) Can you please the sysconfig if there is more then one entry like:
<img width="1117" alt="image" src="https://github.com/znuny/Znuny/assets/804939/b3ba1bae-92dd-4997-acff-6dfb627c5923">

Search in the Sysconfig for `-NotificationEvent` in some cases there is more then one active.

<img width="557" alt="image" src="https://github.com/znuny/Znuny/assets/804939/2f4764ea-1501-4e01-90b3-66ccbe8e2ac6">

Regards

**Comment by hanneshal** [comment]
Hi @tgurr 
1) can you please also post the history of the ticket. 
2) Can you please the sysconfig if there is more then one entry like:
<img width="1117" alt="image" src="https://github.com/znuny/Znuny/assets/804939/b3ba1bae-92dd-4997-acff-6dfb627c5923">

Search in the Sysconfig for `-NotificationEvent` in some cases there is more then one active.

<img width="557" alt="image" src="https://github.com/znuny/Znuny/assets/804939/2f4764ea-1501-4e01-90b3-66ccbe8e2ac6">

Regards

**Comment by tgurr** [comment]
@hanneshal thanks, attaching the requested information below.

> 1. can you please also post the history of the ticket.

![tickethistory](https://github.com/znuny/Znuny/assets/414984/78472356-20c1-401c-ae6b-64383e841e8d)

> Can you please the sysconfig if there is more then one entry like:

The search for `-NotificationEvent` lists only one result:

![sysconfig](https://github.com/znuny/Znuny/assets/414984/0dc0d360-654c-4ef9-9378-b6c72273fcdf)

**Comment by hanneshal** [comment]
Thanks, I assume that the 4 Ticket Create notifications and the customer notification are sent twice, correct?
Queue update is only sent once?

**Comment by tgurr** [comment]
> Thanks, I assume that the 4 Ticket Create notifications and the customer notification are sent twice, correct? Queue update is only sent once?

Indeed, I didn't have configured the agent notifications in my personal agent profile, but after doing so I also recieve two mails. So duplicated are ticket create notification for the agent and the customer notification, while the queue update notification is only sent once:

![outlook](https://github.com/znuny/Znuny/assets/414984/978d5c4b-4fa9-4bf4-8f9d-016a0239eba3)

**Comment by dignin** [comment]
@tgurr, I would like to offer to support you in a community support issue. I feel it will be more comfortable. Please send as an email to info 'at' znuny 'dot' com referencing this GitHub issue, and we'll reach out to you. Simultaneously, I'll leave this issues open.

**Comment by hanneshal** [comment]
Issue is resolved via remote call.
