### ISSUE TITLE
Bug - Znuny 7 - Download button in Ticketview is not visible in a small browser window

### ISSUE THREAD

**Issue by ghostbiker** [znuny/Znuny#423]
### Environment

- OS:           macOS Ventura
- Browser:      Safari, Firefox
- Znuny version: 7.0.4

### Expected behaviour

Download button of mail attachment should visible if browserwindow has a small view

### Actual behaviour

You have to resize the window, until the download button becomes visible

### How to reproduce

1. Go to ticket with attachment
2. Scroll down to attachments
3. Resize window from large width to small width

### Screenshots

<img width="430" alt="small width" src="https://github.com/znuny/Znuny/assets/15995107/33c34c5c-a2e8-429f-9ce4-8480579927f7">
<img width="500" alt="large width" src="https://github.com/znuny/Znuny/assets/15995107/619ac6a5-2fae-449b-b752-228ceed34075">

**Comment by dignin** [comment]
Internal Issue 616 created.

**Comment by NiklasSchmitt** [comment]
This is fixed since Znuny 7.0.5
