### ISSUE TITLE
Bug - Missing group timeaccounting_webservice created on upgrade to 6.1

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#428]
### Environment

- OS:           linux
- Browser:      any
- Znuny version: 6.1 (on upgrade from 6.0 LTS to 6.5 LTS)

### Expected behaviour

No unnecessary groups created on upgrade. Same upstream groups should exist after upgrade to 6.5 and fresh 6.5 install.

### Actual behaviour

When upgrading from 6.0 to 6.5 one [need to upgrade to 6.1 first](https://doc.znuny.org/znuny_lts/releases/installupdate/update.html). 6.1 upgrade script [creates `timeaccounting_webservice`](https://github.com/znuny/Znuny/blob/a92679404a8f811c72af5bd52cce113246daa93d/scripts/MigrateToZnuny6_1/MigrateGroups.pm#L105) group. Group looks like not required for systems that do not use timeaccounting webservice so only `_MigrateGroupNames` should be called there without `_CreateMissingGroups` probably.

After upgrading 6.0->6.1->6.2->6.3->6.4->6.5 group `timeaccounting_webservice` is present (with empty description). After fresh 6.5 install no such group is present in system.

### How to reproduce

Upgrade from 6.0 to 6.1. Install fresh 6.5.

**Comment by rkaldung** [comment]
@pboguslawski This group is necessary since it's required to permit access to the ticket operation [TimeAccountingGet](https://github.com/znuny/Znuny/blob/8dff3e2ddbb324c786b5c333b3d958592d107f7a/Kernel/GenericInterface/Operation/Ticket/TimeAccountingGet.pm#L120).

To fix this it's required to have this group.

**Comment by pboguslawski** [comment]
> To fix this it's required to have this group.

Forcing to create separate, hard-coded group for one specific and optional (if understood correctly) web operation sounds bad.

If separate privilege is necessary for this op, consider rather introducing sysconfig parameter with group name for it, empty by default; then when admin wants to grant access to this op, should set chosen group (creating it manually if necessary).

**Comment by rkaldung** [comment]
Already fixed for Znuny LTS 6.5 and Znuny 7.0.
