### ISSUE TITLE
Bug - "JavaScriptError: Core.Agent.TicketNoteToLinkedTicket is undefined" in Large ticket lists when "Transfer notice" link is rendered

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#430]
### Environment

- OS:           linux
- Browser:     Firefox ESR 102
- Znuny version: 6.5.2

### Expected behaviour

No JS error in L mode when ticket menu displays "Transfer notice".

### Actual behaviour

Any ticket list in L mode throws JS errors like

```
[ERROR] JavaScriptError: Core.Agent.TicketNoteToLinkedTicket is undefined 
```

```
Uncaught TypeError: Core.Agent.TicketNoteToLinkedTicket is undefined
```
when linked tickets with `Transfer notice` is present in tickets menu.

### How to reproduce

1. In fresh 6.5.2 install create two tickets and put link between it.
2. Open index.pl?Action=AgentTicketQueue in L mode - browser should throw JS error as above.

### Additional information

Problem does not occur after adding `Core.Agent.TicketNoteToLinkedTicket.js` to `JavaScript` list in `Loader::Module::AgentTicketQueue###002-Ticket`.

Same problem in other L views (probably every sysconfig parameter where `Core.Agent.Overview.js` already exists).

**Comment by rkaldung** [comment]
This has been fixed with the release of Znuny LTS 6.5.3 / Znuny 7.0.6. See commit https://github.com/znuny/Znuny/commit/d790e487e258309c0f46945c21ff0bdfe077b6cb
