### ISSUE TITLE
Bug - Message: Need ArticleID! error generated on saving note to linked ticket

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#431]
### Environment

- OS:           linux
- Browser:      any
- Znuny version: 6.5.2

### Expected behaviour

No errors in Znuny error.log on saving note to linked ticket.

### Actual behaviour

When adding new note to linked ticket (AgentTicketNoteToLinkedTicket feature) Znuny throws

```
ERROR: OTRS-CGI-1 Perl: 5.32.1 OS: linux Time: Fri May 12 10:29:16 2023

 Message: Need ArticleID!

 RemoteAddress: [...]
 RequestURI: /myznuny/index.pl

 Traceback (13073):.
   Module: Kernel::System::Ticket::Article::Backend::MIMEBase::ArticleGet Line: 755
   Module: Kernel::System::Ticket::Article::ArticleGet Line: 1281
   Module: Kernel::Modules::AgentTicketNoteToLinkedTicket::Run Line: 126
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 1144
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 39
   Module: (eval) (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 173
   Module: ModPerl::Registry::handler (v1.99) Line: 32
```

### How to reproduce

1. Add note to linked ticket
4. See error in apache error.log

### Additional information

`ArticleGet` should probably not be called when `ArticleID` is empty.

**Comment by dignin** [comment]
Internal ISSUE 626

**Comment by jepf** [comment]
@pboguslawski 

Thank you for reporting this issue.

It has been fixed (https://github.com/znuny/Znuny/commit/8c0e0a5c45187f442edde84e40bd91eedb93d865) and will be part of Znuny 7.0.7 and 6.5.4.
