### ISSUE TITLE
Bug - Time accounting item/input field missing on creating notes since upgrading to 6.5.2 LTS

### ISSUE THREAD

**Issue by tgurr** [znuny/Znuny#435]
### Environment
- OS: Linux
- Browser: Chrome
- Znuny version: 6.5.2

### Expected behaviour
Have the line/input field for time accounting being present when the agent creates a note via "communication -> note", like it still appears fine the other communication items like outgoing/incomming phone and outgoing email.

![Screenshot_20230515_102709](https://github.com/znuny/Znuny/assets/414984/f0bd4493-a9f6-42c7-860e-939053ee004f)

### Actual behaviour
Find the actual time accounting line missing when adding notes:
![Screenshot_20230515_102615](https://github.com/znuny/Znuny/assets/414984/69d98ec7-74f1-4039-b1dc-f71485c0edc6)

### How to reproduce

1. Login as agent
2. Navigate to a ticket
3. Create new note via "communication -> note"
4. Find time accounting line/input field missing

### Additional information
The system has been upgraded from 6.0.48 to 6.5.2 just recently (last Friday). Where it previously worked on 6.0.48 without this issue.

The time accounting line appears to be present on the Znuny 7 Demo system though https://preview.znuny.rocks/ however sadly there's no demo system for the LTS version to be able to compare if it might be a local issue.

### Screenshots
See above.

**Comment by tgurr** [comment]
Update: Probably the same root cause, but the time accounting field is not only missing from notes but now also missing from Action=AgentTicketClose and also when used in an article in an ActivityDialog Article during process where it is shown in the process configuration itself:

![image](https://github.com/znuny/Znuny/assets/414984/a9ef977c-33a2-486e-97b5-89a551c805b3)

It's missing in the actual process for the agent.

**Comment by dignin** [comment]
@tgurr , It appears you may be using old templates, or something. In a fresh installation, everything is there.

![image](https://github.com/znuny/Znuny/assets/891283/ba962ac7-da26-420b-892c-34250219a5af).

Would you please address this issue to the community support. Please ensure to provide error logs to the community for more help.

https://community.znuny.org

Thanks.

**Comment by tgurr** [comment]
> @tgurr , It appears you may be using old templates, or something. In a fresh installation, everything is there.

Thanks for confirmation that things are fine in a fresh installation and also for you hint in regards to templates. 

Interestingly I've found some `.custom_backup` files having recent content from 6.5.2 but the regular files dating back to 2017. After replacing them with their current ones things work fine and the time accounting fields reappeared. I've done it step by step and the last few under `Kernel/Modules/`

```
# find . -name *.custom_backup
./Kernel/Modules/CustomerTicketProcess.pm.custom_backup
./Kernel/Modules/AdminSLA.pm.custom_backup
./Kernel/Modules/AgentTicketEmail.pm.custom_backup
./Kernel/Modules/AgentTicketProcess.pm.custom_backup
./Kernel/Modules/AgentTicketPhone.pm.custom_backup
./Kernel/Modules/AdminService.pm.custom_backup
./Kernel/Modules/AgentTicketActionCommon.pm.custom_backup
```
must have done the trick. Hopefully fixed some other possible hurdles by cleaning **all** such cases where duplicates with either `.custom_backup` or `.save` existed.
