### ISSUE TITLE
Bug - API user cannot login if 2FA is mandatory

### ISSUE THREAD

**Issue by CERT-BA** [znuny/Znuny#437]
### Environment

- OS:           any
- Browser:      any
- Znuny version: 6.5.2

### Expected behaviour

API users should be able to login even if 2FA is mandatory. Either by providing the 2FA token in the API login, intruducing api keys which allows an API user to login with or disabling 2FA for API users.

### Actual behaviour

If 2FA is mandatory API users cannot login anymore - even if the token is provided within the login request.

### How to reproduce

1. Go to Admin - AuthTwoFactorModule::AllowEmptySecret  and deactivate the option
2. Login via SOAP or REST API with an user with an empty 2FA secret

### Additional information

We temporary fixed the problem by patching the file Kernel/GenericInterface/Operation/Common.pm with the attached patch file - after that the API user can provide the TwoFactorToken within the login request.

### Screenshots

[Common.pm.patch](https://github.com/znuny/Znuny/files/11487990/Common.pm.patch)

**Comment by rkaldung** [comment]
Internal Issue 633

**Comment by CallMeFlanby** [comment]
Hi, I opened a PR ([Pull 496](https://github.com/znuny/Znuny/pull/496)) related to this. We already use this solution in our company and have to update every time this file. Please have a look on it. :)

**Comment by rkaldung** [comment]
@rkaldung Already done and I left you a comment ;-)

**Comment by CallMeFlanby** [comment]
> @rkaldung Already done and I left you a comment ;-)

Thanks. New PR #502 .

**Comment by CallMeFlanby** [comment]
> > @rkaldung Already done and I left you a comment ;-)
> 
> Thanks. New PR #502 .

@rkaldung Could you please check the new PR?

**Comment by rkaldung** [comment]
The pull request is part of Znuny 7.0.18 and Znuny LTS 6.5.9. Thank you @CallMeFlanby
