### ISSUE TITLE
Bug - Znuny 7: Priority has no color 

### ISSUE THREAD

**Issue by ghostbiker** [znuny/Znuny#443]
### Environment

- OS:           macOS
- Browser:     Firefox, Safari
- Znuny version: 7.0.5

### Expected behaviour

Dashes in front of a ticket in a ticket list should have a color when priority is not 3 

### Actual behaviour

Dashes are only in gray, although priority is 1,2,4 or 5

### How to reproduce

1. Go to Ticketlist
2. Click on change priority to 1,2,4 or 5
3. See error

### Screenshots

<img width="1318" alt="2023-06-01_16-25-44" src="https://github.com/znuny/Znuny/assets/15995107/0bffae45-70e6-4d58-b910-8e8861bbd6a0">

**Comment by rkaldung** [comment]
Internal Issue 642

**Comment by jepf** [comment]
Will be part of Znuny release 7.0.6.
