### ISSUE TITLE
Bug - Znuny 7: The sort order by age is not saved

### ISSUE THREAD

**Issue by ghostbiker** [znuny/Znuny#444]
### Environment

- OS:           macOS 13.4
- Browser:      Firefox, Safari
- Znuny version: 7.0.5

### Expected behaviour

Ticket lists should save selected sort orders (i.E. by Age - newest first) (like Znuny 6.5)

### Actual behaviour

If you select order by age, after every refresh, sort order is reset to "default"

### How to reproduce

1. Go to "New Ticket list"
2. Click on "age" (newest first)
3. click reload 
4. Now: (oldest first)

### Screenshots

<img width="1802" alt="2023-06-05_15-27-54" src="https://github.com/znuny/Znuny/assets/15995107/9c926d11-631e-4c25-86b4-9697f4be063c">

**Comment by rkaldung** [comment]
@ghostbiker This has been the regular behavior since the dashboard was introduced. The system configuration of every single widget determines the sort order. If this should be changed, please open a [feature request](https://github.com/znuny/znuny-feature-requests).
