### ISSUE TITLE
Regression: Process Ticket without Richtext loses line breaks

### ISSUE THREAD

**Issue by tpokorra** [znuny/Znuny#447]
### Environment

- OS:         Linux
- Browser:      Firefox
- Znuny version: 6.5.2

### Expected behaviour

We have the setting Frontend::Richtext disabled.
We want to create a new process ticket, with Article element in the dialog.
We enter multiple lines in the body of the ticket.
We expect the line breaks to be still there after saving the ticket.

### Actual behaviour

The line breaks are gone.

### How to reproduce

see expected behaviour.

### Additional information

This seems to be a regression with this commit, for 6.5.1:
https://github.com/znuny/Znuny/commit/32fb176c8a19901167a8156b8480b03f7af40f90#diff-def9b6b864bdd3b8985bf33929d949d6c05ea7a64bd011405cab3a8383683c78R2866
(Added support for smart tags to process activity dialog article field.)
If I comment the lines after `$Data{Body} = $TemplateGeneratorObject->_Replace` and after ` $Param{GetParam}->{Body} = $TemplateGeneratorObject->_Replace`, then it works like expected.

**Comment by rkaldung** [comment]
@dignin Please verify

**Comment by tpokorra** [comment]
My workaround only helps for displaying the text with line breaks, but it seems when saving the ticket, it will be saved without linebreaks.
EDIT: my mistake, I forgot to comment the lines in _StoreActivityDialog

Any chance @NiklasSchmitt you could please look at this again? I think it was your commit that brought the change.

**Comment by dignin** [comment]
@tpokorra , we are working on this internally and will inform you here when fixed.

**Comment by dennykorsukewitz** [comment]
Fixed
6.5 https://github.com/znuny/Znuny/commit/873e309b31595be3a2dd9311278c7b91b667e28a
7.0 https://github.com/znuny/Znuny/commit/b63959c13eab24198fec48cdcdc41a59446088b0
