### ISSUE TITLE
Bug - Cant Delete Generic Agent Execution Event

### ISSUE THREAD

**Issue by mo-azfar** [znuny/Znuny#448]
### Environment

- OS:           Windows
- Browser:      Edge
- Znuny version: 7.0.6

### Expected behaviour

Being able to delete selected event based execution at Generic Agent

### Actual behaviour

Selected generic agent event based execution cant be delete

### How to reproduce

1. Go to 'Admin > Generic Agent'.
2. Create a Generic Agent with any event based execution.
3. Delete back selected event.
4. The screen just refresh and going back to top. Event not delete.

### Screenshots

![Untitled (1)](https://github.com/znuny/Znuny/assets/62957738/48b6ac9c-1382-4dca-a0b8-727b09940369)

**Comment by NiklasSchmitt** [comment]
internal issue 652

**Comment by NiklasSchmitt** [comment]
This issue is fixed within commit https://github.com/znuny/Znuny/commit/445698c455e41765c6c60cb539d5c3d467d005e2 and will be part of the next Znuny version 7.0.8
