### ISSUE TITLE
Bug(?) - Some Layout/Design topics

### ISSUE THREAD

**Issue by greinick** [znuny/Znuny#450]
### Environment

- OS:          macOS/Linux  
- Browser:      Firefox, Safari 
- Znuny version: 7.0.6  

### Expected behaviour

The new layout and interface design should be an improvement and more user/agent friendly.

### Actual behaviour

We see some smaller layout/design issues, not functional bugs, some are cosmetic.:

- All overview tables, e.g article overview of an ticket or the QueueView table with all tickets have quiet "huge" row heights compared to the text in it. So there is "a lot of wasted" space. Reducing the blank space by a few pixels would make the list more compact and from our pov more useable.
- On macOS/Firefox the overview tables cuts off the lower part of letters like g,j,p .... not on macOS/Safari
- The Default font size for ticket text is quiet small.... using a 2/4K Display it is close to unreadable ... Is that adjustable per user setting without "zooming" the page? Beside that Znuny uses +- a dozen fonts/styles on e.g. the ticket page. Why?
- The information " To protect your privacy, remote content was blocked. Load blocked content. " is part of the ticket text and so could be missed ....
- Overall the new lay out looks more stretched and you have to scroll more.
- Is it possible to set a new (better) window size when answering a ticket? The windows which pops up only covers half of the contents and is only 2/3 of the display size, so I always have to resize it first ...
- What is the little > triangle at the pages top for :) ? If it points ">" to the right, I can click the bell adn my profile icon. If it points left "<" I can't klick thous icons, but see nothing else of use ...   

### Additional information

I know, design and layout etc depend on personal preferences. So the mentioned topics are here for suggestion and to talk about.

Hope we all profit from it!

### Screenshots
<img width="714" alt="Bildschirmfoto 2023-06-20 um 10 45 11" src="https://github.com/znuny/Znuny/assets/23695606/a369e102-a312-4a63-978c-daaf2c86012f">
<img width="772" alt="Bildschirmfoto 2023-06-20 um 10 45 44" src="https://github.com/znuny/Znuny/assets/23695606/0cbc302c-9559-4e97-b4de-e96fa2df5ce1">

**Comment by greinick** [comment]
One more thing:

"The Load blocked content"-link opens the whole znuny dashboard interface page in the ticket frame ....

**Comment by dignin** [comment]
> One more thing:
> 
> "The Load blocked content"-link opens the whole znuny dashboard interface page in the ticket frame ....

This issue is being handled in #454 . Thx

**Comment by dignin** [comment]
@greinick , thanks for your feedback. There are new ways to control height, color, and spacing, which you should take a look at

Core.Vars.css
Core.Colors.css

Please open two issues:

- The information " To protect your privacy, remote content was blocked. Load blocked content. " is part of the ticket text and so could be missed ....
- What is the little > triangle at the pages top for :) ? If it points ">" to the right, I can click the bell adn my profile icon. If it points left "<" I can't klick thous icons, but see nothing else of use ...

Please use the Bug Report Template. I will look into them when I have the report. For all other support issues, please ask or very active community https://community.znuny.org/ I'll close this report. Thanks for helping us keep our channels clean by directing discussions to the community, and issues to GitHub.


If you have specific issues, please always address one issue at a time.
