### ISSUE TITLE
Bug - Failing Fetchmails - MailAccountFetch and MSOffice

### ISSUE THREAD

**Issue by ThWelte** [znuny/Znuny#453]
### Environment

- OS: Linux Debian          
- Browser: any      
- Znuny version: 6.4.3 and 6.5.3

### Expected behaviour

Fetch mails from Office365 INBOX and create new Tickets.

### Actual behaviour

Process keeps active til 600sec timeout which kills this child process and starts anoher try
-> No new Tickets because Mail INBOX is not fetched

### How to reproduce

1. Set up OAuth2 with MS Office -> valid Token
2. Set up Znuny Postmaster with this OAuth Token
3. Wait for Daemon trying to fetch Mails through MailAccountFetch
4. Error TimeOut of MailAccountFetch

https://www.znuny.org/de/blog/modern-authentication-with-microsoft

### Additional information
Other user get same problem like me
https://community.znuny.org/viewtopic.php?f=62&t=43689&p=177308#p177308

Problem may come from MS Office Update "MC545914"
Graph Connector Content Results Experience Switches to Results Inline in All Vertical

Tested Solutions:
- Update to LTS
- reboot everything
- Kill child processes 
- looked into DB for active processes
-  "--force-pid"

#OTRS-otrs.Console.pl-Maint::Email::MailQueue-42
There was an error executing Execute() in Kernel::System::Console::Command::Maint::Email::MailQueue: Error: Message sending already in progress! Skipping...

#OTRS-otrs.Console.pl-Maint::PostMaster::MailAccountFetch-42
There was an error executing Execute() in Kernel::System::Console::Command::Maint::PostMaster::MailAccountFetch: Error: Timeout of 600 seconds reached, killing child process!

**Comment by hanneshal** [comment]
Hi,

does this problem occur since the 23rd?

Please also note that there is an incident pending on MS Side. 

You can find it in the admin center:

<img width="559" alt="image" src="https://github.com/znuny/Znuny/assets/804939/e951556c-9882-4b8b-87ae-15e85de7c8ca">

You may be successful with switching to POP3S, but this only a short term solution. As far as we can tell the problem needs to be addressed on MS side.

**Comment by ThWelte** [comment]
Wow, thank you so much!!!
Switching to POP3S worked for us.
