### ISSUE TITLE
Bug - Error in AgentTicketQueue -> View L

### ISSUE THREAD

**Issue by dkfz2018** [znuny/Znuny#455]
### Environment

- OS:           debian 10
- Browser:      Firefox LTS, Chrome, Edge 
- Znuny version: 6.5.2

### Expected behaviour
View without of AgentTicketQueue Error Message from the Browser

### Actual behaviour

Open or Change the View from S or M to L getting a Error Message from the Browser (Javascript)

### How to reproduce

1. Go to the Action 'AgentTicketQueue'
2. Click on 'L-View'
3. Getting the Error from the Browser itself

### Screenshots

![OTRS_Error_2](https://github.com/znuny/Znuny/assets/35839011/30f98cf4-5c47-4f0d-9aa3-7d0b85d90c4e)
![OTRS_Error_1](https://github.com/znuny/Znuny/assets/35839011/6f20280d-6828-40d8-9d66-d84141acd1b6)

**Comment by hanneshal** [comment]
Hi @dkfz2018 ,

please update to 6.5.3 - the issue is fixed there already.

Reference:
https://github.com/znuny/Znuny/issues/430

Thank you!
Johannes
