### ISSUE TITLE
Bug – Deleting a ticket leaves mentions behind.

### ISSUE THREAD

**Issue by dignin** [znuny/Znuny#459]
### Environment

- OS:           any
- Browser:      any
- Znuny version: Znuny LTS 6.5 and Znuny 7

### Expected behaviour

A mention should be deleted, if the ticket is deleted.

### Actual behaviour

If users are mentioned in a ticket, and the ticket is deleted, then the mentoin remains.

### How to reproduce

1. Mention a user in a ticket.
2. Delete the ticket.
3. Notice the mention is still shown for the user.

```
bin/otrs.Console.pl Maint::Ticket::Delete --ticket-id 1

MariaDB [znuny]> select * from mention\G
*************************** 1. row ***************************
         id: 1
    user_id: 2
  ticket_id: 1
 article_id: 3
create_time: 2023-07-07 06:12:23
1 row in set (0.001 sec)

MariaDB [znuny]> select ticket_id from mention where ticket_id not in (select id from ticket);
+-----------+
| ticket_id |
+-----------+
|         1 |
+-----------+
1 row in set (0.001 sec)
```

### Screenshots

![Snag_34abb13](https://github.com/znuny/Znuny/assets/891283/3097ac62-43f1-4e62-aa5c-72b2ddd14094)

**Comment by dignin** [comment]
github #458 
internal 670

**Comment by dennykorsukewitz** [comment]
Fixed in
rel-6_5_4 - rel-6_5-dev - 501e2fd6538f4b2bd57889caaf4dfc4f43802da1
rel-7_0_8 -  rel-7_0-dev - 513cccbd8417a05170ce0ad9ec06f37d1ee5a217
