### ISSUE TITLE
Bug - TicketUpdate generic interface operation sends HTML TAGS in signature for messsages with ContentType text/plain

### ISSUE THREAD

**Issue by dignin** [znuny/Znuny#460]
### Environment

- OS:           any
- Browser:      any
- Znuny version: Znuny LTS 6.5 and Znuny 7

### Expected behaviour

Using the generic interface operation with ArticleSend to send a plain text email, should result in a plain text signature being sent, as if Frontend::RichText were disabled..

### Actual behaviour

The HTML Content is placed in plain text, rather than converted.

### Screenshots

![Snag_4633726](https://github.com/znuny/Znuny/assets/891283/0a887907-d52c-47ef-8c76-007df6686b7a)

**Comment by dignin** [comment]
Internal Issue 671

**Comment by rkaldung** [comment]
Part of Znuny 7.0.12 and Znuny LTS 6.5.5
