### ISSUE TITLE
Znuny7 - Dropdown arrow does not drop down dropdown box

### ISSUE THREAD

**Issue by chrullrich** [znuny/Znuny#466]
### Environment

- Browser:      Edge
- Znuny version: 7.0.9

### Expected behaviour

Clicking the dropdown arrow in a dropdown box drops down the box. If _any_ part of the dropdown box should drop down the box, I think it would be the dropdown arrow.

### Actual behaviour

Clicking the dropdown arrow does not drop down the box, clicking anywhere else does.

### How to reproduce

1. Open a ticket in zoom view
2. Click on the dropdown arrow in the reply type box
3. Note that the box does not drop down

### Screenshots

Clicking anywhere in the green region will drop down the box, clicking in the red region does not.

![image](https://github.com/znuny/Znuny/assets/4695907/fe50f982-e479-4d54-999c-e4d8350abb9c)

**Comment by dennykorsukewitz** [comment]
internal issue 716

**Comment by dennykorsukewitz** [comment]
Fixed with: 3fde8ea89836bd7189f6c1942ada2198ba9573e1
