### ISSUE TITLE
Znuny 7.0.9 - The System Show "Znuny Daemon is not running."

### ISSUE THREAD

**Issue by tune6688** [znuny/Znuny#468]
Environment
OS: centos8
Browser: Chrome/Firefox/...
Znuny version: 7.0.9

Started the Znuny Daemon from the console,It's normal.
![43d2b360a9fddfdff0a150ccf00187b](https://github.com/znuny/Znuny/assets/70299028/8bb7fb06-d7fc-4d72-b6e8-a75a91a833fb)

Back to the system, it is still show  "Znuny Daemon is not running."
![491f6be2b9b242165006526573bbfc6](https://github.com/znuny/Znuny/assets/70299028/0edda13d-88a8-47c5-a503-f9a30a223215)

Try to stoped the Demon and restart it , the same issue.

Please check it. 

Thank your !

**Comment by hanneshal** [comment]
Hi @tune6688,

just a note upfront:
please do not start the Daemon manually. 
Always "let it start" via Cron.

Regarding your error:
please check for other running instances. This is often the cause of this issue
`ps aux|grep Daemon` should be a start.

Johannes

**Comment by rkaldung** [comment]
@tune6688 Have you reloaded the dashboard after you've started the daemon?

**Comment by tune6688** [comment]
Thank you very much for your help,it is running!
