### ISSUE TITLE
Bug - AgentTicketNoteToLinkedTicket template not correctly updated to Znuny 7

### ISSUE THREAD

**Issue by tipue-dev** [znuny/Znuny#470]
### Environment

- OS:           n.a.
- Browser:      n.a.
- Znuny version: 7.x.x

### Expected behaviour

Fields that are show should match the new design. The way it is now, the hiding on the pending-state-time also doesn't work.
I also noticed, there is no xml entry to add dynamic fields, while the code for that function is still present in the .pm and the .tt.

### Actual behaviour
See screenhot.

### How to reproduce

 - Activate all possible fields in the system configuration for the settings 'AgentTicketNoteToLinkedTicket###'. 
 - Link a ticket to another ticket. 
 - Open the popup via the link on an article

### Screenshots
![AgentTicketNoteToLinkedTicket](https://github.com/znuny/Znuny/assets/80031303/22dddc1a-26f5-4e58-a791-2ea5abb695a7)

**Comment by dennykorsukewitz** [comment]
internal issue: 700

**Comment by dennykorsukewitz** [comment]
Fixed https://github.com/znuny/Znuny/commit/c50c0ac07d228d8f2b97df1c4579a0e0dddc3cc5
