### ISSUE TITLE
Generic Agent - job settings - Select Tickets: Fulltext search-limitation in "Subject"

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#474]
Parameters:
Znuny7

Browsers tested:
Edge, Chrome

OS:
Debian, bookworm

Requirement:
I need a large amount of different keywords in the subject line.

Problem:
It seems that there are some kind of limitations either in maximum subject length or in summary of logical connections made like described in Ticket::GenericAgentTicketSearch: "(*key1*||*key2*)" or in combination of both.

For example the maximum just working fine is:
![image](https://github.com/znuny/Znuny/assets/72391822/b1a03a06-88ec-4acb-8538-a12804a32610)
But one "OR" more, the setting was not taken over after "Save".

The same effect I have with less "OR"s combined with longer strings between the "OR"s.

Is there a way to exceed the limitations or is it a bug?

###########
Edit:
I found out how to write the syntax correctly:
"*01*"||"*02*"||"*03*"||"*04*"||"*05*"||"*06*"||...

None working characters (for now):
":"
"["
"]"
Is it possible to add escaping functionality?

Fpr some reasons this string is not working:
"*QT*"

**Comment by rkaldung** [comment]
@schnudd31do3 The real problem is that there is no maximum length for the input fields defined. When saving such a
 
GenericAgent, the field's value is gone without a visible error message for the user. The problem is logged in Znuny's system log:

> Data too long for column 'job_value' at row 1, SQL: 'INSERT INTO generic_agent_jobs (job_name, job_key, job_value) VALUES (?, ?, ?)'

The current length is limited to 200 characters in the table generic_agent_jobs.

**Comment by rkaldung** [comment]
Internal issue 723

**Comment by rkaldung** [comment]
@schnudd31do3 Errors are now prevented in Znuny 7.0.12 (3142f9ee076f8ba510a6fbeab29b154deb6a01f5)
