### ISSUE TITLE
Bug - Alert dialog position too low to be interactable

### ISSUE THREAD

**Issue by tipue-dev** [znuny/Znuny#483]
### Environment

- OS:           Linux
- Browser:      Chrome
- Znuny version: 7.x.x

### Expected behaviour

Alert dialog should be shown directly in the visible field of the agent.

### Actual behaviour

The dialog is way to low and therefore not interactable. This Issue is at least present in AgentTicketPhone, and when trying to remove the last field in a transition.

This is the reason for two failing tests:
 - Selenium/Agent/Admin/ProcessManagement/AdminProcessManagementTransition.t
 - Selenium/Agent/MultiAttachmentUpload/CreateScreens.t

### How to reproduce

1. Go to AgentTicketPhone
2. Move a file, bigger than allowed, into the upload area
3. You'll see a darker page. The Dialog must be moved using the browsers development tools.

### Videos

https://github.com/znuny/Znuny/assets/80031303/5a2ef544-7d8f-46c4-8504-263864167581

https://github.com/znuny/Znuny/assets/80031303/2fd0da8d-e5ae-4134-b557-63342c602573

**Comment by mo-azfar** [comment]
Hi
this also happen in process management when expand the dynamic field widget especially if widget group is quite a lot.


https://github.com/znuny/Znuny/assets/62957738/a7c6925c-6c6f-48ab-a27c-fe2f374ef5e9

**Comment by rkaldung** [comment]
Internal issue 727

**Comment by mo-azfar** [comment]
> Hi this also happen in process management when expand the dynamic field widget especially if widget group is quite a lot.
> 
>  2023-09-14.10-32-50.mp4

Hi..i checked on this again..and still happening in 7.0.12.
Should i open a new issue or continue from here ?

https://github.com/znuny/Znuny/assets/62957738/07e9a4f0-47bd-43f7-a680-960aaaea3ad9

**Comment by rkaldung** [comment]
@mo-azfar Is this still an issue with 7.0.14?

**Comment by mo-azfar** [comment]
Hi @rkaldung ,
yes still happening in latest 7.0.14


https://github.com/znuny/Znuny/assets/62957738/0ef3d6f0-104a-408e-a376-70c50f1490e1

**Comment by rkaldung** [comment]
@mo-azfar I can't replocate this with 7.0.15/rel-7_0-dev. Please open a new issue if this still happens to you.
