### ISSUE TITLE
Bug - As a customer I cannot see the full message on closed tickets

### ISSUE THREAD

**Issue by Coleoptera180** [znuny/Znuny#488]
### Environment

- OS:           Independent
- Browser:      Independent
- Znuny version: 7.0.9

### Expected behaviour

Login as a customer, go to closed tickets and open one. The content of all messages is completely visible.

### Actual behaviour

The content of the messages is cut short and there is no possibility to see the whole message text.

### How to reproduce

1. Login as a customer
2. Go to closed tickets
3. Select a closed ticket
4. Try to read message text

### Screenshots

![grafik](https://github.com/znuny/Znuny/assets/41924565/5a182798-8d43-432b-913d-2b82e46082e6)

**Comment by dennykorsukewitz** [comment]
Hi  @Coleoptera180 ,
thanks for your report.

I think this is already fixed.
https://github.com/znuny/Znuny/commit/abcf1b7dc5f073bedf8ea9c2437a8eac5398db86

Regards :rocket:
Denny
