### ISSUE TITLE
Bug - Calendar overview colour does not reflect individual calendar colours

### ISSUE THREAD

**Issue by nodrogneirbo** [znuny/Znuny#490]
### Environment

- OS:           KDE Neon (Ubuntu)
- Browser:      Edge & Firefox
- Znuny version: 7.0.2

### Expected behaviour

In previous versions the calendar overview shows the individual appointment calendar colour on the calendar

### Actual behaviour

V7 all entries are orange, and only hover-over reveals the category. 

### How to reproduce

2. Click on '...'
3. Scroll down to '...'

### Additional information

This may be a design decision but from a usability point of view makes it harder to understand at a glance. Perhaps this is a feature request rather than a bug?

**Comment by NiklasSchmitt** [comment]
This should be fixed since Znuny 7.0.5 - https://github.com/znuny/Znuny/issues/411
