### ISSUE TITLE
Bug - Customer Portal Header Toolbar submenu not working

### ISSUE THREAD

**Issue by mo-azfar** [znuny/Znuny#493]
### Environment

- OS:           Windows
- Browser:      Edge, Firefox
- Znuny version: 7.0.10

### Expected behaviour

When clicking / hover on the customer portal toolbar (user initials), i would be able to access preferences and logout submenu 

### Actual behaviour

When clicking / hover on the customer portal toolbar (user initials), then moment mouse move over, the submenu disappear. 
Have to to try it few time untill it can be click.

### How to reproduce

1. Go to 'Customer Portal and Login'
2. Click or hovwer on 'toolbar (user initial)'
3. Move down mouse to the submenu
4. the popup menu gone

### Screenshots

https://github.com/znuny/Znuny/assets/62957738/80b4de5c-d6f4-4d01-8b0e-5fd2fbd25325

**Comment by dignin** [comment]
Internal Issue 726

**Comment by dennykorsukewitz** [comment]
Fixed with 7c04d43dec9f8355c1ea810e4af063d26a5892ce
