### ISSUE TITLE
Bug - Problem with Customer Location TimeZone format hu.pm

### ISSUE THREAD

**Issue by nancy1979** [znuny/Znuny#5]
get after customer creation company in hungary error in apache log and status is 
it is not possible to open AdminLog
 Action=AdminLog Can't call method "ToTimeZone" on an undefined value

```
Jan 20 08:12:52 otrs-itsm-prod OTRS-CGI-25[32626]: [Error][Kernel::System::DateTime::new][Line:174]: Error creating DateTime object ( 'String' => '202119-1-19 07:15:54' ).
Jan 20 08:12:53 otrs-itsm-prod OTRS-CGI-25[32730]: [Error][Kernel::System::DateTime::_StringToHash][Line:1753]: Invalid date/time string 202119-1-19 07:15:54.
Jan 20 08:12:53 otrs-itsm-prod OTRS-CGI-25[32730]: [Error][Kernel::System::DateTime::_CPANDateTimeObjectCreate][Line:1812]: Invalid value for String: 202119-1-19 07:15:54.
Jan 20 08:12:53 otrs-itsm-prod OTRS-CGI-25[32730]: [Error][Kernel::System::DateTime::new][Line:174]: Error creating DateTime object ( 'String' => '202119-1-19 07:15:54' ).
Jan 20 08:12:54 otrs-itsm-prod OTRS-CGI-25[415]: [Error][Kernel::System::DateTime::_StringToHash][Line:1753]: Invalid date/time string 202119-1-19 07:15:54.
Jan 20 08:12:54 otrs-itsm-prod OTRS-CGI-25[415]: [Error][Kernel::System::DateTime::_CPANDateTimeObjectCreate][Line:1812]: Invalid value for String: 202119-1-19 07:15:54.
Jan 20 08:12:54 otrs-itsm-prod OTRS-CGI-25[415]: [Error][Kernel::System::DateTime::new][Line:174]: Error creating DateTime object ( 'String' => '202119-1-19 07:15:54' ).
Jan 20 08:14:04 otrs-itsm-prod OTRS-CGI-25[412]: [Error][Kernel::System::DateTime::_StringToHash][Line:1753]: Invalid date/time string 202119-1-19 07:15:54.
Jan 20 08:14:04 otrs-itsm-prod OTRS-CGI-25[412]: [Error][Kernel::System::DateTime::_CPANDateTimeObjectCreate][Line:1812]: Invalid value for String: 202119-1-19 07:15:54.
Jan 20 08:14:04 otrs-itsm-prod OTRS-CGI-25[412]: [Error][Kernel::System::DateTime::new][Line:174]: Error creating DateTime object ( 'String' => '202119-1-19 07:15:54' ).

```

### How to reproduce

1. Go to 'AdminCustomerCompany'
2. Click on 'new'
3. Scroll down to 'loaction/ country'
4. See error in syslog, errorlog, apache status  

### Screenshots
![image](https://user-images.githubusercontent.com/77772784/105316124-bd237c80-5bc0-11eb-9f9d-a48c9532c539.png)

### Environment

- OS: [Linux]
- Browser: [Chrome,]
- OTRS version [e. g. 6.0.30]

### Additional information
 /opt/otrs/Custom/Kernel/Language/hu.pm

if i change the part 
`$Self->{DateFormatLong} = '%Y. %B %D. %A %T'; in '%Y-%M-%D - %T'; 
`
to 
`$Self->{DateFormatLong} = '%Y-%M-%D - %T';`
it works

**Comment by dennykorsukewitz** [comment]
Hi nancy1979,
thanks for the report.

Unfortunately we could not reproduce your error.

`DateFormatLong` will not be the problem at this point.

```
$Self->{DateFormatLong} = '%Y. %B %D. %A %T';
$Self->{DateFormatLong} = '2021. jan. 25. h 11:38:55'
```

This format has nothing to do with the one in the error message:
`'String' => '202119-1-19 07:15:54'`

Here you can see that the `19` (probably day) occurs twice.
The function _StringToHash reports the error when initializing the DateTimeObject.


1. OM Create DateTimeObject

```perl 
my $DateTimeObject = $Kernel::OM->Create(
    'Kernel::System::DateTime',
    ObjectParams => {
        String => '202119-1-19 07:15:54',
    }
);
```

2. _CPANDateTimeObjectCreate

```perl
my $CPANDateTimeObject = $Self->_CPANDateTimeObjectCreate(%Param);
```

3. _StringToHash
```perl
my $DateTimeHash = $DateTimeObject->_StringToHash( String => '2016-08-14 22:45:00' );
```

---

I guess that you have installed packages in the system?
Maybe the error is somewhere here.
We just need more information at this point.


Best regards,
Denny

**Comment by nancy1979** [comment]
this packages are installaed
./otrs.Console.pl Admin::Package::List
Listing all installed packages...
+----------------------------------------------------------------------------+
| Name:        FAQ
| Version:     6.0.28
| Vendor:      OTRS AG
| URL:         https://otrs.com/
| License:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
| Description: The FAQ/knowledge base.
+----------------------------------------------------------------------------+
| Name:        GeneralCatalog
| Version:     6.0.30
| Vendor:      OTRS AG
| URL:         https://otrs.com/
| License:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
| Description: The General Catalog package.
+----------------------------------------------------------------------------+
| Name:        HideDynamicFields
| Version:     6.0.2
| Vendor:      Perl-Services.de
| URL:         http://www.perl-services.de
| License:     GNU AFFERO GENERAL PUBLIC LICENSE Version 3, November 2007
| Description: Outputfilter to show/hide dynamic fields based on various ticket attributes
+----------------------------------------------------------------------------+
| Name:        ImportExport
| Version:     6.0.30
| Vendor:      OTRS AG
| URL:         https://otrs.com/
| License:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
| Description: The ImportExport package.
+----------------------------------------------------------------------------+
| Name:        ITSM
| Version:     6.0.30
| Vendor:      OTRS AG
| URL:         https://otrs.com/
| License:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
| Description: The OTRS::ITSM bundle package.
+----------------------------------------------------------------------------+
| Name:        ITSMChangeManagement
| Version:     6.0.30
| Vendor:      OTRS AG
| URL:         https://otrs.com/
| License:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
| Description: The OTRS::ITSM Change Management package.
+----------------------------------------------------------------------------+
| Name:        ITSMConfigurationManagement
| Version:     6.0.30
| Vendor:      OTRS AG
| URL:         https://otrs.com/
| License:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
| Description: The OTRS::ITSM Configuration Management package.
+----------------------------------------------------------------------------+
| Name:        ITSMCore
| Version:     6.0.30
| Vendor:      OTRS AG
| URL:         https://otrs.com/
| License:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
| Description: The OTRS::ITSM Core package.
+----------------------------------------------------------------------------+
| Name:        ITSMIncidentProblemManagement
| Version:     6.0.30
| Vendor:      OTRS AG
| URL:         https://otrs.com/
| License:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
| Description: The OTRS::ITSM Incident and Problem Management package.
+----------------------------------------------------------------------------+
| Name:        ITSMServiceLevelManagement
| Version:     6.0.30
| Vendor:      OTRS AG
| URL:         https://otrs.com/
| License:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
| Description: The OTRS::ITSM Service Level Management package.
+----------------------------------------------------------------------------+

**Comment by dennykorsukewitz** [comment]
Hi @nancy1979

probably, your log has stored a wrong date, which now causes problems when calling the Action=AdminLog.
Can you please run the following command on the shell to clear all log entries.

```
bin/otrs.Console.pl Maint::Log::Clear
```

After that the log should be empty and AdminLog should have no more errors.

If the problem occurs at a later time, you have to check at which action the wrong date is written.

Best regards,
Denny

**Comment by dennykorsukewitz** [comment]
Hi @nancy1979

this issue is closed for now.
If you need more help, you are welcome to reopen the issue.

Best regards
Denny
