### ISSUE TITLE
Bug - Dynamic Field Webservice Additional Attributes Not Send To Webservice Invoker

### ISSUE THREAD

**Issue by mo-azfar** [znuny/Znuny#501]
### Environment

- OS:           Windows 11
- Browser:      IE
- Znuny version: 7.011

### Expected behaviour

Dynamic Field Webservice additional attributes will send selected data to Invoker

### Actual behaviour

Only few data send to invoker although all additional attributes selected.
- Missing Owner, CustomerUser, Customer, Queue and State

### How to reproduce

1. Configure Dynamic Field Webservice with Additional Attributes (select all)

![1](https://github.com/znuny/Znuny/assets/62957738/8433a6ae-d8f9-49de-8746-2dfc00d48082)

2. See webservice debugger log

![2](https://github.com/znuny/Znuny/assets/62957738/c0c491cc-ef04-4b7f-8558-bf37a661b2c9)

**Comment by Tronsy** [comment]
hi @mo-azfar 
The attributes can only transfer values from the current mask.
This means that all dynamic fields and ticket attributes that you want to use in the Invoker must also be displayed in the mask in which you use the DynamicField Webservices.

I therefore assume that the Owner, CustomerUser, Customer, Queue and State attributes are not displayed in the mask in which you have tested. Is that correct? 

I will see to it that we describe this better in the documentation.

**Comment by mo-azfar** [comment]
Yes..you right..these missing values not within the mask..Now i understand..😅..you may close this issue

Thanks for the clarification
