### ISSUE TITLE
BUG: Incorrect URL forming in Status View (Medium)

### ISSUE THREAD

**Issue by sergiykhan** [znuny/Znuny#506]
# Version
Znuny LTS 6.5.4

# Description
There a bug in `Kernel/Output/HTML/Templates/Standard/AgentTicketOverviewMedium.tt` leading to incorrect forming of the URL under `CustomerID` for the Medium view on the Status View page.

# Actual behavior
The formed link is `https://address/otrs/[%%20Env(`

# Expected behavior
Link link should be `https://address/otrs/index.pl?Action=AgentCustomerInformationCenter;CustomerID=whatever`

# Solution
The `href` is missing `Interpolate` in `href="[% Config("CustomerDBLink") %]"`

```
--- a/Kernel/Output/HTML/Templates/Standard/AgentTicketOverviewMedium.tt
+++ b/Kernel/Output/HTML/Templates/Standard/AgentTicketOverviewMedium.tt
@@ -209,7 +209,7 @@
 [% IF Data.IsITSMIncidentProblemManagementInstalled %]
                         <td>
 [% RenderBlockStart("CustomerIDRW") %]
-                            <label>[% Translate("CustomerID") | html %]</label><a href="[% Config("CustomerDBLink") %]" class="AsPopup PopupType_TicketAction" [% Config("CustomerDBLinkTarget") %]>[% Data.CustomerID | html %]</a>
+                            <label>[% Translate("CustomerID") | html %]</label><a href="[% Config("CustomerDBLink") | Interpolate %]" class="AsPopup PopupType_TicketAction" [% Config("CustomerDBLinkTarget") %]>[% Data.CustomerID | html %]</a>
 [% RenderBlockEnd("CustomerIDRW") %]
 [% RenderBlockStart("CustomerIDRO") %]
                             <label>[% Translate("CustomerID") | html %]</label>[% Data.CustomerID | html %]
```

**Comment by NiklasSchmitt** [comment]
internal issue: 769

Affects Znuny LTS and also Znuny 7.

**Comment by NiklasSchmitt** [comment]
Fixed with the following commits:
- Znuny 6.5: https://github.com/znuny/Znuny/commit/514fb1c4a00cc908718d2335a499e3f239f66529
- Znuny 7: https://github.com/znuny/Znuny/commit/a45d0f4404f46eda1f06587283c68061afbba468
