### ISSUE TITLE
Bug - Znuny 7.0.12 does not save drafts

### ISSUE THREAD

**Issue by zweigleisig** [znuny/Znuny#507]
### Environment

- OS:           n.a.
- Browser:      n.a.
- Znuny version:  7.0.12

### Expected behaviour

Drafts should be stored completely

### Actual behaviour

In Zununy 7.0.12, if you write a reply to an ticket article and save it as a draft, the written text is not saved. The saved draft has the attachments attached and the title assigned, but the actual draft text is gone. When I look in the database I see that the text was not saved, so the problem is with saving the draft, not with opening the draft later.

### How to reproduce

1. Open a ticket
2. Reply using a template
3. Write text and add attachments
4. Store draft
5. Check draft

### Additional information

none

### Screenshots

none

**Comment by hanneshal** [comment]
@zweigleisig thanks for the report. I updated the issue to the standard template.
Please check if it is still correct

**Comment by rkaldung** [comment]
@zweigleisig We could verify and confirm the bug in Znuny 7.0.13, An internal issue to fix this will be created.

**Comment by rkaldung** [comment]
Internal issue 780

**Comment by rkaldung** [comment]
Fixed in Znuny LTS 6.5 with a574470d3e22222241c2b83c932987b67e3b454f and in Znuny 7.0.14 with 0e42574148c0c0550f390612785960da33ed22f8
