### ISSUE TITLE
The save button is not the standard submit button

### ISSUE THREAD

**Issue by zweigleisig** [znuny/Znuny#508]
### Environment

- OS:           n.a.
- Browser:      n.a.
- Znuny version:  7.0.12

### Expected behaviour

The default submit botton in a form should be "Save" for using the Enter key.

### Actual behaviour

In AgentTicketFreeText, the default action carried out by pressing the Enter key (e.g. after changing the title of a ticket) is not "Submit" but "Save as draft".

### How to reproduce

1. Open a ticket
2. Select Miscellaneous > Free Fields
3. Change the titel
4. Press enter whilst the focus is still on the title input field

### Additional information

As a workaround, we disabled the draft button in the SysConfig

### Screenshots

none

**Comment by KaldungJr** [comment]
We were able to verify the issue and we will clarify if this behaviour is intended.

**Comment by NiklasSchmitt** [comment]
Hi @zweigleisig,

thanks a lot for your issue.
We have decided to change the behaviour and it will be fixed within the next Znuny version 7.0.16.

We have merged https://github.com/znuny/Znuny/pull/498 & commited some changed with commit https://github.com/znuny/Znuny/commit/e03c287617aa171c9a5fd3e4a404623c683d8942 to resolve this issue.

Best,
Niklas

**Comment by zweigleisig** [comment]
Unfortunately, the problem is not solved and unchanged in version 7.1.3.

**Comment by dennykorsukewitz** [comment]
Hi @zweigleisig 

https://github.com/znuny/Znuny/pull/498#issuecomment-2020634820

> Unfortunately we had to revert this PR because it had the side effect of forms without clickable submit buttons not being submittable anymore via Enter key.
Therefore, the ‘problem’ still exists.

Here is the new PullRequest with the improvements.
https://github.com/znuny/Znuny/pull/554

I'll give the PullRequest a bit of a boost.
