### ISSUE TITLE
Bug - [ Queue and Autoresponse]

### ISSUE THREAD

**Issue by carlosgarciagomez** [znuny/Znuny#509]
### Environment

- OS:           Rocky Linux 9.2 
- Browser:      Chrome, Firefox
- Znuny version: 7.0.5

### Expected behaviour

Autoresponse & Queue does not work when a new ticket is created.

### How to reproduce

1. Go to Admin => Queues/Autoresponses...
2. Edit your Queue and select on auto reply/new ticket section, => Select your autoresponse
3. Edit your Automatic response and on type, select automatic_response/new_ticket

When a ticket is created, There is no email sent to anybody.

Any test?

**Comment by rkaldung** [comment]
<img width="801" alt="image" src="https://github.com/znuny/Znuny/assets/378324/722e10d4-42c9-4213-a292-87dc261c543f">

Hello @carlosgarciagomez,
You using the wrong auto-response type. "Auto reply/new ticket" is used for follow-ups on closed tickets (No 1 in the image). Please use the type "reply" as shown in the image with no. 2.

**Comment by carlosgarciagomez** [comment]
You're right

I have just  found where the problem is.

The problem I have is that the client writes the email to an email address(1) which is redirected to another email address(2), which finaly is accessed by imap service and then queued.

That is, it does not work if the address to which the client sends to is different from the address associated with the imap service

Do you think of any solution that I can touch (configuration or code)?

Regards

**Comment by rkaldung** [comment]
Only the queue where the ticket is created determines if and which auto-reply is sent. The email address that the customer us using does not influence the auto-reply.

**Comment by dignin** [comment]
@carlosgarciagomez Your workflow was difficult to follow. As Roy said, the queue which receives the mail, is the one which has to have an auto-reply configured.

1. Can you send mail using the system by replying or creating an email ticket?
2. Does the e-mail land in the correct queue
3. Is there a header like AutoGenerated or Loop? You can look at the communication log, this might give you a clue.

**Comment by rkaldung** [comment]
We have updated the documentation for [Znuny LTS 6.5](https://doc.znuny.org/znuny_lts/admin/communication/autoresponses/index.html) and [Znuny 7.0](https://doc.znuny.org/znuny/admin/communication/autoresponses/index.html).
