### ISSUE TITLE
Bug - Customer Portal Login Form CSS / Layout

### ISSUE THREAD

**Issue by mo-azfar** [znuny/Znuny#512]
### Environment

- Server OS: Ubuntu
- Browser: Edge / Brave
- Znuny version: 7.0.13

### Expected behavior

When LDAP enabled, expected customer login form as below (from znuny 7.0.11 and 7.0.12)

![image](https://github.com/znuny/Znuny/assets/62957738/3ae030be-69ad-49a6-89c1-93c18dc8b513)

### Actual behavior

1. When LDAP enabled, customer login form as below.
Notice no space, no padding between two field and Login button.

![image](https://github.com/znuny/Znuny/assets/62957738/123142cb-67a1-4bee-b9ae-308e6e7de315)

2. When default DB is used

No space / no padding between username field and password label.
![image](https://github.com/znuny/Znuny/assets/62957738/76175b6b-e782-494f-a489-de404dddc44d)

Look like also effecting sign-up and forgot password section for DB.

![image](https://github.com/znuny/Znuny/assets/62957738/c201ee6b-446b-498d-8114-e21cd27a3a02)

![image](https://github.com/znuny/Znuny/assets/62957738/2c54a953-468a-4618-b8bf-c0cbac364d74)

### How to reproduce

1. Enable ldap for customer user.
2. Check customer portal login page

**Comment by NiklasSchmitt** [comment]
internal issue: 785

**Comment by rkaldung** [comment]
Bugfix is part of Znuny 7.0.15
