### ISSUE TITLE
Bug - Empty block (horizontal line) dynamic field group process management

### ISSUE THREAD

**Issue by mo-azfar** [znuny/Znuny#513]
### Environment

- Server OS: Ubuntu 22
- Browser: Brave / Edge
- Znuny version: 7.0.13

### Expected behavior

There is multiple process defined and multiple group in dynamic field widget group.
If some process didnt have the dynamic field value in defined widget group, the block should be hidden / remove.

### Actual behavior

There is multiple process defined and multiple group in dynamic field widget group.
If some process didnt have the dynamic field value in defined widget group, the block actually there and quite waste the space.

We can see it from the horizontal line there.

![image](https://github.com/znuny/Znuny/assets/62957738/19ab42dc-8c85-40c6-848c-fcf6adb8d7ea)

### How to reproduce

1. Create 2 process management.
2. Define dynamic field widget group.
3. See at ticket zoom view

**Comment by mo-azfar** [comment]
You can see the block is called in every group with no value checking. 
https://github.com/znuny/Znuny/blob/4ba26a0ec2e3f0c72bc96710c208b2318989e96e/Kernel/Modules/AgentTicketZoom.pm#L1658

Below is some code that i applied to tackle this. Perhaps you guys has a better way.

    my @FieldsInAGroup;
    for my $GroupName (
        sort keys %{ $Self->{DisplaySettings}->{ProcessWidgetDynamicFieldGroups} }
        )
    {
    
    # --
    # Remove empty block group for dynamic field.
    # --
    # $LayoutObject->Block(
    #     Name => 'ProcessWidgetDynamicFieldGroups',
    # );
    # --
    
    my $GroupFieldsString = $Self->{DisplaySettings}->{ProcessWidgetDynamicFieldGroups}->{$GroupName};

    $GroupFieldsString =~ s{\s}{}xmsg;
    my @GroupFields = split( ',', $GroupFieldsString );

    # --
    # Remove empty block group for dynamic field.
    # --
    my $ShowBlock = 0;
    for my $FieldChecker (@FieldsWidget) {
        if ( !$ShowBlock ){
            if ( grep { $_ eq $FieldChecker->{Name} } @GroupFields ) {
                $ShowBlock = 1;
            }
        }
    }

    if ( $ShowBlock ) {
        $LayoutObject->Block(
            Name => 'ProcessWidgetDynamicFieldGroups',
        );
    }
    # --

    if ( $#GroupFields + 1 ) {

![image](https://github.com/znuny/Znuny/assets/62957738/c37cd44a-5ee9-432f-97d8-f5a21df265be)

**Comment by KaldungJr** [comment]
We can't verify your issue with our existing example processes. Would you be able to send us your process used in the issue?

**Comment by mo-azfar** [comment]
> We can't verify your issue with our existing example processes. Would you be able to send us your process used in the issue?

Hi, basically my ProcessWidgetDynamicGroups as below with contain multiple df group across all process:

![image](https://github.com/znuny/Znuny/assets/62957738/470f39ac-650a-44e3-b1ff-26580bf003c2)


Let say i create a process ticket 'Software Support' as below (which only utilize 'Software Support' df group), we can see all the df group block has been called and display as horizontal line.

![image](https://github.com/znuny/Znuny/assets/62957738/401d2997-dcb5-458e-a1de-12610300be16)


[Export_ProcessEntityID_Process-22cfb5eb43279532308232c678671c34.zip](https://github.com/znuny/Znuny/files/13448938/Export_ProcessEntityID_Process-22cfb5eb43279532308232c678671c34.zip)

**Comment by rkaldung** [comment]
@mo-azfar Can you also add the dynamics (and screens) export?

**Comment by mo-azfar** [comment]
@rkaldung Yes..please refer attached zip file..also attached Config for ProcessWidgetDynamicFieldGroups
```

$Self->{'Ticket::Frontend::AgentTicketZoom'}->{'ProcessWidgetDynamicFieldGroups'} =  {
  '1. Basic Info' => 'Playbook, Status, DeviceName, UserType, Hash, HashResponse, DoubleCheckPreviousData, FalsePositive, PreviousDataNote, NetworkDetectionTools',
  '2. Affected Credentials & Level of Access' => 'AffectedCredentialsNote, AccessLevelCustomer, AccessLevelInternal, AccessLevel, AccessLevelAccountType,  AccessLevelNote',
  '2. Threat Analysis & Forensic' => 'ThreatCategory, ThreatAnalysisNote, ThreatAnalysisStatus, SecurityRiskLevel',
  '2. Threat Classification' => 'InformationReviewed, InformationReviewedNote, ThreatLevel',
  '3. Live Threat Actor and Analysis Log' => 'LiveThreatActor, LiveThreatActorNote, LogAnalysisFailedLogin, LogAnalysisSuccessLogin, LogAnalysisLateralMovement, LogAnalysisLateralMovementPath, LogAnalysisNote ',
  '3. Remediate Action' => 'RemediateMethod, RemediateNote, RemediateStatus',
  '3. Threat Scope' => 'EnvironmentLogReviewed, EnvironmentLogReviewedNote',
  '4. Password Checking' => 'PasswordReused, PasswordStrength',
  '4. Scanned Device' => 'ScanDeviceNote, ScanDeviceStatus',
  '4. Threat Mitigation' => 'ThreatMitigated, ThreatMitigatedNote',
  '5. Root Cause Analysis' => 'RootCauseAnalysis, RootCauseAnalysisNote',
  'Software Support' => 'RelatedContract, ContractID, ContractStartDate, ContractEndDate, SupportTag, RelatedContractDetail'
};
```

[Export Process and DF.zip](https://github.com/znuny/Znuny/files/13449132/Export.Process.and.DF.zip)

**Comment by rkaldung** [comment]
Internal issue 782

**Comment by dennykorsukewitz** [comment]
Hi @mo-azfar,

thanks for your report and the fix suggestion.

I have attached a patch here that is much simpler. 
Can you please check if the error is fixed with this patch.


[0001-782-Bug-Empty-block-horizontal-line-dynamic-field-gr.patch](https://github.com/znuny/Znuny/files/13788984/0001-782-Bug-Empty-block-horizontal-line-dynamic-field-gr.patch)

**Comment by mo-azfar** [comment]
> Hi @mo-azfar,
> 
> thanks for your report and the fix suggestion.
> 
> I have attached a patch here that is much simpler. Can you please check if the error is fixed with this patch.
> 
> [0001-782-Bug-Empty-block-horizontal-line-dynamic-field-gr.patch](https://github.com/znuny/Znuny/files/13788984/0001-782-Bug-Empty-block-horizontal-line-dynamic-field-gr.patch)

Hi @dennykorsukewitz ..thanks for the patch..

Before patch

![before-patch-00001](https://github.com/znuny/Znuny/assets/62957738/9aabed78-eec0-42c7-82e9-89ff3962c488)

However the display result as below after patched. Notice the dynamic field display is 1 x 1 instead of 4 x 1.

![after-patch-0001](https://github.com/znuny/Znuny/assets/62957738/cb8b607b-30b9-42b0-9a53-bde34bb2cfb3)

**Comment by dennykorsukewitz** [comment]
Hi @mo-azfar 

Ah, thanks for testing.
I'll take another look at it then.

**Comment by dennykorsukewitz** [comment]
Hi @mo-azfar 

I have adopted your idea and adapted it a little.
Can you check the fix again?

Thank you.

[0002-782-Bug-Empty-block-horizontal-line-dynamic-field-gr.patch](https://github.com/znuny/Znuny/files/13793265/0002-782-Bug-Empty-block-horizontal-line-dynamic-field-gr.patch)

**Comment by mo-azfar** [comment]
Hi @dennykorsukewitz ,

Tested with group and no-group..
Perfect :)

![image](https://github.com/znuny/Znuny/assets/62957738/b4415fa6-c5b9-4d0d-82fe-11a06825ff18)

**Comment by dennykorsukewitz** [comment]
7.0.15 https://github.com/znuny/Znuny/commit/a6a3c3f508239c71ce2de3f5ecfe9f0a50ba8d3f
