### ISSUE TITLE
Bug - [Dashboard and Widget Filters] - 2

### ISSUE THREAD

**Issue by peralta00** [znuny/Znuny#518]
### Environment

- Server OS: Ubuntu 22.04
- Browser: All
- Znuny version: 7.0.13

### Expected behavior

Drop down with all agents/customers to filter:

![image](https://github.com/znuny/Znuny/assets/21270917/7ac8da8a-c2ee-4cc8-8363-ab6801686ce3)

### Actual behavior

Only one or 2 agents/customers load in the filter dropdown

### How to reproduce

1.Go to 'Dashboard'
2.Click on 'Agent Filter' or 'Customer Filter'

### Additional information

N/A

**Comment by peralta00** [comment]
https://github.com/znuny/Znuny/issues/503

**Comment by dignin** [comment]
@peralta00 can you verify the issue is gone in 7.0.14?

**Comment by peralta00** [comment]
@dignin Remains the same, after updating to the latest version I get the same error in the dev console.

**Comment by dignin** [comment]
@peralta00 I cannot reproduce the issue on a standard system. 
Is your system a production update from a previous Znuny (OTRS) version? 
Do you have add-ons installed? 
Could you also disable the Sysconfig: Loader::Enabled::JS and recheck the console log, sending me your results?
Which widget or overview are you using?

**Comment by dignin** [comment]
My test was skewed. All users are selectable in the dashboard widget as a filter if no tickets are visible. 

![image](https://github.com/znuny/Znuny/assets/891283/c9eb3e85-ae04-488d-b531-b9ad8be17bbe)


If, however, you have visible tickets in the widget, only the users (owners) of listed tickets are included in the filter options. This would be our desired target behavior. What I needed clarification on in your screenshot: You had viewable tickets with owners not shown in the list of agents when clicking on the owner. Please add this to the list of feedback needs.

Do you only see the list of users which have tickets in your list, or is it always only two at a maximum?

**Comment by peralta00** [comment]
Working again, probably some addon !
