### ISSUE TITLE
Bug - [Mention cannot be removed via collection action]

### ISSUE THREAD

**Issue by aengelha-plano** [znuny/Znuny#519]
### Produktion

- Server OS: Windows
- Browser: Chrome, Firefox, Edge
- Znuny version: 6.4.5

### Expected behavior

Mentions can be removed via the collection action

### Actual behavior

Mentions can't be removed via the collection action

### How to reproduce

1. Go to 'Mention'
![image](https://github.com/znuny/Znuny/assets/153006091/0b6a0ad0-87fb-43a9-a368-cb365d047cf1)

2. Mark tickets
![image](https://github.com/znuny/Znuny/assets/153006091/299a74cd-b8a9-4467-862d-36046880d17a)

3. Click on 'removed mention'
![image](https://github.com/znuny/Znuny/assets/153006091/16a910c2-a6bf-49f3-8843-5217bf751278)

4.
![image](https://github.com/znuny/Znuny/assets/153006091/f7f5b64c-221b-4bbd-b88e-c08f533874ea)

5.
two seconds later
![image](https://github.com/znuny/Znuny/assets/153006091/368297ff-5202-46c8-afe5-6996c1b059ba)

But the mentions are not removed.

**Comment by rkaldung** [comment]
@aengelha-plano This looks like the issue https://github.com/znuny/Znuny/pull/295 that is fixed in the latest available version of Znuny LTS (6.5.4). 
The version you use, 6.4.5, is already end-of-life and not supported anymore. I recommend updating your system to solve this issue.
