### ISSUE TITLE
Bug - Error in Daemon Scheduler Task Worker (Task: PluginAsynchronous::ConcurrentUser)

### ISSUE THREAD

**Issue by mo-azfar** [znuny/Znuny#524]
### Environment

- Server OS: Ubuntu 22
- Browser: Brave / Edge
- Znuny version: 7.0.12, 7.0.13, 7.0.14

### Expected behavior

No error in Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker

### Actual behavior

In every some hour, system log reported 

Znuny-znuny.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker-88 - 

Could not create a new object Kernel::System::SupportDataCollector::PluginAsynchronous::OTRS::ConcurrentUsers! - Task: PluginAsynchronous::ConcurrentUser

![image](https://github.com/znuny/Znuny/assets/62957738/c42b978a-b91d-468d-b52e-53af26156307)

### Additional information

This due the scheduler called plugin **OTRS::ConcurrentUsers** while i believe it supposed to be **Znuny::ConcurrentUsers** 

![image](https://github.com/znuny/Znuny/assets/62957738/9f6881e0-a77e-4e3d-b212-92a78cad8b59)

### Files

https://github.com/znuny/Znuny/blob/48a4ccbbbd2959c1e467aecb6fa625a810275990/Kernel/System/Web/InterfaceAgent.pm#L393

https://github.com/znuny/Znuny/blob/48a4ccbbbd2959c1e467aecb6fa625a810275990/Kernel/System/Web/InterfaceCustomer.pm#L395

**Comment by rkaldung** [comment]
Internal issue 797
