### ISSUE TITLE
Bug - Overall extremely slow load times with ckeditor 4.22.1 included in Znuny 6.5.5

### ISSUE THREAD

**Issue by meisterheister** [znuny/Znuny#533]
### Environment

- Server OS: Ubuntu 20.4 LTS
- Browser: Chrome
- Znuny version: 6.5.5

### Expected behavior

After updating from Znuny 6.5.4 to 6.5.5 the newer ckeditor 4.22.1 does not affect system performance.

### Actual behavior

Overall System performace is very slow. Ckeditor and plugins are causing the issue according to the web browser dev tools.

### How to reproduce

1. Setup Znuny 6.5.5. and add the old ckeditor 4.17.1 from Znuny release 6.5.4 to var/httpd/htdocs/js/thirdparty
2. Browse to _/index.pl?Action=AgentTicketPhone_ and wait till loading is complete. Notice also general slow load time e.g. on the Dashboard. The main menu is taking time to be shown.
3. Now alter the system configuration to use the older ckeditor in `Frontend::RichText::Path`, `Loader::Agent::CommonJS###100-CKEditor`, `Loader::Customer::CommonJS###100-CKEditor`.
4. Load times are good again.

### Screenshots

**ckeditor 4.17.1**

<img width="743" alt="ckeditor4 17 1" src="https://github.com/znuny/Znuny/assets/35762852/79825c2b-39c4-49f1-adb6-2e3b212d8aaa">

**ckeditor 4.22.1**
<img width="848" alt="ckeditor4 22 1" src="https://github.com/znuny/Znuny/assets/35762852/20594196-8e4d-487a-9a45-846fef33e1b0">

**Comment by hanneshal** [comment]
Hi @meisterheister,

thanks for the report. We appreciate it. 
we can reproduce this behaviour and in fact are working on this. 
The files should be bundled and minified, but they aren't.

One thing to note: you should check your webserver config. Those load times are way to high:
Sample for a regular hosted instance. 

<img width="714" alt="image" src="https://github.com/znuny/Znuny/assets/804939/703ed71e-2dd7-470a-b9d0-9f0c5ba52c31">

Load time with disabled cache is 1.5 sec on version 6.5.5 (release) - even with this bug. 
Thats why it was not caught by the CI. 

We get back when it is fixed.

Johannes

**Comment by jepf** [comment]
Internal issue 809.

**Comment by meisterheister** [comment]
> Hi @meisterheister,
> 
> thanks for the report. We appreciate it. we can reproduce this behaviour and in fact are working on this. The files should be bundled and minified, but they aren't.
> 
> One thing to note: you should check your webserver config. Those load times are way to high: Sample for a regular hosted instance.
> 
> <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/804939/297438689-703ed71e-2dd7-470a-b9d0-9f0c5ba52c31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTE3MzEsIm5iZiI6MTcwNTY1MTQzMSwicGF0aCI6Ii84MDQ5MzkvMjk3NDM4Njg5LTcwM2VkNzFlLTJkZDctNDcwYS1iOWQwLTlmMGM1YmE1MmMzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwODAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Mzg0YWM2ODI2Y2NiMjNlYWM4M2YxNTYzZTkyNWE5NmY2ODdhYTNiMzdlZTJlZWU1NGUwYTcwOWM4OTFmODQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2ZCQ0qVYQcv1O7PQ4o053wAnq0Id40_oogroyCSWbwc">
> Load time with disabled cache is 1.5 sec on version 6.5.5 (release) - even with this bug. Thats why it was not caught by the CI.
> 
> We get back when it is fixed.
> 
> Johannes

Hi Johannes, thanks for the clarification!
I have disabled `Loader::Enabled::JS` setting in sysconfig when capturing web browser logs but as you say it's not getting minified and there is no load time difference even if I have enabled the setting.
As you can see in the screenshots it's much faster with ckeditor 4.17.1 and I really only change the editor so normally it's a good performance overall.

Regards
Rick

**Comment by hrobayo** [comment]
Hi @meisterheister , following you workarround, usign CKEditor 6.17.1 and updating Frontend::RichText::Path, Loader::Agent::CommonJS###100-CKEditor, Loader::Customer::CommonJS###100-CKEditor , and finnaly replacing Core.UI.RichTextEditor.js with version from 6.5.4, load times are better, but with Loader::Enabled::JS enabled, shows javascript errors.
,
![image](https://github.com/znuny/Znuny/assets/6777410/bc6b0bb0-369c-4693-990d-520c7a27bb04)

![image](https://github.com/znuny/Znuny/assets/6777410/17414b32-ede2-4517-ac45-7ae0904f5fb9)

The errors are shown in both Agent and Customer Interfaces, is there another change I missing, 

Thanks in advance for your help.

UPDATE

The error was due a custom skin, the property Frontend::RichText::Path change in recent versions, I have the old one Frontend::RichTextPath.

Problem solved, thanks for the hint.



Regards,
Hugo

**Comment by rkaldung** [comment]
This is fixed with the release of Znuny LTS 6.5.6 and Znuny 7.0.15
