### ISSUE TITLE
Bug - Snippet did not have a support for dynamic field tags

### ISSUE THREAD

**Issue by mo-azfar** [znuny/Znuny#537]
### Environment

- Server OS: Ubuntu 22
- Browser: Brave / Chrome
- Znuny version: 7.0.14 / 7.0.15

### Expected behavior

Snippet should have a support for dynamic field tags.

### Actual behavior

Upon created a snippet and use it in note / reply screen, dynamic field value will be blank.

### How to reproduce

1. Go to 'Admin > Templates'
2. Create new Snippet template
3. Add dynamic field tags
4. Assign Snippet to queue.
5. Use Snippet in ticket note / reply.
6. Dynamic field value will be blank in rich text editor.

### Additional information

Snippet setup
<img width="358" alt="image" src="https://github.com/znuny/Znuny/assets/62957738/e36b994a-7d74-4b2e-ac7e-77c0e4a58f3b">

Snippet in rich text editor

<img width="339" alt="image" src="https://github.com/znuny/Znuny/assets/62957738/e822ba95-92ea-4040-86d5-f2a958cd0899">

**Comment by NiklasSchmitt** [comment]
internal issue 834

**Comment by NiklasSchmitt** [comment]
fixed within commits https://github.com/znuny/Znuny/commit/5a748da82805faebccd3f84a3e7f0e6c6afe7524 & https://github.com/znuny/Znuny/commit/252d0afc5de411bccb14c01fe85e3542f1156df8.
