### ISSUE TITLE
Bug - closing comment tag is missing in header

### ISSUE THREAD

**Issue by Mielai1l** [znuny/Znuny#539]
### Environment

- Server OS: unkown, not relevant
- Browser: Chromium, Firefox, seems not relevant
- Znuny version: 7.0 

### Expected behavior

The html comment should be enclosed with both a starting and closing tag 

### Actual behavior

The html comment in the header of the code is not closed.

### How to reproduce

1. Visit a znuny website such as https://preview.znuny.rocks/znuny/index.pl
2. Use the 'view source' option of your browser
3. Look at the first lines of the codes
4. See that the code lacks a closing comment tag for the line with the znuny copyright.

```
<!DOCTYPE html>
<html>
<!--                                                                           -->
<!--        Znuny: Copyright (C) 2021 Znuny GmbH, https://znuny.org/
<!--        OTRS: Copyright (C) 2001-2021 OTRS AG, https://otrs.com/           -->
<!--    GNU General Public License: https://www.gnu.org/licenses/gpl-3.0.txt   -->
<!--                                                                           -->
```

### Additional information

Due to this, the code can not be validated, see https://validator.w3.org/nu/?doc=https%3A%2F%2Fpreview.znuny.rocks%2Fznuny%2Findex.pl%3F

Other [publicly accessible znuny sites, as found by Shodan](https://www.shodan.io/search?query=znuny) show the same error.
Such as https://servicedesk.roteskreuz-tirol.at/, according to shodan running "X-Powered-By: Znuny 6.5.5"
However https://rechnung.intebit.de/otrs/index.pl has not that problem and is using "X-Powered-By: Znuny LTS 6.0.34" according to shodan.

### Screenshots

-- no screenshot added--

**Comment by NiklasSchmitt** [comment]
Hi @Mielai1l, thanks for your request.

The issue with the mentioned html comment was already reported and is fixed within the next Znuny versions 6.5.7 and 7.0.16.

See commits https://github.com/znuny/Znuny/commit/1a9d935db8319a65e646cd8a45af2dfd2eb6e89f & https://github.com/znuny/Znuny/commit/9c104dd423d1cfe1b2286ca612bf917abea75af6 for Znuny 7
See commits https://github.com/znuny/Znuny/commit/faf518cebcc9ecd0a9094696123b1b5224242ca6 & https://github.com/znuny/Znuny/commit/7eb99a043b3107a9cbd5aa23a9440c4943fcf821 for Znuny 6.5

Best,
Niklas
