### ISSUE TITLE
Bug - Conflicting uses of $DBObject in CustomerUser/CustomerCompany detail searches

### ISSUE THREAD

**Issue by mvorl** [znuny/Znuny#540]
In the routines CustomerSearchDetail() in Kernel/System/CustomerUser/DB.pm and CustomerCompanySearchDetail() in Kernel/System/CustomerCompany/DB.pm, a single $DBObject is used to query dynamic fields and the CustomerUser/CustomerCompany databases. This leads to conflicts when using external databases for CustomerUser/CustomerCompany.

The proposed patch (against the dev branch) uses the $DBObject initialized from $Kernel::OM->Get('Kernel::System::DB') for the dynamic field queries, and $Self->{DBObject} for querying the CustomerUser/CustomerCompany databases.

[DBObject.patch](https://github.com/znuny/Znuny/files/14341510/DBObject.patch)

**Comment by NiklasSchmitt** [comment]
internal issue 833

**Comment by NiklasSchmitt** [comment]
fixed within commits https://github.com/znuny/Znuny/commit/0b0bc60f69cbdeb1affd49f127d8c82d0e507ce9 & https://github.com/znuny/Znuny/commit/7d0680c5988422acbe654ef4df6a9a05164c7221.
