### ISSUE TITLE
missed 'keys' or 'values'

### ISSUE THREAD

**Issue by chapov** [znuny/Znuny#542]
https://github.com/znuny/Znuny/blob/831ffdeec75a630e98ee32c06b62bdd20aead61d/Kernel/Output/HTML/TicketOverview/Preview.pm#L280

This is hash iterating. 

Probably missed 'keys' or 'values'

**Comment by NiklasSchmitt** [comment]
you are right, thanks for your hint. But for the next time, please use your issue template ;)

**Comment by NiklasSchmitt** [comment]
fixed within commit https://github.com/znuny/Znuny/commit/122fc1fea3c4e535752083924859b64c5016b5a8 & https://github.com/znuny/Znuny/commit/25b8128e87153649e5dc282e2a2182bcc80fe9ae
