### ISSUE TITLE
Bug - "Edit customer user"- column not shown in AgentCustomerInformationCenter anymore

### ISSUE THREAD

**Issue by tipue-dev** [znuny/Znuny#543]
### Environment

- Server OS: NA
- Browser: NA
- Znuny version: > 7.0.15

### Expected behavior

An agent with the correct access rights should be shown an additional row to edit the customer user in AgentCustomerInformationCenter (CustomerUserList-widget)

Screenshot from a previous version:
![image](https://github.com/znuny/Znuny/assets/80031303/7ddc802f-1bb8-4981-8b7b-ed07e6999020)

### Actual behavior

https://github.com/znuny/Znuny/commit/592e85c0cc9be842c79ebd2ea8a6d1962eea98c8 removed the setting of ```$Self->{EditCustomerPermission}``` from Run() and therefore it is not given to the template ```AgentDashboardCustomerUserList``` anymore, so the row isn't shown.
Currently:
![image](https://github.com/znuny/Znuny/assets/80031303/071a2b62-93fe-45dc-8bf9-4b2d6512d8b6)

### How to reproduce

1. Go to the CustomerInformationCenter as Admin
2. Look at the Customer-User-List
3. See, that the edit row is missing

**Comment by rkaldung** [comment]
@tipue-dev I am not able to confirm this. I tried to verify it with a 7.0.15 and today's rel-7_0-dev branch. The result is the same:
<img width="1499" alt="image" src="https://github.com/znuny/Znuny/assets/378324/066d016a-e924-433e-99e1-15d783cb3f6d">

The edit icon is there, and it works as expected. Is it possible that your customer user data source is read-only?

**Comment by tipue-dev** [comment]
@rkaldung easy to confuse the two. I'm talking about the Customer Information Center. Your Screenshot is from the Customer **User** Information Center.

**Comment by rkaldung** [comment]
@tipue-dev You're right of course.

**Comment by rkaldung** [comment]
Internal Issue 842

**Comment by NiklasSchmitt** [comment]
fixed within commit https://github.com/znuny/Znuny/commit/fb82aacea471b9ffec9fb46dc3e2010e455eeac7.
