### ISSUE TITLE
Bug -  Empty Content-Id<> on mail attachments causes no view of multi attachments with apple mail client 

### ISSUE THREAD

**Issue by darim92** [znuny/Znuny#546]
### Environment

- Server OS:  Linux - Debian 12
- Browser: Firefox
- Znuny version: 6.5.6

### Expected behavior

From znuny redirected e-mails with multi attachments should show all attachments correctly in apple mail client.

### Actual behavior

The apple mail clients shows nothing or a duplicate of the first attachment, if you sent two or more different attachments. The cause could be that znuny adds an empty content-id (if no ids provided) to each attachment before redirecting the mail.

#### Source of the redirected(received by apple mail user) mail with empty content-ids:

MIME-Version: 1.0
Date: Thu, 21 Mar 2024 13:41:01 +0100
Organization: Musterfirma AG 
To: apple@client.de
Subject: WG: [i11#2024032110003504] Content-Id Test
From: "znuny@ticket.de" <znuny@ticket.de>
X-Powered-BY: Znuny (https://www.znuny.com/)
Message-ID: <1711024861.799493.376698246@ticket.office.znuny.de>
X-Mailer: Znuny Mail Service (6.5.6)
In-Reply-To: <5ca1d013-af4a-46bc-a869-df892720f712@client.de>
References: <5ca1d013-af4a-46bc-a869-df892720f712@client.de>
Content-Type: multipart/mixed; boundary="----------=_1711024861-30198-2"

This is a multi-part message in MIME format...

------------=_1711024861-30198-2
Content-Type: text/plain; charset="utf-8"
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

Testmail abcdefg

\---- Weitergeleitete Nachricht von Apple Mail User <apple@client.de> ---

Von: Joe Mustermann <apple@client.de>
An: znuny@ticket.de
Betreff: Content-Id Test
Datum: 21.03.2024 13:40:05

\> Original E-Mail with two attachments
\---- Ende der weitergeleiteten Nachricht ---=

------------=_1711024861-30198-2
Content-Type: text/plain; charset=UTF-8; name="Attachment_1.txt"
Content-Disposition: attachment; filename="Attachment_1.txt"
Content-Transfer-Encoding: 7bit
__Content-ID: <>__

Attachment 1
\------------=_1711024861-30198-2
Content-Type: text/plain; charset=UTF-8; name="Attachment_2.txt"
Content-Disposition: attachment; filename="Attachment_2.txt"
Content-Transfer-Encoding: 7bit
__Content-ID: <>__

Attachment 2
\------------=_1711024861-30198-2--

#### Original E-Mail received by znuny ticket:

Received: from xxxxxxx by
 xxxxx with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) id
 15.1.2507.37 via Mailbox Transport; Thu, 21 Mar 2024 13:40:00 +0100
Received: from xxxxxx by
xxxxxxxx with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) id
 15.1.2507.37; Thu, 21 Mar 2024 13:39:59 +0100
Received: from xxxxx.webpack.hosteurope.de (xxxxx.webpack.hosteurope.de [xxxx])
 (using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
  key-exchange ECDHE (prime256v1) server-signature RSA-PSS (2048 bits) server-digest SHA256)
 (No client certificate requested)
 by xxxxx (Postfix) with ESMTPS id A400B3AF98
 for <xxxxxxx>; Thu, 21 Mar 2024 13:39:59 +0100 (CET)
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=xxxxxx;
  s=he129701; h=Subject:From:To:MIME-Version:Date:Message-ID:Content-Type:From
 :Sender:Reply-To:Subject:Date:Message-ID:To:Cc:MIME-Version:Content-Type:
 Content-Transfer-Encoding:Content-ID:Content-Description:In-Reply-To:
 References; bh=w1jesJcdTVfUt1otwZPyIW5cJXgfoCqunyhcxwwuGLQ=; t=1711024799;
 x=1711456799; b=wGg5G60w+Ea/VI1QtGO81S5RrAPBP63ep13pbE5Ueipf9jSOdoydQSg6mQnzh
 eObseEvhwiq3YGVCkiTGY22WbhRquOXumekV6pMGKDyqQi/dGJSvOa6BCluSQ/uR6BL7sMCFPR+yL
 9poIjgnKmxPXNosRmOENlkgxLe0/P3FHKem41X/pgFup3K6SbvU3FNw/edoRDWOrT4fUIfQP9Glu+
 Q79r63dZwrpFUXPQDrJUz1lLuMOl51j0JCYIJ2GU17BtGhoShIz9FYva1qTSJ/rfp7Kr0fG+vCUkP
 Co9/DFQ8yCmSzu/KAJP/ZUFt/2mHVSVjmDG4YWXAhbnAPoVqSA==;
Received: from [xxxxxxx] (helo=[xxxxx]); authenticated
 by xxxxxx.webpack.hosteurope.de running ExIM with esmtpsa (TLS1.3:ECDHE_RSA_AES_128_GCM_SHA256:128)
 id 1rnHiA-000175-SU; Thu, 21 Mar 2024 13:39:58 +0100
Content-Type: multipart/mixed; boundary="------------EU1sRL7aUwzd0k0cZIOTFFD1"
Message-ID: <5ca1d013-af4a-46bc-a869-df892720f712@xxxxx>
Date: Thu, 21 Mar 2024 13:39:58 +0100
Content-Language: de-DE
To: znuny@ticket.de
From: Max Musstermann <client@apple.de>
Subject: Content-Id Test
X-bounce-key: webpack.hosteurope.de;client@apple.de;1711024799;ed1b7bb2;
X-HE-SMSGID: 1rnHiA-000175-SU
Return-Path: client@apple.de
MIME-Version: 1.0

--------------EU1sRL7aUwzd0k0cZIOTFFD1
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

Original E-Mail with two attachments
--------------EU1sRL7aUwzd0k0cZIOTFFD1
Content-Type: text/plain; charset=UTF-8; name="Attachment 2.txt"
Content-Disposition: attachment; filename="Attachment 2.txt"
Content-Transfer-Encoding: base64

QXR0YWNobWVudCAy

--------------EU1sRL7aUwzd0k0cZIOTFFD1
Content-Type: text/plain; charset=UTF-8; name="Attachment 1.txt"
Content-Disposition: attachment; filename="Attachment 1.txt"
Content-Transfer-Encoding: base64

QXR0YWNobWVudCAx

--------------EU1sRL7aUwzd0k0cZIOTFFD1-- 

### How to reproduce

1. Send E-Mail with two or more attachments to znuny
2. Redirect received e-mail and view mail with a apple mail client
3. Multi Attachments will not be displayed correctly

Workaround: detach and reattach files before redirecting the mail to apple mail client.

### Additional information

Outlook and Thunderbird seems not to have that problem. Even after redirecting the mail again from apple mail client.

**Comment by rkaldung** [comment]
@darim92 I was not able to reproduce this. I forwarded (that's you redirect, right?) an email with 3 attachments (txt, pdf and image) to an account the is used with the Appe Mail App. Neither the desktop application (Mail App of Sonoma 14.4) nor the Mail App on iOS had issues with this email.
Is it possible that you provide us the source email?

**Comment by darim92** [comment]
@rkaldung yes i can provide the source. Can I mail it to you?

It's important that the first e-mail does not have content-ids for its attachments. Only in that case znuny will generate empty content-ids (Content-ID: <>) for all attachments when forwarding the e-mail. If content-ids are present from the source e-mail znuny will take these and the error won't occur. 

We can reproduce it by using Thunderbird to send the first e-mail with three txt files as attachment(No Content-ID in source present) to our znuny instance and the forward the e-mail with znuny to a mac client. You will see that znuny generates three time the same Content-ID: <>. for the attachments.

**Comment by rkaldung** [comment]
> @rkaldung yes i can provide the source. Can I mail it to you?
> 

Yes, it would be great to have the email sent to community@znuny.com with a reference to the issue.

**Comment by darim92** [comment]
> > @rkaldung yes i can provide the source. Can I mail it to you?
> 
> Yes, it would be great to have the email sent to [community@znuny.com](mailto:community@znuny.com) with a reference to the issue.

Sent you an example mail.

**Comment by darim92** [comment]
Some additional info:

If you detach and reattach all attachments before forwarding the e-mail, the contentIDs for all attachments will be generated properly

**Comment by dignin** [comment]
@darim92 after testing with you, we cannot reproduce the issue. I recommend looking outside the application for possible errors, and updating the system. We wish you luck.
