### ISSUE TITLE
Bug - Tooltip for some columns in TicketGeneric widget of Dashboard is not translated

### ISSUE THREAD

**Issue by BuilderNSV** [znuny/Znuny#563]
### Environment

- Server OS: Linux Ubuntu 22.04
- Browser: Firefox
- Znuny version: 7.0.17

### Expected behavior

Tooltips for columns in Dashboard should be translated

### Actual behavior

For now, there is exist set of columns which has special translation mapping. I mean Kernel/Output/HTML/Dashboard/TicketGeneric.pm file and $TranslatedWord variable at line 1237.
Names of columns are translated perfectly because they are depended on $FilterTitle variable but names of tooltips keep their untranslated form because they are depended on $Title variable which also should have the same translation mapping.

### How to reproduce

1. Use language different from 'en' (English)
2. Go to Dashboard, TicketGeneric widget
2. Choose 'CustomerName' column in widgets parameters to show it.
3. See that name of CustomerName column is translated
4. Move cursor over column title and see that tootip is remained 'CustomerName'

**Comment by NiklasSchmitt** [comment]
I can reproduce this, thank you for your report.

Internal issue: 904

**Comment by NiklasSchmitt** [comment]
fixed in the upcoming versions of Znuny 6.5.10 and Znuny 7.1.1.
