### ISSUE TITLE
Bug - Last Mentions widget ignores date format

### ISSUE THREAD

**Issue by jtrumm** [znuny/Znuny#569]
### Environment

- Server OS: Debian 11 
- Browser: Firefox, Chrome
- Znuny version: 6.5.3 and 7.0.x (checked on https://preview.znuny.rocks for version 7) 

### Expected behavior

The "Last Mentions" dashboard widget applies the date formatting and time zone conversion, based on the language and time zone selection in the user profile, to the "LASTMENTION" column like the other dashboard widgets (e.g. "Open Tickets" and pages (e.g. "Status View") in the system.

### Actual behavior

The "Last Mentions" dashboard widget always shows the value in the column "LASTMENTION" formatted as yyyy-mm-dd hh:mm:ss and shows the value in UTC timezone. The date format, based on the language and time zone selection in the user profile, are ignored. See attached screenshots.

### How to reproduce

1. Login to Znuny and open the user profile (Personal Preferences -> User Profile)
2. Select a language which has a different date format then yyyy-mm-dd, e.g. "English (United Kingdom)", and select a time zone different from UTC, e.g. "Europe/Berlin". Save the settings.
3. Open the Znuny Dashboard and make sure the "Last Mentions" dashboard widget is visible
4. Use the widget specific settings to make the CHANGED and CREATED columns visible for the "Last Mentions" widget and on any other widget.
5. Make sure that the current user is mentioned in a ticket at least once and can at least see one ticket in a dashboard widget different from "Last Mentions", e.g. in "Open Tickets"
6. Observe that the date format in column "LASTMENTION" of the "Last Mentions" widget is different from the format of "CHANGED" or "CREATED" within the "Last Mentions" widget and also compared to other widgets. Additionally the timestamp is displayed in UTC time zone instead of the selected user time zone.

### Screenshots

**Date Format not Applied**
![Last Mention Date Format](https://github.com/znuny/Znuny/assets/5574410/a9f2eb74-90b2-4ab8-b98d-2d24546700e3)

**Time Zone not Applied**
![Last Mention Time Zone](https://github.com/znuny/Znuny/assets/5574410/6857ac01-a8e4-4883-b26a-b24e8d1407b8)

**Comment by rkaldung** [comment]
Internal issue 903

**Comment by rkaldung** [comment]
Fixed with Znuny LTS 6.5.10 and Znuny 7.1.1
