### ISSUE TITLE
No admin rights

### ISSUE THREAD

**Issue by maljes** [znuny/Znuny#58]
### Environment

- OS: Ubuntu 20.04
- Browser: Safari 14.0.3
- Znuny version: 6.0.33

### Expected behaviour

I have freshly installed Znuny on my system using the OTRS instructions. After the installation I received my root password and logged into the backend. Now I wanted to create a new user to not have to work with the super user.

### Actual behaviour

Unfortunately I only get the answer "You don't have permission to use this module!". A look into the database shows that no table with the name "groups", as in older installations, was created. I also tried to create a group via the CLI, but only get the error listed below.

### How to reproduce

1. Install Znuny from latest release
2. Login with root user
3. Click on alert on the top

### Screenshots

```console
root@ubuntu:/opt/otrs/bin# sudo -su otrs ./otrs.Console.pl Admin::Group::Add --name "IT-Support"
Creating a new group...
[Thu Apr 15 14:01:37 2021] otrs.Console.pl: DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups (name, comments, valid_id,  create_time, create_by, change_time, change_b' at line 1 at /opt/Znuny-rel-6_0_33/Kernel/System/DB.pm line 470.
ERROR: OTRS-otrs.Console.pl-Admin::Group::Add-72 Perl: 5.30.0 OS: linux Time: Thu Apr 15 12:01:38 2021

 Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups (name, comments, valid_id,  create_time, create_by, change_time, change_b' at line 1, SQL: 'INSERT INTO groups (name, comments, valid_id,  create_time, create_by, change_time, change_by) VALUES (?, ?, ?, '2021-04-15 12:01:37', ?, '2021-04-15 12:01:37', ?)'

 Traceback (9392):
   Module: Kernel::System::Group::GroupAdd Line: 136
   Module: Kernel::System::Console::Command::Admin::Group::Add::Run Line: 47
   Module: (eval) Line: 461
   Module: Kernel::System::Console::BaseCommand::Execute Line: 455
   Module: Kernel::System::Console::InterfaceConsole::Run Line: 80
   Module: ./otrs.Console.pl Line: 36

Error: Can't create group.
```

![Screenshot Error](https://user-images.githubusercontent.com/9256700/114868237-fd784c80-9df5-11eb-8872-6dee64d919a3.png)

**Comment by rkaldung** [comment]
Hi,

I suggest that you use MySQL 8? This version was not supported by OTRS 6 and is not support by Znuny LTS 6. See also #41

**Comment by rkaldung** [comment]
MySQL 8 is on the roadmap for upcoming feature releases.
