### ISSUE TITLE
Info - Znuny 7.1.2 No packages found in Freebie Features repo

### ISSUE THREAD

**Issue by bloodysneaker** [znuny/Znuny#582]
Hi,
just a reassurance: is it normal that the new znuny release won't find any packages on the repo, right?
I suspect that it checks the <Framework> field of otrs.xml since the max value I found is <Framework>7.0.x</Framework>
Thank you for your patience and sorry for the dumb question

**Comment by rkaldung** [comment]
Hi @bloodysneaker,

No dump question. The packages are in QA right now and I expect most of them to be released in the next two weeks.

**Comment by rkaldung** [comment]
The first packages are already available and the rest is coming one by one. The QA takes some time, please be patient.
