### ISSUE TITLE
Bug - Getting email and notifications when Follow up Option is set to reject

### ISSUE THREAD

**Issue by kersten-lohmeyer** [znuny/Znuny#585]
- Server OS: Debian 12
- Browser: Chrome (latest version on macOS)
- Znuny version: 7.1.2

I set the junk queue follow up option to reject but when I close a ticket in this queue and there's a follow up then I get an email and a notification about that (junk is not in "my queues"). The ticket is not being opened again, that's fine, but I'd also rather not get bothered about follow ups. Is that intended behaviour?

<img width="519" alt="image" src="https://github.com/user-attachments/assets/0e699377-da62-49bf-99ea-6ef708348b9b">

**Comment by hanneshal** [comment]
Hi,

the setting you are referring to is only valid for E-Mail follow ups. 
If there is a follow up via the customer interface, it wont work. 

You can check the communication log for this ticket and check which filter and follow up options have been triggerd.
Also the history might hint why this has happend.

So please post both and we can check it.

Thanks


a note:
If you think this is a bug, please follow the template and do not delete the contents of it. If you want to ask questions please try to use the forum or the discord.
We only handle issues / bugs here.

**Comment by kersten-lohmeyer** [comment]
This is an E-Mail follow up because we don't use the customer interface.

**Comment by hanneshal** [comment]
Then please provide the requested logs/history and we will have a look.

**Comment by kersten-lohmeyer** [comment]
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/0d64dd67-11b0-4071-9eb2-ee0afbe5ec98">
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/10a936c2-e468-4365-a65b-c0872fb79152">

**Comment by kersten-lohmeyer** [comment]
1 |   | Kernel::System::PostMaster | Delivered-To: info@xxx.de | 07/30/2024 12:46:15
-- | -- | -- | -- | --
2 |   | Kernel::System::PostMaster | From: Mark Brown <Brown.mark321@outlook.com> | 07/30/2024 12:46:15
3 |   | Kernel::System::PostMaster | In-Reply-To: <SEZPR01MB45274EF2FA86E7B7C0B05ADCB1B72@SEZPR01MB4527.apcprd01.prod.exchangelabs.com> | 07/30/2024 12:46:15
4 |   | Kernel::System::PostMaster | Message-ID: <SI2PR01MB4524844AB2FA1CDCFCAE3E6FB1B02@SI2PR01MB4524.apcprd01.prod.exchangelabs.com> | 07/30/2024 12:46:15
5 |   | Kernel::System::PostMaster | Message-Id: <SI2PR01MB4524844AB2FA1CDCFCAE3E6FB1B02@SI2PR01MB4524.apcprd01.prod.exchangelabs.com> | 07/30/2024 12:46:15
6 |   | Kernel::System::PostMaster | References: <SEZPR01MB45274EF2FA86E7B7C0B05ADCB1B72@SEZPR01MB4527.apcprd01.prod.exchangelabs.com> | 07/30/2024 12:46:15
7 |   | Kernel::System::PostMaster | Return-Path: <Brown.mark321@outlook.com> | 07/30/2024 12:46:15
8 |   | Kernel::System::PostMaster | Subject: Re: Any change? | 07/30/2024 12:46:15
9 |   | Kernel::System::PostMaster | To: Mark Brown <Brown.mark321@outlook.com> | 07/30/2024 12:46:15
10 |   | Kernel::System::PostMaster | X-Spam-Flag: NO | 07/30/2024 12:46:15
11 |   | Kernel::System::PostMaster | X-Spam-Level: ** | 07/30/2024 12:46:15
12 |   | Kernel::System::PostMaster | X-Spam-Status: No, score=2.582 tagged_above=2 required=6.2 tests=[BAYES_60=2.2, BOGO_UNSURE=0.1, BOTE_UNSURE=0.01, BT_05=-0.01, DKIM_SIGNED=0.1, DKIM_VALID=-0.01, DKIM_VALID_AU=-0.01, DKIM_VALID_EF=-0.01, DMARC_PASS=-0.01, FREEMAIL_ENVFROM_END_DIGIT=0.25, FREEMAIL_FROM=0.001, HTML_MESSAGE=0.001, RCVD_IN_MSPIKE_H2=-0.01, SPF_HELO_PASS=-0.01, SPF_PASS=-0.01] autolearn=disabled | 07/30/2024 12:46:15
13 |   | Kernel::System::PostMaster::FollowUpCheck::BounceEmail | Searching for header X-OTRS-Bounce. | 07/30/2024 12:46:15
14 |   | Kernel::System::PostMaster::FollowUpCheck::Subject | Searching for TicketNumber in email subject. | 07/30/2024 12:46:15
15 |   | Kernel::System::PostMaster::FollowUpCheck::References | Searching for TicketID in email references. | 07/30/2024 12:46:15
16 |   | Kernel::System::PostMaster::FollowUpCheck::References | Found valid TicketID '183380' in email references. | 07/30/2024 12:46:15
17 |   | Kernel::System::PostMaster | Found follow up ticket with TicketNumber '2024072910001806' and TicketID '183380'. | 07/30/2024 12:46:15
18 |   | Kernel::System::PostMaster::Filter::DetectBounceEmail | Checking if is a Bounce e-mail. | 07/30/2024 12:46:15
19 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: '001 - Auto (Header)' '' =~ /auto-replied (vacation)/i matched NOT! | 07/30/2024 12:46:15
20 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: '002 - Auto (Betreff)' 'Re: Any change?' =~ /^Auto:\s/i matched NOT! | 07/30/2024 12:46:15
21 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: '003 - References' '<SEZPR01MB45274EF2FA86E7B7C0B05ADCB1B72@SEZPR01MB4527.apcprd01.prod.exchangelabs.com>' =~ /xxx.de/i matched NOT! | 07/30/2024 12:46:15
22 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: '004 - FollowUp - Junk' '' =~ /Junk/i matched NOT! | 07/30/2024 12:46:15
23 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'Are you interested' 'Hello, Hope your day is off to a good start. Looking to boost your business? I'd be happy to send you a proposal. Best regards, ________________________________ From: Mark Brown Sent: Monday, July 29, 2024 8:31 PM Subject: See a Quick Return on Your SEO Investment@@ Hi there, After reviewing your website, I’ve identified several opportunities to improve its search engine results and overall performance. With your permission, I’d like to prepare an audit report that includes detailed recommendations and pricing information for these improvements. Would you like to proceed? Share your target location, and I’ll include the relevant pricing. Thank you, SEO Consultant ' =~ /interested in acquiring the/i matched NOT! | 07/30/2024 12:46:15
24 |   | Kernel::System::PostMaster::Filter::MatchDBSource | successful Filter: 'Career Service' 'Mark Brown <Brown.mark321@outlook.com>' =~ /^((?!@stud\.xxx\.de).)*$/i ! | 07/30/2024 12:46:15
25 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'Career Service' 'Mark Brown <Brown.mark321@outlook.com>' =~ /career-service@xxx.de/i matched NOT! | 07/30/2024 12:46:15
26 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'Spam-Flag' 'NO' =~ /YES/i matched NOT! | 07/30/2024 12:46:15
27 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'Spam-Level' '**' =~ /^\*{3,}/i matched NOT! | 07/30/2024 12:46:15
28 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'Weiterbildung' 'Re: Any change?' =~ /DIMT Kontaktformular/i matched NOT! | 07/30/2024 12:46:15
29 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'Weiterbildung' 'Mark Brown <Brown.mark321@outlook.com>' =~ /weiterbildung@xxx.de/i matched NOT! | 07/30/2024 12:46:15
30 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'denis4@hotmail.fr' 'Mark Brown <Brown.mark321@outlook.com>' =~ /denis4@hotmail.fr/i matched NOT! | 07/30/2024 12:46:15
31 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'proofpoint-support.us' 'Mark Brown <Brown.mark321@outlook.com>' =~ /info@proofpoint-support.us/i matched NOT! | 07/30/2024 12:46:15
32 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'sales@dipnom.net' 'Mark Brown <Brown.mark321@outlook.com>' =~ /sales@dipnom.net/i matched NOT! | 07/30/2024 12:46:15
33 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'service@smtp-a.robben-medical.de' 'Mark Brown <Brown.mark321@outlook.com>' =~ /service@smtp-a.robben-medical.de/i matched NOT! | 07/30/2024 12:46:15
34 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'studierendenservice@leuphana.de' 'Mark Brown <Brown.mark321@outlook.com>' =~ /studierendenservice@leuphana.de/i matched NOT! | 07/30/2024 12:46:15
35 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'undelivered mail' 'Re: Any change?' =~ /Undelivered Mail Returned to Sender/i matched NOT! | 07/30/2024 12:46:15
36 |   | Kernel::System::PostMaster::Filter::MatchDBSource | Filter: 'yahoo' 'Re: Any change?' =~ /Delayed Mail (still being retried)/i matched NOT! | 07/30/2024 12:46:15
37 |   | Kernel::System::PostMaster::FollowUpCheck::BounceEmail | Searching for header X-OTRS-Bounce. | 07/30/2024 12:46:15
38 |   | Kernel::System::PostMaster::FollowUpCheck::Subject | Searching for TicketNumber in email subject. | 07/30/2024 12:46:15
39 |   | Kernel::System::PostMaster::FollowUpCheck::References | Searching for TicketID in email references. | 07/30/2024 12:46:15
40 |   | Kernel::System::PostMaster::FollowUpCheck::References | Found valid TicketID '183380' in email references. | 07/30/2024 12:46:15
41 |   | Kernel::System::PostMaster | Found follow up ticket with TicketNumber '2024072910001806' and TicketID '183380'. | 07/30/2024 12:46:15
42 |   | Kernel::System::PostMaster | Follow up for [2024072910001806] but follow up not possible. Follow up rejected. | 07/30/2024 12:46:15
43 |   | Kernel::System::PostMaster::Reject | Going to create new article for TicketID '183380'. | 07/30/2024 12:46:15
44 |   | Kernel::System::PostMaster::Reject | Reject Follow up Ticket! | 07/30/2024 12:46:15
45 |   | Kernel::System::PostMaster::Reject | Charset: utf-8 | 07/30/2024 12:46:15
46 |   | Kernel::System::PostMaster::Reject | Content-Type: text/plain; charset=utf-8 | 07/30/2024 12:46:15
47 |   | Kernel::System::PostMaster::Reject | Delivered-To: info@xxx.de | 07/30/2024 12:46:15
48 |   | Kernel::System::PostMaster::Reject | From: Mark Brown <Brown.mark321@outlook.com> | 07/30/2024 12:46:15
49 |   | Kernel::System::PostMaster::Reject | In-Reply-To: <SEZPR01MB45274EF2FA86E7B7C0B05ADCB1B72@SEZPR01MB4527.apcprd01.prod.exchangelabs.com> | 07/30/2024 12:46:15
50 |   | Kernel::System::PostMaster::Reject | Message-ID: <SI2PR01MB4524844AB2FA1CDCFCAE3E6FB1B02@SI2PR01MB4524.apcprd01.prod.exchangelabs.com> | 07/30/2024 12:46:15
51 |   | Kernel::System::PostMaster::Reject | Message-Id: <SI2PR01MB4524844AB2FA1CDCFCAE3E6FB1B02@SI2PR01MB4524.apcprd01.prod.exchangelabs.com> | 07/30/2024 12:46:15
52 |   | Kernel::System::PostMaster::Reject | References: <SEZPR01MB45274EF2FA86E7B7C0B05ADCB1B72@SEZPR01MB4527.apcprd01.prod.exchangelabs.com> | 07/30/2024 12:46:15
53 |   | Kernel::System::PostMaster::Reject | Return-Path: <Brown.mark321@outlook.com> | 07/30/2024 12:46:15
54 |   | Kernel::System::PostMaster::Reject | Subject: Re: Any change? | 07/30/2024 12:46:15
55 |   | Kernel::System::PostMaster::Reject | To: Mark Brown <Brown.mark321@outlook.com> | 07/30/2024 12:46:15
56 |   | Kernel::System::PostMaster::Reject | X-OTRS-AttachmentCount: 0 | 07/30/2024 12:46:15
57 |   | Kernel::System::PostMaster::Reject | X-OTRS-AttachmentExists: no | 07/30/2024 12:46:15
58 |   | Kernel::System::PostMaster::Reject | X-OTRS-FollowUp-IsVisibleForCustomer: 1 | 07/30/2024 12:46:15
59 |   | Kernel::System::PostMaster::Reject | X-OTRS-FollowUp-SenderType: customer | 07/30/2024 12:46:15
60 |   | Kernel::System::PostMaster::Reject | X-OTRS-IsVisibleForCustomer: 1 | 07/30/2024 12:46:15
61 |   | Kernel::System::PostMaster::Reject | X-OTRS-SenderType: customer | 07/30/2024 12:46:15
62 |   | Kernel::System::PostMaster::Reject | X-Sender: Brown.mark321@outlook.com | 07/30/2024 12:46:15
63 |   | Kernel::System::PostMaster::Reject | X-Spam-Flag: NO | 07/30/2024 12:46:15
64 |   | Kernel::System::PostMaster::Reject | X-Spam-Level: ** | 07/30/2024 12:46:15
65 |   | Kernel::System::PostMaster::Reject | X-Spam-Status: No, score=2.582 tagged_above=2 required=6.2 tests=[BAYES_60=2.2, BOGO_UNSURE=0.1, BOTE_UNSURE=0.01, BT_05=-0.01, DKIM_SIGNED=0.1, DKIM_VALID=-0.01, DKIM_VALID_AU=-0.01, DKIM_VALID_EF=-0.01, DMARC_PASS=-0.01, FREEMAIL_ENVFROM_END_DIGIT=0.25, FREEMAIL_FROM=0.001, HTML_MESSAGE=0.001, RCVD_IN_MSPIKE_H2=-0.01, SPF_HELO_PASS=-0.01, SPF_PASS=-0.01] autolearn=disabled | 07/30/2024 12:46:15
66 |   | Kernel::System::PostMaster::Reject | Reject FollowUp Article to Ticket [2024072910001806] created (TicketID=183380, ArticleID=674311). Follow up rejected. | 07/30/2024 12:46:15

**Comment by hanneshal** [comment]
OK, so the system works exactly as it should. You can see that the reject is properly noted.

The article is added, the state is unchanged -> Which is the important part
and a rejection note would be sent, if configured. 

If you do not want update notification for closed tickets, you need to modify the notification for follow ups and restrict it to specific states / queues.

**Comment by kersten-lohmeyer** [comment]
Ok, thank you. I already tried a few things but nothing seemed to work so I thought this might be a bug.
