### ISSUE TITLE
Firefox - Android - Font rendering problem on mobile 

### ISSUE THREAD

**Issue by DenisTNK2** [znuny/Znuny#590]
![Screenshot_20240831_182059_Firefox](https://github.com/user-attachments/assets/73976981-902a-48bc-9b05-49308842dc97)
![Screenshot_20240831_182047_Firefox](https://github.com/user-attachments/assets/249564d1-3c9f-407b-813a-4cd617936381)

See attached screenshots - Android - Samsung S22 - Firefox

DigitalType display is squashed

Font of Safety Score pretty small in comparison with the rest of the text

**Comment by hanneshal** [comment]
@DenisTNK2 please check if this is the propper screenshot. I do not see any Znuny related informations.
Also please do not delete the issue template. This is there for a reason and we do not work on non compliant issues.

regards
