### ISSUE TITLE
Error - Account Creation - Windows 11 - Chrome 

### ISSUE THREAD

**Issue by DenisTNK2** [znuny/Znuny#591]
Unable to create a new sign up account using a new email address that I have previously not used

Surface 9, Windows 11, Chrome

![image](https://github.com/user-attachments/assets/eab0ab93-c650-435a-81e6-f5eaa919c549)

Error appears top right hand corner

**Comment by hanneshal** [comment]
@DenisTNK2 please check if this is the propper screenshot. I do not see any Znuny related informations.
Also please do not delete the issue template. This is there for a reason and we do not work on non compliant issues.

regards
