### ISSUE TITLE
Bug - Column filter by state does not work if I want to see owned tickets in certain states only

### ISSUE THREAD

**Issue by BuilderNSV** [znuny/Znuny#592]
Environment
- Server OS: Linux
- Browser: Firefox
- Znuny version: 7.1.2

### Expected behavior

The filter for State column on AgentTicketOwnerView screen should filter values if tickets were searched by certain states.

### Actual behavior

The filter for State column on AgentTicketOwnerView screen stops filtering values. Choosing of any state in this filter does take effect - all tickets with states new/open keep showing

### How to reproduce

Prepare several tickets with states 'new' and 'open' and make them owned by yourself.

1. Go to 'AgentTicketOwnerView' screen and see that filter by  State column works as expected.
2. Change code to use States attribute instead of StateType in Search parameters of hash:
    Kernel/Modules/AgentTicketOwnerView.pm, line 176:
```
        All => {
            Name   => Translatable('All'),
            Prio   => 1000,
            Search => {
                StateType  => 'Open',
            ...
```
Replace with 
```
        All => {
            Name   => Translatable('All'),
            Prio   => 1000,
            Search => {
                States     => ['new', 'open' ],
```
3. Go to 'AgentTicketOwnerView' screen and see that filter for State column on AgentTicketOwnerView screen stops filtering values. Choosing of any state in this filter does take effect - all tickets with states new/open keep showing

P.S. This issues does not realted to AgentTicketOwnerView screen only but all '...View' screens where ColumnFilter is used and passed to TicketSearch() function.

**Comment by BuilderNSV** [comment]
I see on this issue one more time and I think solution for this problem will be not trivial. As workaround or the only solution is to use the same attributes in Search and ColumnFilter hashes for the same entity (ex. not to use States but use StateIDs). So when both of them are passed to TicketSearch, attributes of Search hash will be redefined by ColumnFilter one and issue will gone.

**Comment by hanneshal** [comment]
Hi, we discussed this in the team and do not classify this as an issue. 
If you modify the code, you can not expect that your modifications work as you think they will. 

And you are righ, it is a combination of States and StateTypes and when you pass both to the ticket search, it will fail / not show the result you are expecting.

Regards
