### ISSUE TITLE
Bug - Duplicate values in Ticket.xml 'Events###Article'

### ISSUE THREAD

**Issue by BuilderNSV** [znuny/Znuny#594]
### Environment

- Znuny version: 7.1.2

Setting "Events###Article" in Kernel\Config\Files\XML\Ticket.xml has duplicate values "ArticleAgentNotification" and "ArticleCustomerNotification"

**Comment by hanneshal** [comment]
Thanks for the report. we will clean this up in the next release 👍

**Comment by dennykorsukewitz** [comment]
internal Issue: 964

**Comment by eyazi** [comment]
ArticleCustomerNotification still occurs twice.

**Comment by dennykorsukewitz** [comment]
🙇🏼‍♂️  Thanks 😄 😶‍🌫️

**Comment by dennykorsukewitz** [comment]
Fixed https://github.com/znuny/Znuny/commit/5152febd8579ee1dfc9aee296fd7bb3b164fd8bd https://github.com/znuny/Znuny/releases/tag/rel-7_1_3
