### ISSUE TITLE
Bug - [AgentTicketNote -> Add Article -> Text - Text area is disabled]

### ISSUE THREAD

**Issue by sudddy** [znuny/Znuny#595]
### Environment

- Server OS:  MacOs
- Browser:  Chrome
- Znuny version:  6.5.10

### Expected behavior

A visible Text Area on the `Add Note to Ticket` Page on the `Text` field. 

### Actual behavior
Text Area is hidden because of the error in the 

<img width="663" alt="Screenshot 2024-09-16 at 3 06 07 PM" src="https://github.com/user-attachments/assets/42df6bd8-4a43-43ed-8ddb-249dc8a7e9e2">

### How to reproduce

1. Click on the tickets available in the dashboard
2. Inside the ticket summary, click on the `communication` dropdown and select `Note`
3. And, in the Add Note section, you will see the error in the console and in the UI you won't see the TextArea for the field `Text`

### Screenshots
<img width="1483" alt="Screenshot 2024-09-16 at 3 12 08 PM" src="https://github.com/user-attachments/assets/b88bc271-a035-46ac-9c75-5bc530ef00f0">

**Comment by hanneshal** [comment]
Hi @sudddy ,
did you perform an update of Znuny before this error occured? Or did it never work?

Can please try the following:
- Disable the JavaScript Loader > Admin>Sysconfig>Search "Loader::Enabled::JS" [ENTER]
Disable the Loader and reload the ATNote screen
- Post the actual error message 

My guess is, you did a version update and old settings have been keept. You should see a 404 in the network tab. 

Regards
Johannes

**Comment by sudddy** [comment]
![Screenshot 2024-09-17 at 7 06 47 AM](https://github.com/user-attachments/assets/30b79e4e-1d24-42f9-9083-503870916cc4)


Yes, you are right, i did migrate from otrs platform to znuny 6.1 then to the latest version (6.5.10)

**Comment by hanneshal** [comment]
"Perfect" 😄 

Please check the following sysconfigs and reset them:
```
Loader::Agent::CommonJS###100-CKEditor
Loader::Customer::CommonJS###100-CKEditor
Frontend::RichText::Path
```

**Comment by sudddy** [comment]
Great.
Thank you for your prompt response, good day!
