### ISSUE TITLE
Bug - Not required DateTime dynamic field with limitation of date in past blocks note submitting

### ISSUE THREAD

**Issue by BuilderNSV** [znuny/Znuny#596]
### Environment

- Server OS: Linux
- Browser: Firefox
- Znuny version: 7.1.2

### Expected behavior

Note for ticket should be submitted if not required DateTime dynamic field with limitation 'Prevent entry of dates in the past' was not touched on the form

### Actual behavior

DateTime dynamic field with limitation 'Prevent entry of dates in the past' raises error 'Invalid date (need a future date)!' even mark for field activation is not set

### How to reproduce

1. Create a dynamic field (Object type=Ticket, Field Type= Date/Time, Restrict entering of dates='Prevent entry of dates in the past')
2. Link this dynamic field with AgentTicketNote screen as not required
`$Self->{'Ticket::Frontend::AgentTicketNote'}->{'DynamicField'} =  {
  'Test' => '1'
};
`
3. Create a New Phone Ticket
5. Go to Communication -> Note in the created ticket.
6. Fill Subject/Body but don't touch dynamic field and don't activate it with mark (checkbox).
7. Try to submit form and see error 'Invalid date (need a future date)!' on dynamic field.

### Screenshots

![error](https://github.com/user-attachments/assets/b362f2d6-5e35-49fd-b0f9-91e424d66956)

**Comment by rkaldung** [comment]
Internal issue 966

**Comment by jepf** [comment]
@BuilderNSV 

Thanks for reporting 👍
Fix will be part of 7.1.4.

**Comment by dennykorsukewitz** [comment]
https://github.com/znuny/Znuny/commit/782bf39582af7ab13e054ca94dcc9761a1642c75#diff-d975bf659606195d2165918f93e1cf680ef68ea3c9cab994f033705fea8238b2R2
