### ISSUE TITLE
Bug - unable to proceed with installation

### ISSUE THREAD

**Issue by dca00** [znuny/Znuny#597]
### Environment

- Server OS: uname -a
Linux deb12-plane 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Browser: 
- Znuny version: 

### Expected behavior

Should work.

### Actual behavior

Result of database check

Wrong database collation (character_set_database is utf8mb4, but it needs to be utf8).

### How to reproduce

1. Go to 'http://10.10.10.206/znuny/installer.pl'
2. Click on 'accept license'
3. Click on 'Next'
4. Click on 'Check database settings'

### Screenshots

![image](https://github.com/user-attachments/assets/0209b6be-bbd6-4112-bacc-207339e65819)

**Comment by hanneshal** [comment]
Would you be so kind and add you Znuny and DB version to the tag. 
Thanks

**Comment by dca00** [comment]
I do not know what a tag is so here

mariadb --version
mariadb  Ver 15.1 Distrib 10.11.6-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

The znuny version is the latest as of today, and I'd added it to the ticket but it somehow got stripped: 7.0.19

**Comment by hanneshal** [comment]
Hi @dca00,
then it is the correct message. 
The utf8mb4 support is in 7.1 not 7.0 (https://doc.znuny.org/znuny/releases/7_1_1/index.html) 

Regards
Johannes

**Comment by dca00** [comment]
I am excited to learn that the message is correct!
What is the next step that is necessary to arrive at a working instance of Znuny?

**Comment by hanneshal** [comment]
use 7.1 latest, not 7.0 and follow the instructions here
 https://doc.znuny.org/znuny/installation/index.html
 
 Then you should be fine

**Comment by hanneshal** [comment]
Hi @

**Comment by dca00** [comment]
I downloaded https://download.znuny.org/releases/znuny-latest.tar.gz

ls -l znuny-latest.tar.gz 
-rw-r--r-- 1 root root 35751274 Jun 26 04:28 znuny-latest.tar.gz

It extracted znuny-7.0.19 folder.

Is this not the file that your users are supposed to get when they download the latest?

**Comment by hanneshal** [comment]
Please follow the documtentation. Thats why I posted the link.
![image](https://github.com/user-attachments/assets/aad21f47-92df-4c40-aafb-7bad06683e39)

As I see it, is no issue and I will lock this thread.
If you have further question, please move to discord (See link in Readme) or the forum 

https://community.znuny.org/

Regards
Johannes

**Comment by hanneshal** [comment]
Update: the lates package now points to 7.1.x
