### ISSUE TITLE
Bug - unable to proceed with installation

### ISSUE THREAD

**Issue by dca00** [znuny/Znuny#598]
### Environment

- Server OS: uname -a
Linux deb12-plane 6.1.0-25-amd64 https://github.com/znuny/Znuny/pull/1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Browser: Firefox
- Znuny version: 7.1.2

### Expected behavior

Should work

### Actual behavior

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.62 (Debian) Server at 10.10.10.206 Port 80

### How to reproduce

1. Go to 'http://localhost/znuny/installer.pl'
2. See error

### Additional information

I followed your instructions in https://github.com/znuny/Znuny/issues/597 that you hurried to close before I could ask additional questions regarding the recovery from my current situation in which 7.0.19 was installed.
Your instructions did not work right away because the `tar` extraction command is for an older version.
When I extracted the latest version 7.1.2 and recreated the symbolic link `ln -s /opt/znuny-7.1.2/ /opt/znuny` I saw the error in the browser.
Please do not hurry to close issues until the user confirms that they are clear and that there are no further questions. There is nothing to be gained by rushing to close them.

### Screenshots

![image](https://github.com/user-attachments/assets/a3f5b8dd-1ef0-4b35-b44a-c8075a34e033)

**Comment by hanneshal** [comment]
There is in fact a lot. We especially state that this repo is not for Questions. 
This is not a bug in the software. Please move to the proper channels, as stated in my last comment on your last issue.
Thanks.
