### ISSUE TITLE
Screen is garbled on Galaxy S21

### ISSUE THREAD

**Issue by dca00** [znuny/Znuny#600]
### Environment

- Server OS: 
- Browser: Chrome
- Znuny version: 7.1.2

### Expected behavior

Screen should be readable

### Actual behavior

Screen is garbled

### How to reproduce

1. Log in
2. See problem

### Screenshots

![image](https://github.com/user-attachments/assets/d4b21673-fc31-4f13-88cf-10a2f347144b)

**Comment by KaiHerlemann** [comment]
Closed as duplicate to #362.

**Comment by KaiHerlemann** [comment]
Closed as duplicate to https://github.com/znuny/Znuny/issues/362.
