### ISSUE TITLE
Bug - Znuny 7.1.3 shows HTML code when answering or forwarding ticket

### ISSUE THREAD

**Issue by kersten-lohmeyer** [znuny/Znuny#601]
### Environment

- Server OS: Debian 12
- Browser: Chrome, also Firefox
- Znuny version: 7.1.3

### Expected behavior

I expect proper formatted text when answering, not HTML code

### Actual behavior

Text is shown in HTML code (probably CKEditor not loaded)

### How to reproduce

Answer an existing Ticket

### Additional information

Not a fresh install, was updating from 7.1.2

### Screenshots

<img width="1204" alt="Bildschirmfoto 2024-10-06 um 10 03 07" src="https://github.com/user-attachments/assets/16183b42-c6e3-4754-a0c3-abc5be013875">

**Comment by rkaldung** [comment]
@kersten-lohmeyer I tried to verify this but had no success. Here my steps:

1. Install Znuny 7.1.2 w/ MariaDB
2. Create a new template, type Answer
3. Answered a new ticket
4. Updated to Znuny 7.1.3
5. Answered the same ticket again

Everything was displayed as expected.
Please check if it helps to  clean and create the loader cache
```
bin/znuny.Console.pl Maint::Loader::CacheCleanup
bin/znuny.Console.pl Maint::Loader::CacheGenerate
```

**Comment by kersten-lohmeyer** [comment]
> ```
> bin/znuny.Console.pl Maint::Loader::CacheCleanup
> bin/znuny.Console.pl Maint::Loader::CacheGenerate
> ```

Nope, doesn't work. Started with the clean 7.1.3, did not overwrite old 7.1.2 files, deleted everything before. Only restored Config.pm and ZZZAAuto.pm. That's all. Cleared Firefox cache, didn't help. Tried the commands above, didn't help.

No errors in the JS-Console, nothing blocked either.

Is that being changed by the update? If not that's probably why it not works in my case:
<img width="1275" alt="image" src="https://github.com/user-attachments/assets/39e79d41-9313-4d80-9cd4-05aa46468799">

If I change it to the right path it looks like this, even after CacheCleanup and CacheGenerate:
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/0e2c804b-d33f-41de-b4cf-053857c99fbb">

I'm probably doing something stupid here. xD

EDIT: Got it to work. Was just a path issue. Thanks anyway!

**Comment by rkaldung** [comment]
Glad to hear that you've found it.
