### ISSUE TITLE
Bug -> sudo a2enconf zzz_znuny --> leads to: ERROR: Conf zzz_znuny does not exist!

### ISSUE THREAD

**Issue by Tschukedi** [znuny/Znuny#606]
### Environment

- Server OS: 21.10.2024: Ubuntu 24.04.1 LTS noble
- Browser: Chrome
- Znuny version: Latest LTS-Version 6.5.11 / 2024-10-02 --> Cant really say!

### Expected behavior

I expect that the "sudo a2enconf zzz_znuny" should find a config file

### Actual behavior

ERROR: Conf zzz_znuny does not exist!

### How to reproduce

1. Follow instructions on: https://doc.znuny.org/znuny_lts/releases/installupdate/install.html
2. Proceed like in above description
3. trying to get on http://<IP-Host>/otrs/installer.pl --> can not file such file

**Comment by hanneshal** [comment]
Hi @Tschukedi,

you forgot this line:

```
ln -s /opt/otrs/scripts/apache2-httpd.include.conf /etc/apache2/conf-available/zzz_znuny.conf
```
So the file does not exist and cannot be linked.

Note:
You may need to change the path from otrs to znuny.

Please also note: this is more like a question, not an issue with the software itself.
Please use the forum or discord for further question.
Thank you!

Regards 
Johannes

**Comment by Tschukedi** [comment]
Dear @hanneshal ,

I allready tried that and still no fix for this problem.

**Comment by hanneshal** [comment]
Please show an `ls -l` of your /etc/apache2/conf-available folder 
Then we can move on from there.

**Comment by hanneshal** [comment]
@Tschukedi any update on this?

**Comment by sbakhtiar** [comment]
I've run into the same problem. 

`ls -la`

-rw-r--r-- 1 root root  269 Mar 18  2024 charset.conf
-rw-r--r-- 1 root root 3178 Mar 18  2024 localized-error-pages.conf
-rw-r--r-- 1 root root  143 Mar 18  2024 other-vhosts-access-log.conf
-rw-r--r-- 1 root root 1827 Mar 18  2024 security.conf
-rw-r--r-- 1 root root  409 Mar 18  2024 serve-cgi-bin.conf
lrwxrwxrwx 1 root root   44 Nov 12 16:45 zzz_znuny.conf -> /opt/otrs/scripts/apache2-httpd.include.conf

`ls -la /opt/`

drwxr-xr-x  2 root root 4096 Sep 27 08:36 .
drwxr-xr-x 22 root root 4096 Nov 12 16:15 ..

Following the instructions above, otrs is not installed in opt.

**Comment by hanneshal** [comment]
Hi @sbakhtiar 
> Following the instructions above, otrs is not installed in opt.

Where is it installed? And why did you point the symlink to: 
>/opt/otrs/scripts/apache2-httpd.include.conf
?

Regards

**Comment by sbakhtiar** [comment]
> Hi @sbakhtiar
> 
> > Following the instructions above, otrs is not installed in opt.
> 
> Where is it installed? And why did you point the symlink to:
> 
> > /opt/otrs/scripts/apache2-httpd.include.conf
> > ?
> 
> Regards

I followed the installation instructions here:
https://doc.znuny.org/znuny_lts/releases/installupdate/install.html

Under the Webserver condiguration section, under the Ubuntu instructions I copied and pasted this command into the prompt:

'ln -s /opt/otrs/scripts/apache2-httpd.include.conf /etc/apache2/conf-available/zzz_znuny.conf'

I was wondering what step installed znuny, it looks like that step is missing under the Ubuntu instructions?

There is an RPM choice, and a install from source choice. I think the assumption is to install from source on Ubuntu? There is not .pkg?

I'm going to install from source which will definitely install under opt (if I'm ready the instructions correctly).

**Comment by sbakhtiar** [comment]
UPDATE:

I had to run the "Install From Source" section which should be titled "Install From Source / Ubuntu"

Once installed from source I was able to stat the installation process.

**Comment by hanneshal** [comment]
> There is an RPM choice, and a install from source choice. I think the assumption is to install from source on Ubuntu? There is not .pkg?
> 
Correct, debian users should use from source. As they can not use RPMs.

Edit##
As the documentation states, 
```
# Download Znuny
cd /opt
wget https://download.znuny.org/releases/znuny-latest-6.5.tar.gz
# Extract
tar xfz znuny-latest-6.5.tar.gz
# Create a symlink
sudo ln -s /opt/znuny-6.5.10 /opt/otrs
```
Download, Exxtraxt, Symlink. I do not see a way where the doc states "Symlink" without install first.

EditEnd###

The main question is: what version of RPM did you install? 7.x or 6.x 
Or how did you installed it the "first time?".
If you used 7.x then you used the wrong documentation. If you used 6.x then you made an error somewhere.

The RPM for version 7 (non LTS) on Redhat installs on /opt/znuny

The source install path is totall up to you. But the same here: 7 should be in /opt/znuny, < 7 should be /opt/otrs

The source install is not debian specific, so we wont change the name for this.
