### ISSUE TITLE
Bug - 'Use of uninitialized value' warning on build custom package and there are no permissions to write to the target directory

### ISSUE THREAD

**Issue by BuilderNSV** [znuny/Znuny#610]
### Environment

- Server OS: Linux
- Browser: Firefox
- Znuny version: 7.1.3

### Problem description

Error message appears in system log on try to build a package (command `bin/znuny.Console.pl Dev::Package::Build`) and there are no permissions to write to the target directory:

> znuny.Console.pl: Use of uninitialized value $File in concatenation (.) or string at /opt/otrs/Kernel/System/Console/Command/Dev/Package/Build.pm line 133.
> Error: File  could not be written.
> 

$File variable is undefined but used to print error message. I guess $Filename variable should be used instead.

**Comment by hanneshal** [comment]
Hi @BuilderNSV 
can you elaborate this a bit more. 

What parameters have you passed to the call? Are you building a package a package based on a SOPM?
Some more insights would be really helpful. 

Regarding the message. IMHO the error makes sense. 
$File is not the file you passed, but the file the handle created / should create.

<img width="1802" alt="grafik" src="https://github.com/user-attachments/assets/77a61452-3eef-4f00-b953-7291a4f2a676">

Which seems not possible to bad permissions.

**Comment by BuilderNSV** [comment]
Hi @hanneshal.
No need to explain anything deeper. It's enough to take a look on the code - inside `if ( !$File )` it is known for sure that the variable $File is undefined and it is incorrectly use it to print string on line 133.

**Comment by hanneshal** [comment]
Ah, now I see. 
You are right, thanks.

**Comment by dennykorsukewitz** [comment]
internal Issue: 980
