### ISSUE TITLE
Bug - translation of some strings is missed in the code

### ISSUE THREAD

**Issue by BuilderNSV** [znuny/Znuny#615]
### Environment

- Server OS: Linux
- Browser: Firefox
- Znuny version: 7.1.3

I have described all found issues in diff-like format to clear understand what exactly I meant

<details>
<summary>1. There are not all strings are translated in the code</summary>

**`Kernel/Output/HTML/Templates/Standard/AgentDashboardCommon.tt, line 16:`**
`-                <a class="[% Data.ClassDashboardWidgetExpandAll | html %]">All</a>`
`+                <a class="[% Data.ClassDashboardWidgetExpandAll | html %]">[% Translate("All") | html %]</a>`

**`Kernel/Output/HTML/Templates/Standard/Header.tt, line 40:`**
`-                        <label>Account</label>`
`+                        <label>[%Translate("Account") | html %]</label>`

**`Kernel/Output/HTML/Templates/Standard/CustomerHeader.tt, line 46:`**
`-                            <label>Account</label>`
`+                            <label>[% Translate("Account") | html %]</label>`

**`Kernel/Output/HTML/Templates/Standard/CustomerTicketSearch.tt, line 13:`**
`-        <h1 class="PageTitle">Ticket Search</h1>`
`+        <h1 class="PageTitle">[% Translate("Ticket Search") | html %]</h1>`

**`Kernel/Output/HTML/Templates/Standard/CustomerTicketSearch.tt, line 47:`**
`-                        <h2>Template name</h2>`
`+                        <h2>[% Translate("Template name") | html %]</h2>`

**`Kernel/Output/HTML/Templates/Standard/CustomerTicketOverview.tt, line 15:`**
`-        <h1 class="PageTitle">Tickets</h1>`
`+        <h1 class="PageTitle">[% Translate("Tickets") | html %]</h1>`

**`Kernel/Output/HTML/Templates/Standard/CustomerPreferences.tt, line 13:`**
`-    <h1 class="PageTitle">Preferences</h1>`
`+    <h1 class="PageTitle">[% Translate("Preferences") | html %]</h1>`

</details>

<details>
<summary>2. Ticket state value is translated everywhere except output of search results in PDF</summary>

**`Kernel/Modules/CustomerTicketSearch.pm, line 885:`**
`-                push @PDFRow,  $Data{State};`
`+                push @PDFRow,  $LayoutObject->{LanguageObject}->Translate($Data{State});`

**`Kernel/Modules/AgentTicketSearch.pm, line 1131:`**
`-                push @PDFRow,  $Data{State};`
`+                push @PDFRow,  $LayoutObject->{LanguageObject}->Translate($Data{State});`
</details>

And some other minor issues:

<details>
<summary>1. Extra carridge return leads to show "(g)" on a new line</summary>

**`Kernel/Output/HTML/Templates/Standard/AgentDashboardCommon.tt, line 68:`**
`-                        <button class="btn-main btn-primary" accesskey="g" title="[% Translate("Save changes") | html %]`
`-                            (g)" type="submit" value="[% Translate("Save") | html %]">`
`+                        <button class="btn-main btn-primary" accesskey="g" title="[% Translate("Save changes") | html %] (g)" type="submit" value="[% Translate("Save") | html %]">`
</details>

<details>
<summary>2. Strange number 2422 in the header comments of Kernel/GenericInterface/Operation/Ticket/TicketUpdate.pm</summary>

**`Kernel/GenericInterface/Operation/Ticket/TicketUpdate.pm, line 1:`**
`-#2422 --`
`+# --`
</details>

**Comment by dennykorsukewitz** [comment]
internal issue: 987
