### ISSUE TITLE
Bug - Drop-Down menue in the ticket overview can not be collapsed

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/Znuny#619]
### Environment

- Server OS: Debian 12
- Browser: Chrome, Firefox, Edge, perhaps others too
- Znuny version: 7.1.3

### Expected behavior

All drop down menues for showing tickets in the ticket overview
https://myserver/znuny/index.pl?Action=AgentDashboard
should be collapsed by default and it should be able to collapse

![image](https://github.com/user-attachments/assets/c18a0a19-530a-474d-a10c-256b7ebdf950)

Hoovering over the open drop down menue
![image](https://github.com/user-attachments/assets/9313c277-4989-4304-b052-fe4c4548a503)

### Actual behavior

It can not be collapsed

**Comment by schnudd31do3** [comment]
Here it was the same: https://github.com/znuny/Znuny/issues/503

**Comment by hanneshal** [comment]
Hi @schnudd31do3 
I'm not able to reproduce this on a fresh 7.1.x setup. 
Can you provide you package list, maybere there is an error related to a specific package.

Can you reproduce the steps to disable the LS Loader (Loader::Enabled::JS) so that we get the real error message in the browser console.

Regards and thank you
Johannes

**Comment by schnudd31do3** [comment]
- I forgot to say that I upgraded from 7.0.19 to 7.1.3

- Package list:

![image](https://github.com/user-attachments/assets/1448e4f1-4e05-49fd-8a8e-767a06e03d71)
![image](https://github.com/user-attachments/assets/da77c46a-5970-4806-aa41-425c54936f54)
![image](https://github.com/user-attachments/assets/916e232e-2a20-4010-b47f-345f780c387d)

- For testing, I disabled Loader::Enabled::JS with no change (means the error is still there)

- This is the browser console (disabled/enabled Loader::Enabled::JS makes no difference):
![image](https://github.com/user-attachments/assets/b92fd2ff-9062-4d47-bcb2-95cc749d14bd)

**Comment by hanneshal** [comment]
Hi @schnudd31do3 
the loader seems still to be active. Otherwise the ModuleJS file would not be there.
Can you check this again.

Regards

**Comment by schnudd31do3** [comment]
Hi @hanneshal,
I checked it once again:
![image](https://github.com/user-attachments/assets/44107ba4-fa42-494f-a375-9b393f9eeeb1)
Best.

**Comment by hanneshal** [comment]
And the green signals: it is not deployed ;)

**Comment by schnudd31do3** [comment]
Oh man, you are rihgt. I haven't deployed. The error has gone.

**Comment by schnudd31do3** [comment]
Thanhs for your patience / help.
