### ISSUE TITLE
Bug - Log Warning - Use of uninitialized value $_ in array element

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny#63]
### Environment

- OS:           Linux
- Browser:      none
- Znuny version: 6.0.34

### Expected behaviour

No log warning on regular usage

### Actual behaviour

A log warning is created:

```
Use of uninitialized value $_ in array element at /opt/otrs/Kernel/System/SupportDataCollector/PluginAsynchronous/OTRS/ConcurrentUsers.pm line 143.
Use of uninitialized value $_ in array element at /opt/otrs/Kernel/System/SupportDataCollector/PluginAsynchronous/OTRS/ConcurrentUsers.pm line 143.
```

### How to reproduce

Update to 6.0.34, error will occur shortly

### Additional information

The problem was reported by KIT via #1174834 on 22nd of April.
Reason for this Bug is a fix from March were some `$_` variables were cleaned up and renamed. 
It is already fixed with a sub-release 6.0.34-02 . This release is available on the download server from now on. The archives are updated and have the same name, the RPMs have the build number 02 instead of 01.

https://download.znuny.org/releases/

Sorry for the inconvenience 
Your Znuny Team 🚀

**Comment by fedorkotov** [comment]
GitHub Release https://github.com/znuny/Znuny/releases/tag/rel-6_0_34 does not match archive https://download.znuny.org/releases/znuny-6.0.34.tar.gz . This bug is not fixed in GitHub release. Please recreate it or add a new one.
