### ISSUE TITLE
FR: Add note via REST API

### ISSUE THREAD

**Issue by ikreb7** [znuny/Znuny#66]
### Environment

- OS:           any
- Browser:      any
- Znuny version: 6.0.33

### Expected behaviour

We want to add a note with certain additional information to tickets. For this, the REST API would need to be extended. Currently we use pyOTRS for other things. I could extend pyOTRS by myself.

**Comment by rkaldung** [comment]
Hi @ikreb7,

Adding additional information is already possible. What exactly do you need?

**Comment by ikreb7** [comment]
Hi @rkaldung,

I would like to be able to create and read notes from other frontend users.

**Comment by rkaldung** [comment]
@ikreb7 What's a frontend user for you? An agent (param UserLogin) or a customer user (param CustomerUserLogin)?

Agents are able to read and create wherever they have appropriate permission. Customer users are able to read and creates notes on their own tickets and, if enabled, company tickets.

**Comment by ikreb7** [comment]
Sorry, you are right. I solved the problem. Thank you very much for very fast support!
