### ISSUE TITLE
Bug - Login not possible on fresh installation

### ISSUE THREAD

**Issue by tune6688** [znuny/Znuny#7]
### Expected behaviour

Login should be possible

### Actual behavior

Used RPM to install and run installer.pl to finshed setup. 
Run localhost/otrs/index.pl with default username and password, clicked login button, but no responsed.
Please give me some advice on how to solve it
Thank you very much！

### How to reproduce

1. Used RPM to install and run installer.pl to finshed setup.
2. Run localhost/otrs/index.pl with default username and password, clicked login button, but no responsed.

### Environment

- OS: [centos7]
- Browser: [ Chrome, Firefox]
- OTRS version [e. g. 6.0.31]

### Additional information

Add any other information about the problem here.

**Comment by hanneshal** [comment]
This is probably related to issue #6 
This breaks the JS, which is needed for this:

Please let us know if this workaround, helps:
copy this to you Kernel/Config.pm

```
$Self->{'Loader::Enabled::JS'}   = 0;
```

**Comment by tune6688** [comment]
Thanks for your great help. Yes ,this is same to issue #6. can be solved with the same solution.
