### ISSUE TITLE
Bug - Missing queues in Overview top menu - AgentTicketQueue

### ISSUE THREAD

**Issue by darim92** [znuny/Znuny#70]
### Environment

- OS:           Windows 10
- Browser:      Chrome, Firefox
- Znuny version: 6.0.34

### Expected behaviour

In Znuny 6.0.33 we could go to the AgentTicketQueue Overview. (German: Tickets-->Ansicht nach Queues).
The top menu normaly shows all available queues, even if there is no new ticket in it. 
NormaIy I can navigate through the queues from the top menu.

### Actual behaviour

Now the queues are missing. They only show up in the top menu if a new Ticket is assigned.
On my Agent Dashboard is also a Queue Overview Widget. There I can see all queues.

The queues are not empty.  

### How to reproduce

Assign Ticket to a non empty queue.
Go to <otrs domain>/index.pl?Action=AgentTicketQueue
Close the new assigned ticket.
Go to <otrs domain>/index.pl?Action=AgentTicketQueue --> queue is disappeared from the top menu

**Comment by rkaldung** [comment]
Hi @darim92 Please let me know what the value of your system configuration setting Ticket::Frontend::AgentTicketQueue###HideEmptyQueues  is?

**Comment by darim92** [comment]
> Ticket::Frontend::AgentTicketQueue###HideEmptyQueues is?

It's not checked --> deactivated

**Comment by rkaldung** [comment]
Ok, I will setup a clean 6.0.33 to check. Any add-ons do you have installed?

**Comment by darim92** [comment]
> Ok, I will setup a clean 6.0.33 to check. Any add-ons do you have installed?

No add-ons. 

Logged in this morning and all queues are visible again like in 6.0.33. Maybe some background job fixed it?

**Comment by rkaldung** [comment]
@darim92 Could be a probably a probem with the cache (cache is deleted over the weekend) and can be fixed by rebuilding the command `bin/otrs.Console.pl Maint::Ticket::QueueIndexRebuild`

Was it a fresh installation or an update (from which version)?

**Comment by rkaldung** [comment]
@darim92 Sorry, I did not saw you said 6.0.34 and mentioned it worked in 6.0.33.

Did you run the migration script after the update?

**Comment by darim92** [comment]
@rkaldung Yes, we run the migration script after every update.

**Comment by rkaldung** [comment]
@darim92 Ok, that's a must have and I recognized many skip this. Please use the command above to fix issues with the queue view like you had.
