### ISSUE TITLE
ITSM Package shows Error Message for Repo

### ISSUE THREAD

**Issue by ghost** [znuny/Znuny#81]
### Environment

- OS:   Windows 10
- Browser:   Google Chrome 
- Znuny version: 6.0.34
### Expected behaviour
No error message.

### Actual behaviour
Error Message "No packages found in Repository".

### How to reproduce

1. Install ITSM GeneralCatalog
2. Install ITSM Core
3. Add Znuny ITSM Repo in the Systemconfiguration
4. Try to get the other packages for ITSM with the Repository
-> Error message
You are able to download the other extensions but the message will still exist.

### Additional information
No function issue, just a wrong reference to the old (offline?) Repo from OTRS instead of Znuny.

### Screenshots

Error Message
![image](https://user-images.githubusercontent.com/84412466/118715320-ca294300-b823-11eb-9b54-264478b16147.png)

**Comment by rkaldung** [comment]
Hi @OTECMarkus,

What exactly did you in your step 3? Did you changed/updated the system configuration 
Package::RepositoryList ?

**Comment by ghost** [comment]
Yes

**Comment by rkaldung** [comment]
That's the setting I tested:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/378324/118773730-63d50c80-b885-11eb-95d9-d89848a2353a.png">

The entry labeled 1 works, the one labeled 2 not.

Does your setting looks different?

**Comment by ghost** [comment]
I set it like labeld 1 and this works. If all Packages are installed, the "Error" Message is still there until you select another Repo and refresh. Away from this, is it posible to set per default the Znuny Repo instead of the OTRS Repo for the ITSM Packages?

**Comment by rkaldung** [comment]
@OTECMarkus The next release of the ITSM packages will solve this on a new installation. For existing setups this is planned to be fixed with the upcoming patch level.

The error message is existing behavior and we won't change this for the LTS branch.
