### ISSUE TITLE
Bug - Errors in System Log about missing PackageManagerCheckNotVerifiedPackages

### ISSUE THREAD

**Issue by arndkeyz** [znuny/Znuny#9]
### Expected behavior

Packages are working as intended.

### Actual behavior

Error in System Log about missing PackageManagerCheckNotVerifiedPackages module

### How to reproduce

- Clean install of Znuny 6.0.32
- Open System Log and see errors starting with Can't locate Kernel/Output/HTML/Notification PackageManagerCheckNotVerifiedPackages.pm.

### Screenshots

![image](https://user-images.githubusercontent.com/41154642/106616298-b2c49380-656d-11eb-93f9-43d522ec1813.png)

### Environment

    OS: Linux (Debian 10 (buster) x86_64)
    Browser: Firefox (78.7.0esr)
    Znuny 6.0.32

**Comment by rkaldung** [comment]
Hi @arndkeyz,

which archive did you use for the installation?

**Comment by arndkeyz** [comment]
https://download.znuny.org/releases/znuny-6.0.32.tar.gz

**Comment by rkaldung** [comment]
Hello @arndkeyz ,

I can't reproduce this. Because of this, two questions:

1) Please provide a screenshot of your package manager including version and
2) the content of your Apache error log (/var/log/apache2/error_log), the stack trace would be nice

**Comment by arndkeyz** [comment]
I do use a customized initial_setup.sql based on 6.0.30. That might be causing these errors.

![image](https://user-images.githubusercontent.com/41154642/106879740-d4dc2400-66db-11eb-9d2e-12761e9d9ef4.png)

```
ERROR: OTRS-CGI-98 Perl: 5.28.1 OS: linux Time: Thu Feb 4 10:15:36 2021

 Message: Can't locate Kernel/Output/HTML/Notification/PackageManagerCheckNotVerifiedPackages.pm in @INC (you may need to install the Kernel::Output::HTML::Notification::PackageManagerCheckNotVerifiedPackages module) (@INC contains: /usr/Custom /usr/Kernel/cpan-lib /usr /usr/sbin/../../Custom /usr/sbin/../../Kernel/cpan-lib /usr/sbin/../.. /opt/otrs/Custom /opt/otrs/Kernel/cpan-lib /opt/otrs/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /etc/apache2) at /opt/otrs/Kernel/System/Main.pm line 85.


 RemoteAddress: redacted
 RequestURI: /otrs/index.pl?Action=AdminLog

 Traceback (12090):
   Module: Kernel::Output::HTML::Layout::NavigationBar Line: 3264
   Module: Kernel::Modules::AdminLog::Run Line: 33
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 1135
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 38
   Module: (eval) (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 173
   Module: ModPerl::Registry::handler (v1.99) Line: 32
```

**Comment by rkaldung** [comment]
@arndkeyz That's for sure not a clean install.  I suggest your dump contains System Configuration settings? If yes, they probably should be gone after executing `bin/otrs.Console.pl Maint::Config::Rebuild --cleanup` as the OTRS user.

Please let me know if this solves the issues.

**Comment by arndkeyz** [comment]
It does. I should have realized that was the cause of the issue. 
Thanks for your help and sorry for wasting your time
