### ISSUE TITLE
Bug - orphaned daemon task pids not purged from DB

### ISSUE THREAD

**Issue by pboguslawski** [znuny/Znuny#97]
### Environment

- OS:           Linux
- Browser:      not important
- Znuny version: 6.0.35

### Expected behaviour

When ongoing daemon task is interrupted (i.e. system reboot during long ArticleSearchIndexRebuild after upgrade to Znuny 6) orphaned pid in DB should be cleaned automatically and not blocking new task executions. Now Znuny seems not celaning orphaned PIDs (waited over 12h without success) and job execution is blocked and alert mails are sent every minute.

### Actual behaviour

Znuny should purge orphaned PID record from DB as soon as it detects that process with this pid is no longer present is OS.

### How to reproduce

`mysql -e "insert into  process_id values('ArticleSearchIndexRebuild', 873, 'system.fqdn.here', 1624214644, 1624214644)" otrs`

### Additional information

Purging old PIDs was working in earlier OTRS versions (purging after some timeout as far as I remember which probably was dangerous - alive long living process may be purged).

Quick and dirty manual workaround to get rid of example orphaned PID=873:
`mysql -e 'delete from process_id where process_id=873' otrs `

**Comment by rkaldung** [comment]
Available in Znuny 7.0.19 and newer
