### ISSUE TITLE
Bug - Outdated Hyperlink in HTML Admin Manual Update Instructions

### ISSUE THREAD

**Issue by jtrumm** [znuny/Znuny#99]
### Environment

- OS:           Windows, Linux
- Browser:      Firefox
- Znuny version: 6.0.35]

### Expected behaviour

The link should point to: https://doc.znuny.org/doc/manual/developer/6.0/en/html/package-porting.html#packge-porting-5-to-6-configuration-files

### Actual behaviour

There is an outdated hyperlink in step 4 of the HTML Admin Manual Update Instructions https://doc.znuny.org/doc/manual/admin/6.0/en/html/updating.html

The link "converted to the new formats supported by OTRS 6" points to http://doc.otrs.com/doc/manual/developer/6.0/en/html/package-porting.html#packge-porting-5-to-6-configuration-files instead of https://doc.znuny.org/doc/manual/developer/6.0/en/html/package-porting.html#packge-porting-5-to-6-configuration-files

### How to reproduce

1. Go to https://doc.znuny.org/doc/manual/admin/6.0/en/html/updating.html
2. Scroll down to Step 4
3. Check the hyperlink "converted to the new formats supported by OTRS 6" in the first NOTE box

### Additional information

NA

### Screenshots

![Outdated Hyperlink in HTML Admin Manual Update Instructions Step 4](https://user-images.githubusercontent.com/5574410/123079911-a8bc0800-d41c-11eb-836b-a9cf61d7f0dd.png)

**Comment by jtrumm** [comment]
Please note there are further broken links in the documentation. Not sure if they should be added to this bug or better open a new one.

1. Link "OTRS Group" in the footer of all pages, for an example see https://doc.znuny.org/doc/manual/admin/6.0/en/html/index.html
2. Link "www.otrs.com" in section "The Simple Way - Installation of Pre-Built Packages" on page https://doc.znuny.org/doc/manual/admin/6.0/en/html/installation.html#installation-of-prepared-packages
3. Link "https://www.otrs.com/download-open-source-help-desk-software-otrs-free/" in section "Step 1: Install .tar.gz" on page https://doc.znuny.org/doc/manual/admin/6.0/en/html/manual-installation-of-otrs.html

**Comment by rkaldung** [comment]
@jtrumm The link you've posted first now point to the proper location. Regarding your other points:
1. is fixed, link removed
2. and 3. links now to the release overview

**Comment by rkaldung** [comment]
Just a note: we will release the documentation at GitHub to have the community involved. This will happen soon, around the release of Znuny 6.3
